#ifndef AGRemapCore_SanhuaExorcistThumbprints_H
#define AGRemapCore_SanhuaExorcistThumbprints_H

// ##### Credits

// ===== Anime Game Remap (AG Remap) =====
// Authors: Albert Gold#2696, NK#1321
//
// if you used it to remap your mods pls give credit for "Albert Gold#2696" and "Nhok0169"
// Special Thanks:
//   nguen#2011 (for support)
//   SilentNightSound#7430 (for internal knowdege so wrote the blendCorrection code)
//   HazrateGolabi#1364 (for being awesome, and improving the code)

// ##### EndCredits

#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>


namespace AGRemapCore {
    /**
     * @brief
     @rst
     The thumbprints of SanhuaExorcist's own textures (``Data/Mod Downloads/WuWa/SanhuaExorcist/2_5``),
     by hash -- see :cpp:member:`WWMIFixerConfig::textureThumbprints`. Generated by
     ``Tools/Misc/Diagnostics/wwmiTextureThumbs.py``
     @endrst
     */
    const std::unordered_map<std::string, std::vector<std::uint8_t>>& sanhuaExorcistTextureThumbprints();
}

#endif
