// ##### Credits

// ===== Anime Game Remap (AG Remap) =====
// Authors: Albert Gold#2696, NK#1321
//
// if you used it to remap your mods pls give credit for "Albert Gold#2696" and "Nhok0169"
// Special Thanks:
//   nguen#2011 (for support)
//   SilentNightSound#7430 (for internal knowdege so wrote the blendCorrection code)
//   HazrateGolabi#1364 (for being awesome, and improving the code)

// ##### EndCredits

// GENERATED by Tools/Misc/Docs/genConstantStrings.py from the core headers' doc comments; regenerate
// rather than hand-edit a docstring, so the two stay in step.

#include "PyConstantStrings.h"

#include <pybind11/stl.h>

#include "AGRemapCore/constants/FileExt.h"
#include "AGRemapCore/constants/FilePrefixes.h"
#include "AGRemapCore/constants/FileTypes.h"
#include "AGRemapCore/constants/IniGraphModObjKeywords.h"
#include "AGRemapCore/constants/IniKeywords.h"

namespace py = pybind11;
namespace AGRC = AGRemapCore;


void initCppConstantStrings(pybind11::module_ &m) {
    // Each class is a namespace of plain strings on both sides: `IniKeywords.Hash` is "hash" itself,
    // with no '.value' to read through, and is read-only from Python.
    py::class_<AGRC::FileExt>(m, "FileExt", R"doc(
Different file extensions for files
    )doc")
        .def_readonly_static("Ini", &AGRC::FileExt::Ini, py::doc(R"doc(
Initialization file extension
        )doc"))
        .def_readonly_static("Txt", &AGRC::FileExt::Txt, py::doc(R"doc(
Text file extension
        )doc"))
        .def_readonly_static("Buf", &AGRC::FileExt::Buf, py::doc(R"doc(
Buffer file extension
        )doc"))
        .def_readonly_static("DDS", &AGRC::FileExt::DDS, py::doc(R"doc(
`Direct Draw Surface`_ file extension
        )doc"));

    py::class_<AGRC::FilePrefixes>(m, "FilePrefixes", R"doc(
Prefixes this software puts on the files it renames
    )doc")
        .def_readonly_static("BackupFilePrefix", &AGRC::FilePrefixes::BackupFilePrefix, py::doc(R"doc(
What a disabled (backed-up) file's name is prefixed with
        )doc"))
        .def_readonly_static("DisabledPrefix", &AGRC::FilePrefixes::DisabledPrefix, py::doc(R"doc(
What a mod's own name is prefixed with to turn it OFF :raw-html:`<br />`
:raw-html:`<br />`

Not this software's convention but the ecosystem's: mod managers rename a folder or a
file this way, and so do modders by hand, so a mod library holds disabled ``.ini``
files, disabled variants inside a merged mod, and disabled copies of whole folders.
Matched case-insensitively -- ``DISABLED``, ``Disabled`` and ``disabled`` are all in
the wild :raw-html:`<br />` :raw-html:`<br />`

.. note::
   GIMI's hash-updating tools skip these, which is why a merged mod's disabled
   variants can still carry hashes several game versions old
        )doc"))
        .def_readonly_static("OldBackupFilePrefixV3", &AGRC::FilePrefixes::OldBackupFilePrefixV3, py::doc(R"doc(
What version 3 of this software prefixed a disabled (backed-up) file's name with
:raw-html:`<br />` :raw-html:`<br />`

Only ever *recognized*, never written -- a mod folder fixed by an old version of this
software can still hold one, and :meth:`RemapService.fix` has to know not to
treat it as a mod's own ``.ini`` file
        )doc"))
        .def_readonly_static("OldBackupFilePrefixV4_3", &AGRC::FilePrefixes::OldBackupFilePrefixV4_3, py::doc(R"doc(
What version 4.3 of this software prefixed a disabled (backed-up) file's name with --
recognized but never written, exactly as :attr:`OldBackupFilePrefixV3` is
        )doc"));

    py::class_<AGRC::FileTypes>(m, "FileTypes", R"doc(
Display names for the different types of files the software encounters :raw-html:`<br />`
:raw-html:`<br />`

These are **prose**,
not matching patterns -- the only thing that reads them is a message being written for a
person (:meth:`RemapService.reportSummary` and friends), which is why ``"*.ini file"``
carries a ``*`` that no file name ever does. Anything deciding what a file *is* uses
:class:`FileExt`/:class:`FilePrefixes`/:class:`FileSuffixes` instead
    )doc")
        .def_readonly_static("Default", &AGRC::FileTypes::Default, py::doc(R"doc(
Default file type
        )doc"))
        .def_readonly_static("Ini", &AGRC::FileTypes::Ini, py::doc(R"doc(
Initialization files
        )doc"))
        .def_readonly_static("Blend", &AGRC::FileTypes::Blend, py::doc(R"doc(
Blend.buf files
        )doc"))
        .def_readonly_static("Position", &AGRC::FileTypes::Position, py::doc(R"doc(
Position.buf files
        )doc"))
        .def_readonly_static("Texture", &AGRC::FileTypes::Texture, py::doc(R"doc(
Texture .dds files
        )doc"))
        .def_readonly_static("RemapBlend", &AGRC::FileTypes::RemapBlend, py::doc(R"doc(
RemapBlend.buf files created by this fix
        )doc"))
        .def_readonly_static("RemapPosition", &AGRC::FileTypes::RemapPosition, py::doc(R"doc(
RemapPosition.buf files created by this fix
        )doc"))
        .def_readonly_static("Log", &AGRC::FileTypes::Log, py::doc(R"doc(
The log file
        )doc"))
        .def_readonly_static("RemapTexture", &AGRC::FileTypes::RemapTexture, py::doc(R"doc(
RemapTex.dds files created by this fix
        )doc"))
        .def_readonly_static("RemapDownload", &AGRC::FileTypes::RemapDownload, py::doc(R"doc(
RemapDL download files created by this fix
        )doc"))
        .def_readonly_static("Texcoord", &AGRC::FileTypes::Texcoord, py::doc(R"doc(
Texcoord.buf files
        )doc"))
        .def_readonly_static("RemapTexcoord", &AGRC::FileTypes::RemapTexcoord, py::doc(R"doc(
RemapTexcoord.buf files created by this fix
        )doc"))
        .def_readonly_static("RemapBuf", &AGRC::FileTypes::RemapBuf, py::doc(R"doc(
Any other ``.buf`` file created by this fix -- the catch-all for the ``.buf`` half of
:meth:`RemapIniRemover.classifyResource`
        )doc"))
        .def_readonly_static("RemapOther", &AGRC::FileTypes::RemapOther, py::doc(R"doc(
A file of no recognized kind created by this fix -- the final catch-all of
:meth:`RemapIniRemover.classifyResource`
        )doc"));

    py::class_<AGRC::IniGraphModObjKeywords>(m, "IniGraphModObjKeywords", R"doc(
Keywords used as the *component* half of a :class:`IniGraphGroup.ModObj` for graphs that
don't belong to a real mod object :raw-html:`<br />` :raw-html:`<br />`

A :class:`IniGraphGroup` is keyed by ``(component, mod object)``, which works for the
graphs that really are one mod object's ``TextureOverride`` command chain. The group a parser
hands back also carries graphs that aren't -- the synthesized download-resource `sections`_ --
and those get a reserved component name instead, so they can never collide with a real
``(component, object)`` pair from the ``.ini`` file.
    )doc")
        .def_readonly_static("Download", &AGRC::IniGraphModObjKeywords::Download, py::doc(R"doc(
Marks a graph whose `sections`_ are download resources rather than a mod object's commands
        )doc"));

    py::class_<AGRC::IniKeywords>(m, "IniKeywords", R"doc(
Common keywords used in the .ini file :raw-html:`<br />` :raw-html:`<br />`

Bound to `Python`_ as ``IniKeywords``, each member a plain string. Add a member when a caller on
either side needs a keyword, rather than spelling the literal out where it is used
    )doc")
        .def_readonly_static("Resource", &AGRC::IniKeywords::Resource, py::doc(R"doc(
The starting prefix used for any `sections`_ that reference some file
        )doc"))
        .def_readonly_static("TextureOverride", &AGRC::IniKeywords::TextureOverride, py::doc(R"doc(
The starting prefix used for some `section`_ that overrides the resource of a mod
        )doc"))
        .def_readonly_static("CommandList", &AGRC::IniKeywords::CommandList, py::doc(R"doc(
The `section`_ prefix of a ``3dmigoto`` command list -- a `section`_ that is run by name
rather than matched against a draw
        )doc"))
        .def_readonly_static("This", &AGRC::IniKeywords::This, py::doc(R"doc(
The `KVP`_ key that overrides the resource the `section`_ itself matched
:raw-html:`<br />` :raw-html:`<br />`

A texture-only recolour is written with it -- ``hash`` names one of the game's textures
and ``this`` names what to draw in its place -- so a `section`_ carrying it binds no
register of its own
        )doc"))
        .def_readonly_static("ShaderOverride", &AGRC::IniKeywords::ShaderOverride, py::doc(R"doc(
The starting prefix used for some `section`_ that overrides a mod's shader
        )doc"))
        .def_readonly_static("Remap", &AGRC::IniKeywords::Remap, py::doc(R"doc(
The substring used to indicate a `section`_ is edited by this software
        )doc"))
        .def_readonly_static("Blend", &AGRC::IniKeywords::Blend, py::doc(R"doc(
The substring that usually occurs in the name of a `section`_ to indicate that the
`section`_ will call some ``*.Blend.buf`` file
        )doc"))
        .def_readonly_static("Position", &AGRC::IniKeywords::Position, py::doc(R"doc(
The substring that usually occurs in the name of a `section`_ to indicate that the
`section`_ will call some ``*.Position.buf`` file
        )doc"))
        .def_readonly_static("Texcoord", &AGRC::IniKeywords::Texcoord, py::doc(R"doc(
The substring that usually occurs in the name of a `section`_ to indicate that the
`section`_ will call some ``*.Texcoord.buf`` file
        )doc"))
        .def_readonly_static("RemapFix", &AGRC::IniKeywords::RemapFix, py::doc(R"doc(
The substring used to indicate that the `section`_ was created by this program
        )doc"))
        .def_readonly_static("RemapTex", &AGRC::IniKeywords::RemapTex, py::doc(R"doc(
The substring used to indicate that the `section`_ contains some edited/created texture
``*.RemapTex.dds`` file
        )doc"))
        .def_readonly_static("RemapDL", &AGRC::IniKeywords::RemapDL, py::doc(R"doc(
The substring used to indicate that the `section`_ contains some downloaded file from the internet
        )doc"))
        .def_readonly_static("RemapRef", &AGRC::IniKeywords::RemapRef, py::doc(R"doc(
The substring used to indicate that a resource `section`_ INSIDE a fix's block names a
file the fix did **not** write -- one of the mod's own, referenced by the fix
:raw-html:`<br />` :raw-html:`<br />`
An undo takes every section of the fix's block out and deletes every file those
sections name, which is right for a ``RemapBlend`` / ``RemapTex`` / ``RemapDL`` file the
fix produced and destroys the mod for a texture the fix merely bound (the WWMI fixer
binds a mod's textures by register, and a file no resource of the mod's own ``.ini``
names has to be declared somewhere). A section carrying this keyword is removed with
the block and its file is left alone -- see :meth:`RemapIniRemover.collectRemovedResources`
        )doc"))
        .def_readonly_static("Run", &AGRC::IniKeywords::Run, py::doc(R"doc(
The `KVP`_ key used to reference/call another `section`_
        )doc"))
        .def_readonly_static("Hash", &AGRC::IniKeywords::Hash, py::doc(R"doc(
The `KVP`_ key holding a `section`_'s model hash -- what
:class:`GIMISectionClassifier` looks a mod object up by
        )doc"))
        .def_readonly_static("MatchFirstIndex", &AGRC::IniKeywords::MatchFirstIndex, py::doc(R"doc(
The `KVP`_ key holding the first index of the model a `section`_ draws -- the second
half of what :class:`GIMISectionClassifier` looks a mod object up by, for the mod
objects a ``hash`` alone cannot tell apart
        )doc"))
        .def_readonly_static("MatchIndexCount", &AGRC::IniKeywords::MatchIndexCount, py::doc(R"doc(
The `KVP`_ key holding how many indices of the model a `section`_ draws
        )doc"))
        .def_readonly_static("MatchVertexCount", &AGRC::IniKeywords::MatchVertexCount, py::doc(R"doc(
The `KVP`_ key holding how many vertices the model a `section`_ draws has
        )doc"))
        .def_readonly_static("MatchPriority", &AGRC::IniKeywords::MatchPriority, py::doc(R"doc(
The `KVP`_ key breaking the tie when several `sections`_ match one draw
        )doc"))
        .def_readonly_static("FilterIndex", &AGRC::IniKeywords::FilterIndex, py::doc(R"doc(
The ``filter_index`` `KVP`_ key -- the value a shader's own draw writes into
     ``IniConstants``, which a remapped `section`_ matches on to tell one pass from another
        )doc"))
        .def_readonly_static("Array", &AGRC::IniKeywords::Array, py::doc(R"doc(
The ``array`` `KVP`_ key -- how many elements a buffer resource holds
        )doc"))
        .def_readonly_static("MatchType", &AGRC::IniKeywords::MatchType, py::doc(R"doc(
The `KVP`_ key holding which kind of draw call a `section`_ matches
        )doc"))
        .def_readonly_static("MatchKeys", &AGRC::IniKeywords::MatchKeys, py::doc(R"doc(
Every `KVP`_ key by which a `section`_ selects the draw it overrides
:raw-html:`<br />` :raw-html:`<br />`

These are what make a ``TextureOverride`` fire, so they are meaningful only where
3dmigoto is matching. A ``CommandList`` is *called*, never matched, so a fix that
copies a section's body into one drops these on the way -- carried across they say
nothing, and a stale ``hash`` in particular reads as a second claim on a draw the
fix has already remapped
        )doc"))
        .def_readonly_static("Filename", &AGRC::IniKeywords::Filename, py::doc(R"doc(
The `KVP`_ key naming the file a resource `section`_ points at :raw-html:`<br />`
:raw-html:`<br />`

.. note::
   Classes that edit `KVPs`_ generically take this as a ``K``-typed customization point
   instead (eg. :class:`BaseResEdit.ResEditConfig`'s ``filenameKey``), since ``K``
   is not ``std::string`` in the `pybind11`_ layer. This constant is for the
   plain-``std::string`` callers, and for keeping the one spelling in one place
        )doc"))
        .def_readonly_static("Ref", &AGRC::IniKeywords::Ref, py::doc(R"doc(
The prefix a register binding uses to name a resource `section`_ rather than a value --
``ps-t0 = ref ResourceFoo``. Strip it with
:meth:`IniNamingTools.removeRefPrefix` rather than by hand: it was written out at
seven sites across three files, one of them carrying the literal's LENGTH as a bare 4
        )doc"))
        .def_readonly_static("Type", &AGRC::IniKeywords::Type, py::doc(R"doc(
A resource `section`_'s kind, eg. ``type = Buffer``
        )doc"))
        .def_readonly_static("Stride", &AGRC::IniKeywords::Stride, py::doc(R"doc(
A resource `section`_'s bytes per element, eg. ``stride = 40``
        )doc"))
        .def_readonly_static("Format", &AGRC::IniKeywords::Format, py::doc(R"doc(
A resource `section`_'s element format, eg. ``format = R32_UINT``
        )doc"))
        .def_readonly_static("Null", &AGRC::IniKeywords::Null, py::doc(R"doc(
The value a `KVP`_ carries to mean "nothing at all" -- a ``filename =`` naming this is
a placeholder, not a real resource
        )doc"))
        .def_readonly_static("Ib", &AGRC::IniKeywords::Ib, py::doc(R"doc(
The `KVP`_ key naming a `section`_'s index buffer -- also the last index column of the
:class:`Hashes` row holding that buffer's hash
        )doc"))
        .def_readonly_static("Vb0", &AGRC::IniKeywords::Vb0, py::doc(R"doc(
The `KVP`_ key naming a `section`_'s position vertex buffer
        )doc"))
        .def_readonly_static("Vb1", &AGRC::IniKeywords::Vb1, py::doc(R"doc(
The `KVP`_ key naming a `section`_'s blend **or** texcoord vertex buffer -- which of
the two it is depends on the `section`_, not on the key
        )doc"))
        .def_readonly_static("Handling", &AGRC::IniKeywords::Handling, py::doc(R"doc(
The `KVP`_ key controlling how a draw call is handled -- ``skip`` is the only value
this software writes, alongside :attr:`Draw`, after a downloaded ``Blend.buf``
        )doc"))
        .def_readonly_static("Draw", &AGRC::IniKeywords::Draw, py::doc(R"doc(
The `KVP`_ key issuing a non-indexed draw, written as ``<vertex count>,0`` -- the pair
:attr:`Handling` completes after a downloaded ``Blend.buf``
        )doc"))
        .def_readonly_static("DrawIndexed", &AGRC::IniKeywords::DrawIndexed, py::doc(R"doc(
The `KVP`_ key that actually draws a model. What a texture fix has to be issued in
front of -- see :class:`RegDelimitedAdd`
        )doc"))
        .def_readonly_static("ORFixPath", &AGRC::IniKeywords::ORFixPath, py::doc(R"doc(
The sub-command call to `ORFix`_ (Outline Reflection Fix) :raw-html:`<br />`
:raw-html:`<br />`

One of the two fixes shipped by an external ``3dmigoto`` library that work around
textures the game breaks each version. A ``run =`` naming this is a call into that
library, not into the mod's own `sections`_
        )doc"))
        .def_readonly_static("NNFixPath", &AGRC::IniKeywords::NNFixPath, py::doc(R"doc(
The sub-command call to ``NNFix`` (No Normal Fix) -- the other half of the same
external library as :attr:`ORFixPath` :raw-html:`<br />` :raw-html:`<br />`

.. note::
   It lives under the library's ``ORFix`` folder, **not** an ``NNFix`` one. That
   asymmetry is the library's, not a typo here
        )doc"))
        .def_readonly_static("GIMISetTexturesPath", &AGRC::IniKeywords::GIMISetTexturesPath, py::doc(R"doc(
GIMI's own texture helper, ``CommandList\GIMI\SetTextures`` -- ORFix reading
:attr:`GIMINormalMap` / :attr:`GIMIDiffuse` / :attr:`GIMILightMap`
instead of ``ps-t0`` / ``ps-t1`` / ``ps-t2``. A mod's use of it is rewritten into the
traditional API as it is read -- see :class:`GIMIApiNormalizer`
        )doc"))
        .def_readonly_static("GIMINormalMap", &AGRC::IniKeywords::GIMINormalMap, py::doc(R"doc(
The normal map key of GIMI's texture API -- read as ``ps-t0``, see :attr:`GIMISetTexturesPath`
        )doc"))
        .def_readonly_static("GIMIDiffuse", &AGRC::IniKeywords::GIMIDiffuse, py::doc(R"doc(
The diffuse key of GIMI's texture API -- read as ``ps-t1``, see :attr:`GIMISetTexturesPath`
        )doc"))
        .def_readonly_static("GIMILightMap", &AGRC::IniKeywords::GIMILightMap, py::doc(R"doc(
The light map key of GIMI's texture API -- read as ``ps-t2``, see :attr:`GIMISetTexturesPath`
        )doc"))
        .def_readonly_static("TexFxFolder", &AGRC::IniKeywords::TexFxFolder, py::doc(R"doc(
The folder holding the `TexFx`_ external library's sub-commands :raw-html:`<br />`
:raw-html:`<br />`

A third addon alongside ORFix and NNFix, and the one that gives textures capabilities
the importer does not have on its own -- most visibly making parts of a model look
transparent. What each channel of an input texture means is documented on its own
GitHub rather than here :raw-html:`<br />` :raw-html:`<br />`

It owns **two dedicated registers**, ``ps-t69`` and ``ps-t70``, which is why a fix that
shifts a character's registers around leaves those two alone
        )doc"))
        .def_readonly_static("PsT69", &AGRC::IniKeywords::PsT69, py::doc(R"doc(
The first of `TexFx`_'s two dedicated registers :raw-html:`<br />` :raw-html:`<br />`

A modder opts into TexFx by binding these, which is what makes the library optional
where NNFix and ORFix are mandatory -- so a fix issues a TexFx sub-command only where
one of them is actually bound, never simply because the character's row names one
        )doc"))
        .def_readonly_static("PsT70", &AGRC::IniKeywords::PsT70, py::doc(R"doc(
The second of `TexFx`_'s two dedicated registers -- see :attr:`PsT69`
        )doc"))
        .def_readonly_static("TexFxTransparency0", &AGRC::IniKeywords::TexFxTransparency0, py::doc(R"doc(
`TexFx`_'s transparency sub-command for a diffuse living on ``ps-t0``, GI 5.0 and later
:raw-html:`<br />` :raw-html:`<br />`

The call names the register the diffuse is on, so which of these two a fix issues
follows from where its register shift left the diffuse -- not from the character
        )doc"))
        .def_readonly_static("TexFxTransparency1", &AGRC::IniKeywords::TexFxTransparency1, py::doc(R"doc(
`TexFx`_'s transparency sub-command for a diffuse living on ``ps-t1`` -- see
:attr:`TexFxTransparency0`
        )doc"))
        .def_readonly_static("TexFxTransparency0Pre5_0", &AGRC::IniKeywords::TexFxTransparency0Pre5_0, py::doc(R"doc(
The PRE-5.0 spelling of :attr:`TexFxTransparency0` -- ``T.0`` rather than ``TN.0``
:raw-html:`<br />` :raw-html:`<br />`

The same sub-command, which `TexFx`_ itself renamed at 5.0. A fix transcribed from a
4.x row has to issue THIS one: the two are not interchangeable, and issuing the 5.0
name names a sub-command that library does not have -- which surfaces as an effect
that quietly does nothing rather than as an error
        )doc"))
        .def_readonly_static("TexFxTransparency1Pre5_0", &AGRC::IniKeywords::TexFxTransparency1Pre5_0, py::doc(R"doc(
The PRE-5.0 spelling of :attr:`TexFxTransparency1` -- see :attr:`TexFxTransparency0Pre5_0`
        )doc"))
        .def_readonly_static("HashNotFound", &AGRC::IniKeywords::HashNotFound, py::doc(R"doc(
Written in place of a ``hash`` that has no mapping onto the mod being fixed to --
see :class:`RegAssetRemap`
        )doc"))
        .def_readonly_static("IndexNotFound", &AGRC::IniKeywords::IndexNotFound, py::doc(R"doc(
Written in place of a ``match_first_index`` that has no mapping onto the mod being
fixed to -- the index counterpart of :attr:`HashNotFound`
        )doc"))
        .def_readonly_static("HideOriginalComment", &AGRC::IniKeywords::HideOriginalComment, py::doc(R"doc(
The comment marker used to hide (comment out) a previously-fixed original `section`_
        )doc"));
}
