#
# ===== neuvilletteMelusentSynth =====
#
#   py -3 neuvilletteMelusentSynth.py [out folder]      (default: ./synth; GIMI's folder is hard-coded below)
#
# Synthetic NeuvilletteMelusent mods for the reverse direction's structural axes (there are few real ones), built
# from PRISTINE copies of the identity mod and NeuvilletteMelusent1 (fix block and generated files stripped):
#   SynthMerged    a genshin_merge_mods.py master of two variants: the identity, and NeuvilletteMelusent1's mesh
#                  (no Coat of its own -> downloads in that branch)
#   SynthRecolour  a texture-only recolour (NeuvilletteMelusent1's tex.ini alone), its hair tinted pink
#   SynthNoEye     the identity with its whole Eye component removed
#   Synth16        the identity with every index buffer 16-bit (R16_UINT)
import os, re, shutil, struct, subprocess, sys
GIMI = r"E:\Computer\Games\Wuthering Waves Mods\Importer\GIMI"
Out = os.path.abspath(sys.argv[1]) if len(sys.argv) > 1 else os.path.join(os.getcwd(), "synth")
Merge = os.path.join(GIMI, "Neuvillette5", "genshin_merge_mods.py")
Repo = os.environ.get("AG_REMAP_REPO") or r"E:\Computer\Games\Genshin\Repos\Repos\Fix-Raiden-Boss"
APISrc = os.path.join(Repo, "Anime Game Remap (for all users)", "api", "src", "py")
sys.path.insert(0, APISrc); os.add_dll_directory(os.path.join(APISrc, "FixRaidenBoss2"))
import FixRaidenBoss2 as FRB

def find(name):
    for base in (GIMI, os.path.join(GIMI, "Mods")):
        if os.path.isdir(os.path.join(base, name)):
            return os.path.join(base, name)
    raise SystemExit("no " + name)

def pristine(src, dst, drop = ()):
    shutil.copytree(src, dst)
    for f in os.listdir(dst):
        p = os.path.join(dst, f)
        if "Remap" in f or f in drop or f.startswith(".mod"):
            os.remove(p); continue
        if f.lower().endswith(".ini"):
            t = open(p, "rb").read().decode("utf-8")
            i = t.find("; --------------- NeuvilletteMelusent Remap")
            if i >= 0:
                # the fix's boilerplate starts a few comment lines above its heading
                head = t[:i]
                j = head.rfind("; .ini generated by")
                t = head[:j] if j >= 0 else head
            open(p, "wb").write(t.rstrip().encode("utf-8") + b"\r\n")

shutil.rmtree(Out, ignore_errors = True); os.makedirs(Out)
identity, m1 = find("NeuvilletteMelusentIdentity"), find("NeuvilletteMelusent1")

# ---- SynthMerged ----
merged = os.path.join(Out, "NeuvilletteMelusentSynthMerged")
os.makedirs(merged)
pristine(identity, os.path.join(merged, "A"))
pristine(m1, os.path.join(merged, "B"), drop = ("tex.ini",))
# its four orphan Coat resources name files the mod does not ship, which the merge script cannot copy
q = os.path.join(merged, "B", "NeuvilletteMelusent.ini")
tb = open(q, "rb").read().decode("utf-8").replace("\r\n", "\n")
tb = "".join(s for s in re.split(r"(?m)^(?=\[)", tb) if not s.startswith("[ResourceNeuvilletteMelusentCoat"))
open(q, "wb").write(tb.replace("\n", "\r\n").encode("utf-8"))
r = subprocess.run([sys.executable, Merge, "-r", ".", "-k", "j"], input = "\n", capture_output = True, text = True, cwd = merged)
print("merge:", r.returncode, r.stdout[-200:].strip().replace("\n", " | "), r.stderr[-300:])

# ---- SynthRecolour ----
recolour = os.path.join(Out, "NeuvilletteMelusentSynthRecolour")
os.makedirs(recolour)
for f in os.listdir(m1):
    if f == "tex.ini" or f.lower().endswith(".dds") and "Remap" not in f:
        shutil.copy(os.path.join(m1, f), recolour)
pristine_tex = os.path.join(recolour, "tex.ini")
t = open(pristine_tex, "rb").read().decode("utf-8")
i = t.find("; .ini generated by XXMI")
k = t.find("; --------------- NeuvilletteMelusent Remap")
if k >= 0:
    t = t[:t.rfind("; .ini generated by", 0, k)] if t.rfind("; .ini generated by", 0, k) > i else t[:k]
open(pristine_tex, "wb").write(t.rstrip().encode("utf-8") + b"\r\n")
tex = FRB.CppTextureFile(os.path.join(recolour, "NeuvilletteMelusentHeadDiffuse.dds"))
tex.open()
px = bytearray(tex.getPixels())
for n in range(0, len(px), 4):
    px[n] = min(255, px[n] + 90); px[n + 1] = px[n + 1] * 3 // 5
tex.setPixels(bytes(px), tex.width, tex.height)
tex.save(compress = False)

# ---- SynthNoEye ----
noEye = os.path.join(Out, "NeuvilletteMelusentSynthNoEye")
pristine(identity, noEye)
for f in os.listdir(noEye):
    if f.startswith("NeuvilletteMelusentEye"):
        os.remove(os.path.join(noEye, f))
p = os.path.join(noEye, "NeuvilletteMelusent.ini")
t = open(p, "rb").read().decode("utf-8").replace("\r\n", "\n")
parts = re.split(r"(?m)^(?=\[)", t)
t = "".join(s for s in parts if not re.match(r"\[(TextureOverride|Resource)NeuvilletteMelusentEye", s))
open(p, "wb").write(t.replace("\n", "\r\n").encode("utf-8"))

# ---- Synth16 ----
s16 = os.path.join(Out, "NeuvilletteMelusentSynth16")
pristine(identity, s16)
for f in os.listdir(s16):
    if f.endswith(".ib"):
        q = os.path.join(s16, f); d = open(q, "rb").read()
        idx = struct.unpack(f"<{len(d)//4}I", d); assert max(idx) < 65536
        open(q, "wb").write(struct.pack(f"<{len(idx)}H", *idx))
p = os.path.join(s16, "NeuvilletteMelusent.ini")
t = open(p, "rb").read().decode("utf-8")
n = t.count("DXGI_FORMAT_R32_UINT")
open(p, "wb").write(t.replace("DXGI_FORMAT_R32_UINT", "DXGI_FORMAT_R16_UINT").encode("utf-8"))
print("16-bit formats rewritten:", n)
for d in sorted(os.listdir(Out)):
    print(d, sorted(x for x in os.listdir(os.path.join(Out, d)) if x.endswith(".ini") or os.path.isdir(os.path.join(Out, d, x))))
