##### Credits

# ===== Anime Game Remap (AG Remap) =====
# Authors: Albert Gold#2696, NK#1321
#
# if you used it to remap your mods pls give credit for "Albert Gold#2696" and "Nhok0169"
# Special Thanks:
#   nguen#2011 (for support)
#   SilentNightSound#7430 (for internal knowdege so wrote the blendCorrection code)
#   HazrateGolabi#1364 (for being awesome, and improving the code)

##### EndCredits

# The REVERSE direction's oracle: prototype vs compiled on every CitlaliWhisperofStars mod.
# Fixes two fresh scratch copies of each -- one through citlaliFromWhisperFix.py's overrides, one
# through the compiled tables with no override at all -- then compares the .ini semantically and
# every generated .buf/.ib/.dds by CONTENT (their names differ only by suffix).
#   py -3.9 abCitlaliRev.py [mod ...]
import collections, hashlib, os, shutil, subprocess, sys
Repo = r"E:\Computer\Games\Genshin\Repos\Repos\Fix-Raiden-Boss"
G = r"E:\Computer\Games\Wuthering Waves Mods\Importer\GIMI"
B = r"C:\Users\3dark\AGRemapBuild\citRev"
Proto = os.path.join(Repo, "Tools", "Misc", "Prototypes", "citlaliFromWhisperFix.py")
env = dict(os.environ, PYTHONIOENCODING = "utf-8")

# --noDownload makes the comparison DETERMINISTIC: a download that fails to land changes the band
# output, so the two sides otherwise differ over a file neither config chose -- on a different mod
# each run. Compare with it on to judge the CONFIG, and without it to exercise the download path.
noDownload = "--noDownload" in sys.argv
downloadArg = ', downloadMode = "disabled"' if noDownload else ""
mods = [a for a in sys.argv[1:] if not a.startswith("--")] or \
       ["CitlaliWhisperofStarsIdentity", "CitlaliWhisper1", "CitlaliWhisper2",
        "CitlaliWhisper3", "CitlaliWhisper4", "CitlaliWhisper5"]

def src(m):
    for p in (os.path.join(G, m), os.path.join(G, "Mods", m)):
        if os.path.isdir(p):
            return p
    raise SystemExit(f"no mod {m}")

def generated(root):
    out = collections.Counter()
    for d, _, fs in os.walk(root):
        for f in fs:
            low = f.lower()
            if low.endswith((".buf", ".ib", ".dds")) and "remap" in low:
                out[hashlib.md5(open(os.path.join(d, f), "rb").read()).hexdigest()] += 1
    return out

worst = 0
for m in mods:
    proto, comp = os.path.join(B, "proto", m), os.path.join(B, "comp", m)
    for p in (proto, comp):
        shutil.rmtree(p, ignore_errors = True)
        shutil.copytree(src(m), p)

    protoArgs = [sys.executable, Proto, proto] + (["--download", "disabled"] if noDownload else [])
    r = subprocess.run(protoArgs, capture_output = True, text = True, env = env)
    r2 = subprocess.run([sys.executable, "-c", f"""
import os, sys
Api = r"{Repo}\\Anime Game Remap (for all users)\\api\\src\\py"
sys.path.insert(0, Api); os.add_dll_directory(os.path.join(Api, "FixRaidenBoss2"))
import FixRaidenBoss2 as FRB
FRB.CppStrategyOverrides.clear()
s = FRB.RemapService(path = r"{comp}", keepBackups = False{downloadArg}); s.fix()
print("compiled: .ini fixed", len(s.stats.ini.fixed), "skipped", len(s.stats.ini.skipped), dict(s.stats.ini.skipped))
"""], capture_output = True, text = True, env = env)

    print(f"===== {m}")
    print("  prototype: " + next((l for l in r.stdout.splitlines() if l.startswith(".ini fixed")), r.stderr[-300:]))
    print("  " + (r2.stdout.strip() or r2.stderr[-400:]))

    a = subprocess.run([sys.executable, os.path.join(Repo, "Tools", "Misc", "Diagnostics", "abIni.py"), proto, comp],
                       capture_output = True, text = True, env = env)
    diffs = [l for l in a.stdout.splitlines() if not l.startswith("  ok")]
    print("\n".join("  " + l for l in diffs[-30:]))

    # JUDGE BY THE DIFF, NOT BY abIni's EXIT CODE. It also exits non-zero for "no remap block -- the
    # fix did not run on it", which one of these mods has legitimately: a shared Face.ini carrying
    # none of the skin's hashes. That is a fact about the MOD, true of both sides, and reporting it
    # as a prototype-vs-compiled difference made a clean A/B read as a failure.
    differs = any(("DIFF" in l or "PROBLEMS" in l) for l in a.stdout.splitlines())

    gp, gc = generated(proto), generated(comp)
    print(f"  generated by content: prototype {sum(gp.values())}, compiled {sum(gc.values())}, "
          f"only prototype {sum((gp - gc).values())}, only compiled {sum((gc - gp).values())}")
    worst = max(worst, int(differs), int(gp != gc))

print("\nA/B", "CLEAN" if worst == 0 else "DIFFERS")
sys.exit(worst)
