#
# ===== wwmiTextureThumbs =====
#
# Generates the texture THUMBPRINT table a compiled WWMI fixer identifies a mod's textures with: for
# every game texture in a download folder, a 16 x 16 grayscale box average of the decoded pixels,
# emitted as a C++ source file. The fixer computes the same thumbprint of a mod file that carries no
# hash and correlates it against these (>= 0.97 with one, < 0.90 with every other = that texture),
# which is how `Component6_Diffuse.dds` of one mod is placed as the ps-t5 ramp its pixels say it is
# rather than the iris its name says. Measured against the full-size colour correlation on 19 files
# of the cloak mod: the same decision on every one (2026-09-19).
#
#   python wwmiTextureThumbs.py <Data/Mod Downloads/WuWa/<Name>/<ver>> --name Sanhua --out <core>/src/data/IniFixData/Sanhua/SanhuaThumbprints.cpp
#
# The arithmetic here and in WWMIFixer.cpp (thumbprintOf) must stay identical: the decoded RGBA8
# buffer's (r + g + b) / 3 per pixel, box-averaged over blocks of (width / 16) x (height / 16)
# pixels, rounded to the nearest integer. Needs the API's Python (`py -3` here) for the decode.
#

import argparse
import os
import re
import sys

import numpy as np

Repo = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
sys.path.insert(0, os.path.join(Repo, "Anime Game Remap (for all users)", "api", "src", "py"))
if (hasattr(os, "add_dll_directory")):
    os.add_dll_directory(os.path.join(Repo, "Anime Game Remap (for all users)", "api", "src", "py", "FixRaidenBoss2"))

import FixRaidenBoss2 as FRB     # noqa: E402

DownloadName = re.compile(r"Texture([0-9a-f]{8})\.dds$", re.IGNORECASE)
Size = 16


def thumbprint(path, size = Size):
    tex = FRB.TextureFile(path)
    tex.open()
    if (not tex.hasImage):
        return None
    w, h = tex.width, tex.height
    if (w < size or h < size):
        return None
    px = np.frombuffer(tex.getPixels(), dtype = np.uint8).reshape(h, w, 4)[..., :3].astype(np.float64)
    gray = px.sum(axis = 2) / 3.0
    bw, bh = w // size, h // size
    gray = gray[:bh * size, :bw * size]
    thumb = gray.reshape(size, bh, size, bw).mean(axis = (1, 3))
    return np.clip(np.rint(thumb), 0, 255).astype(int).ravel().tolist()


def main():
    parser = argparse.ArgumentParser(description = "generate the texture thumbprint table of a WWMI character's download folder, as C++")
    parser.add_argument("folder", help = "Data/Mod Downloads/WuWa/<Name>/<ver>")
    parser.add_argument("--name", required = True, help = "the character, eg. Sanhua -- names the function")
    parser.add_argument("--out", required = True, help = "the .cpp file to write")
    args = parser.parse_args()

    rows = []
    for f in sorted(os.listdir(args.folder)):
        m = DownloadName.search(f)
        if (not m):
            continue
        t = thumbprint(os.path.join(args.folder, f))
        if (t is None):
            print(f"  skipped {f} (undecodable or too small)")
            continue
        rows.append((m.group(1).lower(), t))
        print(f"  {m.group(1).lower()}: {f}")

    header = os.path.splitext(os.path.basename(args.out))[0]
    lines = [f'#include "AGRemapCore/data/IniFixData/{args.name}/{header}.h"', "",
             "// ##### Credits", "", "// ===== Anime Game Remap (AG Remap) =====", "// Authors: Albert Gold#2696, NK#1321", "//",
             '// if you used it to remap your mods pls give credit for "Albert Gold#2696" and "Nhok0169"', "// Special Thanks:",
             "//   nguen#2011 (for support)", "//   SilentNightSound#7430 (for internal knowdege so wrote the blendCorrection code)",
             "//   HazrateGolabi#1364 (for being awesome, and improving the code)", "", "// ##### EndCredits", "",
             "// GENERATED by Tools/Misc/Diagnostics/wwmiTextureThumbs.py from the character's download folder -- do not edit by hand.",
             f"// {len(rows)} textures, each a {Size} x {Size} grayscale box average of the game's own file (see the script for the arithmetic).", "",
             "#include <cstdint>", "#include <string>", "#include <unordered_map>", "#include <vector>", "", "",
             "namespace AGRemapCore {",
             f"    const std::unordered_map<std::string, std::vector<std::uint8_t>>& {args.name[0].lower() + args.name[1:]}TextureThumbprints() {{",
             "        static const std::unordered_map<std::string, std::vector<std::uint8_t>> thumbprints = {"]
    for h, t in rows:
        chunks = [", ".join(str(v) for v in t[i:i + Size]) for i in range(0, len(t), Size)]
        lines.append(f'            {{"{h}", {{')
        for c in chunks:
            lines.append(f"                {c},")
        lines.append("            }},")
    lines += ["        };", "", "        return thumbprints;", "    }", "}", ""]
    with open(args.out, "w", encoding = "utf-8", newline = "\r\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {args.out}: {len(rows)} thumbprints")


if (__name__ == "__main__"):
    main()
