import sys
import os
import shutil
import copy
from typing import List, Optional
from ordered_set import OrderedSet

from .constants.Paths import UtilitiesPath
from .tools.ProjectPathTools import ProjectPathTools

sys.path.insert(1, UtilitiesPath)
from Utils.python.PyFile import PyFile
from Utils.python.FromImport import FromImport
from Utils.path.PyPathTools import PyPathTools
from Utils.path.ModulePathTools import ModulePathTools
from Utils.enums.ScriptPartNames import ScriptPartNames
from Utils.softwareStats.SoftwareMetadata import SoftwareMetadata
from Utils.softwareStats.BuildMetadata import BuildMetadata
from Utils.FileTools import FileTools
from Utils.toolStatsUpdater.TomlUpdater import TomlUpdater
from Utils.toml.TomlFile import TomlFile
from Utils.constants.BoilerPlate import Credits, MirrorPreamble, APIMirrorPreambleStats
from Utils.constants.toolStats import APIMirrorBuilderBuildStats
from Utils.constants.StrReplacements import VersionReplace, RanDateTimeReplace, BuildHashReplace, RanHashReplace, BuiltDateTimeReplace


BuildSystemSection = "build-system"
BuildBackendKey = "build-backend"
ProjectSection = "project"
ProjectUrlsSection = "project.urls"

# the sections the mirror's pyproject.toml is made out of. Any other section that the mirror's .toml
#   happens to have is dropped -- most of what the API's .toml carries describes how to compile the
#   API's C++/Cython sources, and none of that belongs in a pure python package
MirrorSections = [BuildSystemSection, ProjectSection, ProjectUrlsSection]

# the [project] keys the mirror inherits from the API, in the order they get written.
#   'name', 'version' and 'dependencies' are deliberately absent -- those describe the mirror itself
#   and get filled in from the mirror's own metadata instead
MirroredProjectKeys = ["authors", "description", "readme", "requires-python", "classifiers",
                       "keywords", "license", "license-files", "maintainers"]

# the mirror is a pure python package, so it gets a pure python build backend rather than the API's
PurePythonBuildSystem = ['requires = ["setuptools"]', 'build-backend = "setuptools.build_meta"']


class APIMirrorBuilder():
    def __init__(self, apiFolder: str, mirrorFolder: str, rootModule: str, apiStats: SoftwareMetadata, apiMirrorStats: SoftwareMetadata,
                 apiProjectFolder: Optional[str] = None, mirrorProjectFolder: Optional[str] = None):
        self._module = ModulePathTools.dirname(rootModule)

        self._apiFolder = FileTools.parseOSPath(apiFolder)
        self._apiInitPath = PyPathTools.getInitPath(apiFolder)
        self._apiMainPath = PyPathTools.getMainPath(apiFolder)
        self._apiProjectFolder = self._getProjectFolder(self._apiFolder, apiProjectFolder)

        self._mirrorFolder = FileTools.parseOSPath(mirrorFolder)
        self._mirrorInitPath = PyPathTools.getInitPath(mirrorFolder)
        self._mirrorMainPath = PyPathTools.getMainPath(mirrorFolder)
        self._mirrorProjectFolder = self._getProjectFolder(self._mirrorFolder, mirrorProjectFolder)

        self._apiStats = apiStats
        self._apiMirrorStats = apiMirrorStats

        self._mirrorBuildStats = BuildMetadata.fromSoftwareMetadata(apiMirrorStats)
        self._mirrorBuilderBuildStats = copy.deepcopy(APIMirrorBuilderBuildStats)
        self._mirrorBuildStats.refresh()
        self._mirrorBuilderBuildStats.refresh()

        self.preamble = self.getPreamble()


    # _getProjectFolder(packageFolder, projectFolder): Retrieves the folder holding a project's
    #   pyproject.toml, LICENSE and README
    #
    # note: the API's package and the mirror's package are no longer the same number of folders deep,
    #   so the old 'two parents above the package' guess only ever worked for one of them
    def _getProjectFolder(self, packageFolder: str, projectFolder: Optional[str] = None) -> str:
        if (projectFolder is not None):
            return FileTools.parseOSPath(projectFolder)

        return os.path.dirname(os.path.dirname(packageFolder))


    # getPreamble(): Retrieves the preamble text for the files generated by this builder
    def getPreamble(self) -> str:
        generationNote = MirrorPreamble.replace(VersionReplace, self._mirrorBuilderBuildStats.version)
        generationNote = generationNote.replace(RanDateTimeReplace, self._mirrorBuilderBuildStats.getFormattedDatetime())
        generationNote = generationNote.replace(RanHashReplace, self._mirrorBuilderBuildStats.buildHash)

        mirrorStats = APIMirrorPreambleStats.replace(VersionReplace, self._mirrorBuildStats.version)
        mirrorStats = mirrorStats.replace(BuiltDateTimeReplace, self._mirrorBuildStats.getFormattedDatetime())
        mirrorStats = mirrorStats.replace(BuildHashReplace, self._mirrorBuildStats.buildHash)

        result = f"{generationNote}{Credits}"[:-1]
        result += mirrorStats
        return result


    def buildMirrorInit(self):
        file = PyFile(self._apiInitPath, self._module)
        file.read()

        allObjects = file.getLocalObjects()
        fromImport = FromImport(self._apiStats.name, objects = allObjects)
        
        # get the __all__ text for the init file
        allModulesTxt = "__all__ = ["
        allObjects = map(lambda ob: f'"{ob}"', allObjects)
        allModulesTxt += ", ".join(allObjects)
        allModulesTxt += "]"

        print(f"Creating __init__.py")
        initTxt = f"{self.preamble}{fromImport.toStr()}\n\n{allModulesTxt}"
        mirrorInitFile = PyFile(self._mirrorInitPath, self._module)
        mirrorInitFile.write(initTxt)

    def buildMirrorMain(self):
        file = PyFile(self._apiMainPath, self._module)
        file.read()

        fromImport = FromImport(self._apiStats.name, objects = OrderedSet([ScriptPartNames.MainFunc.value]))

        print(f"Creating __main__.py")
        mainTxt = f"{self.preamble}{fromImport.toStr()}\n\n{file.getScriptStr()}"
        scriptMainFile = PyFile(self._mirrorMainPath, self._module)
        scriptMainFile.write(mainTxt)

    # getSectionKeyLines(toml, section): Retrieves the lines for only the 'key = value' assignments
    #   of a section
    #
    # note: a section's body runs all the way to the next section's header, so it also carries the
    #   blank lines and the comment block that introduce that next section. Those belong to whatever
    #   comes next rather than to this section, and must not be copied along with it
    def getSectionKeyLines(self, toml: TomlFile, section: str) -> List[str]:
        result = []
        for keyLines in toml.getKeys(section).values():
            result += keyLines

        while (result and (not result[-1].strip() or result[-1].lstrip().startswith("#"))):
            result.pop()

        return result


    # getMirrorBuildSystem(apiToml, mirrorToml): Retrieves the [build-system] section for the mirror
    #
    # note: the mirror keeps whatever pure python backend it already had, but never the API's own --
    #   the API compiles C++ and Cython sources, and a mirror that inherited that backend would try to
    #   run CMake over sources it does not have
    def getMirrorBuildSystem(self, apiToml: TomlFile, mirrorToml: TomlFile) -> List[str]:
        if (mirrorToml.getSection(BuildSystemSection) is None):
            return list(PurePythonBuildSystem)

        apiBackend = apiToml.getKey(BuildSystemSection, BuildBackendKey)
        mirrorBackend = mirrorToml.getKey(BuildSystemSection, BuildBackendKey)

        if (mirrorBackend is not None and mirrorBackend == apiBackend):
            print(f"  the mirror's {BuildBackendKey} is the API's own -- resetting it back to a pure python one")
            return list(PurePythonBuildSystem)

        return self.getSectionKeyLines(mirrorToml, BuildSystemSection)


    # getMirrorProject(apiToml): Retrieves the [project] section for the mirror, out of the parts of
    #   the API's [project] section that describe the software rather than how it is built
    def getMirrorProject(self, apiToml: TomlFile) -> List[str]:
        result = [f'name = "{self._apiMirrorStats.name}"']

        if (self._apiMirrorStats.version is not None):
            result.append(f'version = "{self._apiMirrorStats.version}"')

        for key in MirroredProjectKeys:
            keyLines = apiToml.getKey(ProjectSection, key)
            if (keyLines is not None):
                result += keyLines

        return result


    # buildMirrorConfig(): Creates the mirror's pyproject.toml
    #
    # note: this selectively copies the parts of the API's pyproject.toml that describe the software
    #   (its description, authors, urls, ...) instead of copying the file. The API is a C++/Cython/
    #   python project and the mirror is a pure python one, so most of the API's .toml does not apply
    def buildMirrorConfig(self):
        apiConfig = ProjectPathTools.getPythonTomlConfigPath(self._apiProjectFolder)
        mirrorConfig = ProjectPathTools.getPythonTomlConfigPath(self._mirrorProjectFolder)

        print(f"Creating pyproject.toml")

        apiToml = TomlFile(apiConfig)
        apiToml.read()

        mirrorToml = TomlFile(mirrorConfig)
        if (os.path.isfile(mirrorConfig)):
            mirrorToml.read()

        for section in mirrorToml.sections:
            if (section not in MirrorSections):
                print(f"  dropping the '{section}' section, which is not part of a pure python package")

        buildSystem = self.getMirrorBuildSystem(apiToml, mirrorToml)
        project = self.getMirrorProject(apiToml)

        projectUrls = self.getSectionKeyLines(apiToml, ProjectUrlsSection)

        mirrorToml.preamble = []
        mirrorToml.sections.clear()
        mirrorToml.setSection(BuildSystemSection, buildSystem + [""])
        mirrorToml.setSection(ProjectSection, project + [""])
        mirrorToml.setSection(ProjectUrlsSection, projectUrls + [""])

        mirrorToml.write()

        # 'name', 'version' and the dependency onto the API are the mirror's own metadata
        configUpdater = TomlUpdater(mirrorConfig, self._apiMirrorStats, dependencies = [("==", self._apiStats)])
        configUpdater.update()
    
    def build(self):
        self.buildMirrorInit()
        self.buildMirrorMain()

        # copy the license and README
        apiReadMePath = ProjectPathTools.getReadMePath(self._apiProjectFolder)
        apiLicensePath = ProjectPathTools.getLicensePath(self._apiProjectFolder)
        mirrorReadMePath = ProjectPathTools.getReadMePath(self._mirrorProjectFolder)
        mirrorLicensePath = ProjectPathTools.getLicensePath(self._mirrorProjectFolder)

        print(f"Copying README")
        shutil.copy2(apiReadMePath, mirrorReadMePath)

        print(f"Copying LICENSE")
        shutil.copy2(apiLicensePath, mirrorLicensePath)

        self.buildMirrorConfig()
