"""
Regenerates api/src/cpp/py/src/constants/PyConstantStrings.cpp -- the bindings of the core's
string-constant classes (IniKeywords, FileExt, FilePrefixes, FileTypes, IniGraphModObjKeywords) --
from the core headers, docstrings included, so the Python docs say what the C++ docs say.

    python genConstantStrings.py            writes the .cpp
    python genConstantStrings.py --check    exits 1 if the .cpp is not what the headers give

Run it after adding, removing or re-documenting a member of one of those classes, then rebuild. Every
`static inline const` member that has a doc comment is bound read-only, under its C++ name; one with
no doc comment is skipped, so document the member. A new class goes in CLASSES (and its header in
HEAD's include list).
"""

import os, re, sys

REPO = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."))
CPP = os.path.join(REPO, "Anime Game Remap (for all users)", "api", "src", "cpp")
INC = os.path.join(CPP, "core", "include", "AGRemapCore", "constants")
OUT = os.path.join(CPP, "py", "src", "constants", "PyConstantStrings.cpp")

CLASSES = ["FileExt", "FilePrefixes", "FileTypes", "IniGraphModObjKeywords", "IniKeywords"]

# Doxygen/Breathe roles -> the Sphinx Python roles the bound docstrings render with
ROLES = [(":cpp:class:", ":class:"), (":cpp:func:", ":meth:"), (":cpp:enum:", ":class:"),
         (":cpp:enumerator:", ":attr:"), (":cpp:member:", ":attr:"), (":cpp:type:", ":class:")]


def toPyDoc(lines):
    """A /** ... */ block as a Python docstring: markers dropped, common indent removed, roles converted"""
    body = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("/**") or stripped.startswith("*/") or stripped in ("@rst", "@endrst", "* @brief"):
            continue
        line = re.sub(r"^\s*\* ?@brief ?", "", line.rstrip())
        if line.strip().startswith("*"):
            line = re.sub(r"^\s*\* ?", "", line)
        body.append(line)

    nonEmpty = [line for line in body if line.strip()]
    indent = min((len(line) - len(line.lstrip()) for line in nonEmpty), default = 0)
    text = "\n".join(line[indent:] if len(line) >= indent else line.strip() for line in body).strip("\n")

    for old, new in ROLES:
        text = text.replace(old, new)
    text = re.sub(r"\\ref (\w+)", r":attr:`\1`", text)
    text = re.sub(r"#(\w+)", r":attr:`\1`", text)
    text = text.replace("AGRemapCore::", "")
    while True:
        new = re.sub(r"(:(?:class|meth|attr):`[^`]*?)::", r"\1.", text)
        if new == text:
            break
        text = new

    assert ')doc"' not in text, "a docstring would close the raw string early"
    return text


def parse(cls):
    with open(os.path.join(INC, cls + ".h"), encoding = "utf-8") as f:
        txt = f.read().replace("\r\n", "\n")

    m = re.search(r"(/\*\*(?:(?!\*/).)*\*/)\s*class " + cls + r"\b", txt, re.S)
    classDoc = toPyDoc(m.group(1).split("\n"))
    members = [(mm.group(3), toPyDoc(mm.group(1).split("\n")))
               for mm in re.finditer(r"(/\*\*(?:(?!\*/).)*\*/)\s*static inline const ([\w:<>]+) (\w+)\s*=", txt[m.end():], re.S)]
    return classDoc, members


HEAD = """// ##### Credits

// ===== Anime Game Remap (AG Remap) =====
// Authors: Albert Gold#2696, NK#1321
//
// if you used it to remap your mods pls give credit for "Albert Gold#2696" and "Nhok0169"
// Special Thanks:
//   nguen#2011 (for support)
//   SilentNightSound#7430 (for internal knowdege so wrote the blendCorrection code)
//   HazrateGolabi#1364 (for being awesome, and improving the code)

// ##### EndCredits

// GENERATED by Tools/Misc/Docs/genConstantStrings.py from the core headers' doc comments; regenerate
// rather than hand-edit a docstring, so the two stay in step.

#include "PyConstantStrings.h"

#include <pybind11/stl.h>

#include "AGRemapCore/constants/FileExt.h"
#include "AGRemapCore/constants/FilePrefixes.h"
#include "AGRemapCore/constants/FileTypes.h"
#include "AGRemapCore/constants/IniGraphModObjKeywords.h"
#include "AGRemapCore/constants/IniKeywords.h"

namespace py = pybind11;
namespace AGRC = AGRemapCore;


void initCppConstantStrings(pybind11::module_ &m) {
    // Each class is a namespace of plain strings on both sides: `IniKeywords.Hash` is "hash" itself,
    // with no '.value' to read through, and is read-only from Python.
"""


def generate():
    parts = [HEAD]
    for i, cls in enumerate(CLASSES):
        classDoc, members = parse(cls)
        parts.append(f'    py::class_<AGRC::{cls}>(m, "{cls}", R"doc(\n{classDoc}\n    )doc")')
        for name, doc in members:
            parts.append(f'\n        .def_readonly_static("{name}", &AGRC::{cls}::{name}, py::doc(R"doc(\n{doc}\n        )doc"))')
        parts.append(";\n" if i == len(CLASSES) - 1 else ";\n\n")
    parts.append("}\n")
    return "".join(parts)


if __name__ == "__main__":
    src = generate()
    if "--check" in sys.argv:
        with open(OUT, encoding = "utf-8", newline = "") as f:
            current = f.read().replace("\r\n", "\n")
        print("up to date" if current == src else "OUT OF DATE: run without --check")
        sys.exit(0 if current == src else 1)

    with open(OUT, "w", encoding = "utf-8", newline = "\n") as f:
        f.write(src)
    print("wrote", OUT, {cls: len(parse(cls)[1]) for cls in CLASSES})
