#ifndef AGRemapCore_ShapeKeyChecksumData_H
#define AGRemapCore_ShapeKeyChecksumData_H

// ##### Credits

// ===== Anime Game Remap (AG Remap) =====
// Authors: Albert Gold#2696, NK#1321
//
// if you used it to remap your mods pls give credit for "Albert Gold#2696" and "Nhok0169"
// Special Thanks:
//   nguen#2011 (for support)
//   SilentNightSound#7430 (for internal knowdege so wrote the blendCorrection code)
//   HazrateGolabi#1364 (for being awesome, and improving the code)

// ##### EndCredits

#include <string>
#include <utility>
#include <vector>


namespace AGRemapCore {
    namespace Data {
        /**
         * @brief
         @rst
         The data table backing :cpp:class:`ShapeKeyChecksums`: the shape-key ``checksum`` of a WWMI character -- the sum of the first four shape-key offsets of the game's own mesh, which a mod's ``$\\WWMIv1\\shapekey_checksum`` must equal for WWMI's ShapeKeyOverrider to accept the mod's shape keys as this character's (the ``type`` column is ``shapekeys``) :raw-html:`<br />` :raw-html:`<br />`

         Rows are ``({version, name, component, type}, value)``, the shape
         :cpp:func:`getIndexDataRows` has, and the value is kept as a string for the same reason
         an index is -- it is what a ``.ini`` line carries and what a fixer replaces :raw-html:`<br />`
         :raw-html:`<br />`

         .. danger::
            Generated by script from the characters' ``Metadata.json`` in WWMI-Assets'
            ``PlayerCharacterData`` (never hand-transcribed); a new character's rows are added by
            editing the literal in the ``.cpp``, with ``ModTypeIdTools::getName`` for the name so a
            registry rename cannot desync it
         @endrst
         */
        const std::vector<std::pair<std::vector<std::string>, std::string>>& getShapeKeyChecksumDataRows();
    }
}

#endif
