// ##### Credits

// ===== Anime Game Remap (AG Remap) =====
// Authors: Albert Gold#2696, NK#1321
//
// if you used it to remap your mods pls give credit for "Albert Gold#2696" and "Nhok0169"
// Special Thanks:
//   nguen#2011 (for support)
//   SilentNightSound#7430 (for internal knowdege so wrote the blendCorrection code)
//   HazrateGolabi#1364 (for being awesome, and improving the code)

// ##### EndCredits


#ifndef WWMI_TEXTURE_INDEX_H
#define WWMI_TEXTURE_INDEX_H

#include <algorithm>
#include <cstdint>
#include <functional>
#include <map>
#include <optional>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "AGRemapCore/constants/FileExt.h"
#include "AGRemapCore/constants/IniKeywords.h"
#include "AGRemapCore/model/assets/Hashes.h"
#include "AGRemapCore/model/textures/TexThumbprint.h"
#include "AGRemapCore/model/files/IniScan.h"
#include "AGRemapCore/model/IniNamingTools.h"
#include "AGRemapCore/tools/files/FileService.h"
#include "AGRemapCore/tools/StringTools.h"


namespace AGRemapCore {

    /**
     * @brief
     @rst
     What a WuWa character's own textures look like, so a mod's files can be sorted into ROLES
     :raw-html:`<br />` :raw-html:`<br />`

     Every field here describes the SOURCE -- the character whose mod is being read -- and none of
     them says anything about the target, the plan or the fix. That is why this is a thing of its
     own rather than part of :cpp:struct:`WWMIFixerConfig`: sorting a mod's files into roles is
     CLASSIFICATION, which is the parser's job, and the fixer only needs the answer
     @endrst
     */
    struct WWMITextureFacts {
        /**
         * @brief The character's own texture hashes, as ``hash -> role``
         */
        std::unordered_map<std::string, std::string> roles;

        /**
         * @brief
         @rst
         Roles by WWMI Tools' ``Component<N>_<Type>`` naming, as ``component -> {type -> role}``,
         for a file no hash names
         @endrst
         */
        std::map<int, std::unordered_map<std::string, std::string>> typeRoles;

        /**
         * @brief
         @rst
         A 16 x 16 grayscale box average of each of the character's game textures, keyed by hash --
         pixel identity for a file no hash and no name places :raw-html:`<br />` :raw-html:`<br />`

         Generated by ``Tools/Misc/Diagnostics/wwmiTextureThumbs.py``
         @endrst
         */
        std::unordered_map<std::string, std::vector<std::uint8_t>> textureThumbprints;

        /**
         * @brief The thumbprint's side, in pixels
         */
        int thumbprintSize = 16;

        /**
         * @brief How alike a file and a thumbprint must be before the file IS that texture
         */
        double identityMin = 0.97;

        /**
         * @brief How far the runner-up must fall behind before the winner is believed
         */
        double identityGap = 0.90;

        /**
         * @brief
         @rst
         Identifies a texture file by hand, in place of the thumbprints -- for a test, or a
         character whose thumbprints are not generated yet
         @endrst
         */
        std::function<std::optional<std::string>(const std::string& file)> identifyTexture;
    };



    const std::unordered_map<std::string, std::string> TypeOfSuffix = {
        {"diffuse", "diffuse"}, {"albedo", "diffuse"}, {"base", "diffuse"}, {"color", "diffuse"}, {"colour", "diffuse"}, {"d", "diffuse"},
        {"lm", "mask"}, {"lightmap", "mask"}, {"mask", "mask"}, {"m", "mask"},
        {"nm", "normal"}, {"normal", "normal"}, {"normalmap", "normal"}, {"n", "normal"}};

    // ---- the mod's textures, by role ----

    struct TextureRole {
        std::string role;
        std::string how;
    };

    /**
     * Every .dds under the mod's root with the roles it plays, and every .ini's resource
     * sections -> files. A file plays EVERY role its hashes name: a mod declares one file
     * under two hashes when one atlas serves two components (Upper_D.dds as both the arm
     * skin's and the bodice's diffuse), and taking only the first left the second component
     * unbound, drawing with the TARGET's own textures (2026-09-19). The root is the .ini file's own folder, climbed while the parent
     * holds a .ini file of its own (LOD folders under a file that declares their textures).
     */
    class WWMITextureIndex {
        public:
            WWMITextureIndex(const std::string& iniFolder, const WWMITextureFacts& facts, const std::string& remapTexKeyword,
                         const Hashes* libraryHashes, const std::string& sourceName);

            const std::string& root() const { return root_; }
            std::size_t fileCount() const { return real_.size(); }
            std::size_t byHash() const { return byHash_; }
            std::size_t byPixels() const { return byPixels_; }
            std::size_t byName() const { return byName_; }
            const std::vector<std::string>& unresolved() const { return unresolved_; }
            const std::unordered_map<std::string, std::vector<TextureRole>>& rolesOf() const { return rolesOf_; }

            // The file's real spelling, for what gets written into the .ini.
            std::string real(const std::string& key) const;

            // (resource section, file key) in the .ini's own declaration order: the FIRST resource
            // naming a file is the one bound, as the prototype binds it
            const std::vector<std::pair<std::string, std::string>>& resourcesOf(const std::string& iniPath) const;

        private:
            static std::string findRoot(const std::string& iniFolder);

            // A DISABLED-prefixed folder or file, anywhere under the root: the game ignores it.
            bool isDisabled(const std::string& file) const;

            std::string root_;
            std::unordered_map<std::string, std::string> real_;
            std::unordered_map<std::string, std::vector<std::pair<std::string, std::string>>> resourcesByIni_;
            std::unordered_map<std::string, std::vector<TextureRole>> rolesOf_;
            std::vector<std::string> unresolved_;
            std::size_t byHash_ = 0;
            std::size_t byPixels_ = 0;
            std::size_t byName_ = 0;
    };
}

#endif
