// ##### Credits

// ===== Anime Game Remap (AG Remap) =====
// Authors: Albert Gold#2696, NK#1321
//
// if you used it to remap your mods pls give credit for "Albert Gold#2696" and "Nhok0169"
// Special Thanks:
//   nguen#2011 (for support)
//   SilentNightSound#7430 (for internal knowdege so wrote the blendCorrection code)
//   HazrateGolabi#1364 (for being awesome, and improving the code)

// ##### EndCredits


#ifndef WWMI_TEXTURE_INDEX_H
#define WWMI_TEXTURE_INDEX_H

#include <algorithm>
#include <cstdint>
#include <functional>
#include <map>
#include <optional>
#include <regex>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "AGRemapCore/constants/IniKeywords.h"
#include "AGRemapCore/model/assets/Hashes.h"
#include "AGRemapCore/model/textures/TexThumbprint.h"
#include "AGRemapCore/model/files/IniScan.h"
#include "AGRemapCore/model/IniNamingTools.h"
#include "AGRemapCore/tools/files/FileService.h"
#include "AGRemapCore/tools/StringTools.h"


namespace AGRemapCore {

    /**
     * @brief
     @rst
     What a WuWa character's own textures look like, so a mod's files can be sorted into ROLES
     :raw-html:`<br />` :raw-html:`<br />`

     Every field here describes the SOURCE -- the character whose mod is being read -- and none of
     them says anything about the target, the plan or the fix. That is why this is a thing of its
     own rather than part of :cpp:struct:`WWMIFixerConfig`: sorting a mod's files into roles is
     CLASSIFICATION, which is the parser's job, and the fixer only needs the answer
     @endrst
     */
    struct WWMITextureFacts {
        /**
         * @brief The character's own texture hashes, as ``hash -> role``
         */
        std::unordered_map<std::string, std::string> roles;

        /**
         * @brief
         @rst
         Roles by WWMI Tools' ``Component<N>_<Type>`` naming, as ``component -> {type -> role}``,
         for a file no hash names
         @endrst
         */
        std::map<int, std::unordered_map<std::string, std::string>> typeRoles;

        /**
         * @brief
         @rst
         A 16 x 16 grayscale box average of each of the character's game textures, keyed by hash --
         pixel identity for a file no hash and no name places :raw-html:`<br />` :raw-html:`<br />`

         Generated by ``Tools/Misc/Diagnostics/wwmiTextureThumbs.py``
         @endrst
         */
        std::unordered_map<std::string, std::vector<std::uint8_t>> textureThumbprints;

        /**
         * @brief The thumbprint's side, in pixels
         */
        int thumbprintSize = 16;

        /**
         * @brief How alike a file and a thumbprint must be before the file IS that texture
         */
        double identityMin = 0.97;

        /**
         * @brief How far the runner-up must fall behind before the winner is believed
         */
        double identityGap = 0.90;

        /**
         * @brief
         @rst
         Identifies a texture file by hand, in place of the thumbprints -- for a test, or a
         character whose thumbprints are not generated yet
         @endrst
         */
        std::function<std::optional<std::string>(const std::string& file)> identifyTexture;
    };

    // The file-name and section-name vocabulary the index reads. Moved here with the class that
    // uses them rather than left behind in the fixer for it to reach back into.
    inline const std::string DdsExt = ".dds";
    inline const std::string IniExt = ".ini";
    inline const std::string ResourcePrefix = "Resource";
    inline const std::string TextureOverrideTexturePrefix = "TextureOverrideTexture";
    inline const std::string ThisKey = "this";

    // WWMI Tools' own export names: "... t=<hash>.dds" and "Component<N>_<Type>.dds".
    inline const std::regex FileHashPattern(R"(t=([0-9a-fA-F]{8})\.dds$)", std::regex::icase);
    inline const std::regex ComponentFilePattern(R"(component[\s_-]*(\d+)[\s_-]+([a-z]+)\.dds$)", std::regex::icase);

    // How far above the .ini file its textures may live -- a mod with LOD folders declares them in
    // a parent.
    inline const int MaxFolderClimb = 3;

    const std::unordered_map<std::string, std::string> TypeOfSuffix = {
        {"diffuse", "diffuse"}, {"albedo", "diffuse"}, {"base", "diffuse"}, {"color", "diffuse"}, {"colour", "diffuse"}, {"d", "diffuse"},
        {"lm", "mask"}, {"lightmap", "mask"}, {"mask", "mask"}, {"m", "mask"},
        {"nm", "normal"}, {"normal", "normal"}, {"normalmap", "normal"}, {"n", "normal"}};

    // ---- the mod's textures, by role ----

    struct TextureRole {
        std::string role;
        std::string how;
    };

    /**
     * Every .dds under the mod's root with the roles it plays, and every .ini's resource
     * sections -> files. A file plays EVERY role its hashes name: a mod declares one file
     * under two hashes when one atlas serves two components (Upper_D.dds as both the arm
     * skin's and the bodice's diffuse), and taking only the first left the second component
     * unbound, drawing with the TARGET's own textures (2026-09-19). The root is the .ini file's own folder, climbed while the parent
     * holds a .ini file of its own (LOD folders under a file that declares their textures).
     */
    class WWMITextureIndex {
        public:
            WWMITextureIndex(const std::string& iniFolder, const WWMITextureFacts& facts, const std::string& remapTexKeyword,
                         const Hashes* libraryHashes, const std::string& sourceName) {
                root_ = findRoot(iniFolder);

                // The roles this config knows what to do with -- the gate on the library
                // lookup below, so a `vb0` or `cb4` row can never be read as a texture role.
                std::unordered_set<std::string> knownRoles;
                for (const auto& entry : facts.roles) {
                    knownRoles.insert(entry.second);
                }

                // A ROLE IS ASKED OF THE LIBRARY FIRST. `facts.roles` is written from one
                // generation of the character's textures and a mod carries whatever hash its
                // author dumped, so a mod a version or two old matched almost nothing and
                // downloaded the GAME's texture for role after role -- someone's painted outfit
                // rendering as the vanilla one, with "downloaded 13 files" in the summary.
                // HashData files them typed by role at every generation.
                //
                // One call, no version: ModMappedAssets keys its buckets by the ASSET, so a
                // hash's buckets are its own generations and a hash that only ever existed at
                // 3.0 has exactly one.
                auto roleOfHash = [&facts, &knownRoles, libraryHashes, &sourceName]
                                  (const std::string& hash) -> std::optional<TextureRole> {
                    if (libraryHashes != nullptr && !sourceName.empty()) {
                        std::optional<std::vector<std::string>> key =
                            libraryHashes->getKey(hash, std::nullopt, {sourceName, std::nullopt}, false);
                        if (key.has_value() && key->size() > 1 && knownRoles.count((*key)[1]) > 0) {
                            return TextureRole{(*key)[1], "hash " + hash + " (the library's history)"};
                        }
                    }

                    auto role = facts.roles.find(hash);
                    if (role != facts.roles.end()) {
                        return TextureRole{role->second, "hash " + hash};
                    }

                    return std::nullopt;
                };

                std::unordered_map<std::string, std::vector<std::string>> hashesOfFile;
                std::vector<std::string> ddsFiles;
                const std::string remapTex = StringTools::toLower(remapTexKeyword);
                const std::string remapFix = StringTools::toLower(IniKeywords::RemapFix);
                for (const std::string& file : FileService::getFilesAndDirs(root_, true).first) {
                    if (isDisabled(file)) {
                        continue;
                    }

                    const std::string name = StringTools::toLower(FileService::baseName(file));
                    if (StringTools::endsWith(name, DdsExt)) {
                        if (name.find(remapTex) == std::string::npos) {
                            const std::string key = FileService::pathKey(file);
                            ddsFiles.push_back(key);
                            real_[key] = file;
                        }

                        continue;
                    }

                    if (!StringTools::endsWith(name, IniExt) || name.find(remapFix) != std::string::npos) {
                        continue;
                    }

                    const std::string folder = FileService::parentOf(file);
                    std::vector<std::pair<std::string, std::string>> resources;     // in declaration order
                    std::unordered_map<std::string, std::string> fileOfResource;
                    const std::vector<IniScanSection> sections = IniScan::scan(file);
                    for (const IniScanSection& section : sections) {
                        if (!StringTools::startsWith(section.name, ResourcePrefix)
                            || StringTools::toLower(section.name).find(remapFix) != std::string::npos) {
                            continue;
                        }

                        std::optional<std::string> fileName = IniScan::firstVal(section, IniKeywords::Filename);
                        if (fileName.has_value() && StringTools::endsWith(StringTools::toLower(*fileName), DdsExt)) {
                            const std::string key = FileService::pathKey(FileService::absPathOfRelPath(*fileName, folder));
                            resources.emplace_back(section.name, key);
                            fileOfResource[section.name] = key;
                        }
                    }

                    for (const IniScanSection& section : sections) {
                        if (!StringTools::startsWith(section.name, TextureOverrideTexturePrefix)) {
                            continue;
                        }

                        std::optional<std::string> hash = IniScan::firstVal(section, IniKeywords::Hash);
                        std::optional<std::string> resource = IniScan::firstVal(section, ThisKey);
                        if (hash.has_value() && resource.has_value() && fileOfResource.count(*resource) > 0) {
                            hashesOfFile[fileOfResource[*resource]].push_back(StringTools::toLower(*hash));
                        }
                    }

                    resourcesByIni_[FileService::pathKey(file)] = std::move(resources);
                }

                std::vector<std::string> pending;
                for (const std::string& file : ddsFiles) {
                    std::vector<std::string> hashes = hashesOfFile[file];
                    std::smatch match;
                    if (std::regex_search(file, match, FileHashPattern)) {
                        hashes.push_back(StringTools::toLower(match[1].str()));
                    }

                    std::vector<TextureRole> roles;
                    for (const std::string& hash : hashes) {
                        std::optional<TextureRole> role = roleOfHash(hash);
                        if (!role.has_value()) {
                            continue;
                        }

                        const bool known = std::any_of(roles.begin(), roles.end(),
                                                       [&](const TextureRole& r) { return r.role == role->role; });
                        if (!known) {
                            roles.push_back(*role);
                        }
                    }

                    if (!roles.empty()) {
                        rolesOf_[file] = std::move(roles);
                        ++byHash_;
                    } else {
                        pending.push_back(file);
                    }
                }

                for (const std::string& file : pending) {
                    std::optional<std::string> hash;
                    if (facts.identifyTexture) {
                        hash = facts.identifyTexture(real_[file]);
                    }

                    if (!hash.has_value()) {
                        hash = TexThumbprint::identifyFile(real_[file], facts.textureThumbprints, facts.thumbprintSize,
                                                  facts.identityMin, facts.identityGap);
                    }

                    if (hash.has_value()) {
                        std::optional<TextureRole> role = roleOfHash(StringTools::toLower(*hash));
                        if (role.has_value()) {
                            rolesOf_[file] = {TextureRole{role->role, "the game's own " + *hash + " by its pixels"}};
                            ++byPixels_;
                            continue;
                        }
                    }

                    std::smatch match;
                    const std::string name = FileService::baseName(file);
                    if (std::regex_search(name, match, ComponentFilePattern)) {
                        const int component = std::stoi(match[1].str());
                        auto type = TypeOfSuffix.find(StringTools::toLower(match[2].str()));
                        auto typeRoles = facts.typeRoles.find(component);
                        if (type != TypeOfSuffix.end() && typeRoles != facts.typeRoles.end()) {
                            auto role = typeRoles->second.find(type->second);
                            if (role != typeRoles->second.end()) {
                                rolesOf_[file] = {TextureRole{role->second, "its name"}};
                                ++byName_;
                                continue;
                            }
                        }
                    }

                    unresolved_.push_back(file);
                }
            }

            const std::string& root() const { return root_; }
            std::size_t fileCount() const { return real_.size(); }
            std::size_t byHash() const { return byHash_; }
            std::size_t byPixels() const { return byPixels_; }
            std::size_t byName() const { return byName_; }
            const std::vector<std::string>& unresolved() const { return unresolved_; }
            const std::unordered_map<std::string, std::vector<TextureRole>>& rolesOf() const { return rolesOf_; }

            // The file's real spelling, for what gets written into the .ini.
            std::string real(const std::string& key) const {
                auto it = real_.find(key);
                return it == real_.end() ? key : it->second;
            }

            // (resource section, file key) in the .ini's own declaration order: the FIRST resource
            // naming a file is the one bound, as the prototype binds it
            const std::vector<std::pair<std::string, std::string>>& resourcesOf(const std::string& iniPath) const {
                static const std::vector<std::pair<std::string, std::string>> none;
                auto it = resourcesByIni_.find(FileService::pathKey(iniPath));
                return it == resourcesByIni_.end() ? none : it->second;
            }

        private:
            static std::string findRoot(const std::string& iniFolder) {
                std::string folder = iniFolder;
                for (int i = 0; i < MaxFolderClimb; ++i) {
                    const std::string parent = FileService::parentOf(folder);
                    if (parent.empty() || parent == folder) {
                        break;
                    }

                    bool holdsIni = false;
                    for (const std::string& file : FileService::getFilesAndDirs(parent, false).first) {
                        const std::string name = FileService::baseName(file);
                        if (StringTools::endsWith(StringTools::toLower(name), IniExt) && !IniNamingTools::isDisabled(name)) {
                            holdsIni = true;
                            break;
                        }
                    }

                    if (!holdsIni) {
                        break;
                    }

                    folder = parent;
                }

                return folder;
            }

            // A DISABLED-prefixed folder or file, anywhere under the root: the game ignores it.
            bool isDisabled(const std::string& file) const {
                const std::string rel = FileService::pathKey(FileService::getRelPath(file, root_));
                std::size_t start = 0;
                while (start <= rel.size()) {
                    const std::size_t end = rel.find('/', start);
                    const std::string part = rel.substr(start, end == std::string::npos ? std::string::npos : end - start);
                    if (IniNamingTools::isDisabled(part)) {
                        return true;
                    }

                    if (end == std::string::npos) {
                        break;
                    }

                    start = end + 1;
                }

                return false;
            }

            std::string root_;
            std::unordered_map<std::string, std::string> real_;
            std::unordered_map<std::string, std::vector<std::pair<std::string, std::string>>> resourcesByIni_;
            std::unordered_map<std::string, std::vector<TextureRole>> rolesOf_;
            std::vector<std::string> unresolved_;
            std::size_t byHash_ = 0;
            std::size_t byPixels_ = 0;
            std::size_t byName_ = 0;
    };
}

#endif
