// ##### Credits

// ===== Anime Game Remap (AG Remap) =====
// Authors: Albert Gold#2696, NK#1321
//
// if you used it to remap your mods pls give credit for "Albert Gold#2696" and "Nhok0169"
// Special Thanks:
//   nguen#2011 (for support)
//   SilentNightSound#7430 (for internal knowdege so wrote the blendCorrection code)
//   HazrateGolabi#1364 (for being awesome, and improving the code)

// ##### EndCredits


#ifndef WWMI_TEXTURE_FACTS_H
#define WWMI_TEXTURE_FACTS_H

#include <algorithm>
#include <cstdint>
#include <functional>
#include <map>
#include <optional>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "AGRemapCore/constants/FileExt.h"
#include "AGRemapCore/constants/IniKeywords.h"
#include "AGRemapCore/model/assets/Hashes.h"
#include "AGRemapCore/model/textures/TexThumbprint.h"
#include "AGRemapCore/model/files/IniScan.h"
#include "AGRemapCore/model/IniNamingTools.h"
#include "AGRemapCore/tools/files/FileService.h"
#include "AGRemapCore/tools/StringTools.h"


namespace AGRemapCore {

    /**
     * @brief
     @rst
     What a WuWa character's own textures look like, so a mod's files can be sorted into ROLES
     :raw-html:`<br />` :raw-html:`<br />`

     Every field here describes the SOURCE -- the character whose mod is being read -- and none of
     them says anything about the target, the plan or the fix. That is why this is a thing of its
     own rather than part of :cpp:struct:`WWMIFixerConfig`: sorting a mod's files into roles is
     CLASSIFICATION, which is the parser's job, and the fixer only needs the answer
     @endrst
     */
    struct WWMITextureFacts {
        /**
         * @brief The character's own texture hashes, as ``hash -> role``
         */
        std::unordered_map<std::string, std::string> roles;

        /**
         * @brief
         @rst
         Roles by WWMI Tools' ``Component<N>_<Type>`` naming, as ``component -> {type -> role}``,
         for a file no hash names
         @endrst
         */
        std::map<int, std::unordered_map<std::string, std::string>> typeRoles;

        /**
         * @brief
         @rst
         A 16 x 16 grayscale box average of each of the character's game textures, keyed by hash --
         pixel identity for a file no hash and no name places :raw-html:`<br />` :raw-html:`<br />`

         Generated by ``Tools/Misc/Diagnostics/wwmiTextureThumbs.py``
         @endrst
         */
        std::unordered_map<std::string, std::vector<std::uint8_t>> textureThumbprints;

        /**
         * @brief The thumbprint's side, in pixels
         */
        int thumbprintSize = 16;

        /**
         * @brief How alike a file and a thumbprint must be before the file IS that texture
         */
        double identityMin = 0.97;

        /**
         * @brief How far the runner-up must fall behind before the winner is believed
         */
        double identityGap = 0.90;

        /**
         * @brief
         @rst
         Identifies a texture file by hand, in place of the thumbprints -- for a test, or a
         character whose thumbprints are not generated yet
         @endrst
         */
        std::function<std::optional<std::string>(const std::string& file)> identifyTexture;

        /**
         * @brief
         @rst
         Which role each register binds, per source component, as ``component -> {register -> role}``
         :raw-html:`<br />` :raw-html:`<br />`

         The other way a texture is identified: the `section`_ carries the MESH's hash, so
         :cpp:class:`GIMISectionClassifier` places it on a component, and the register says what the
         file it binds is. The usual GI form; rare in WuWa -- 31 files against 609 over this
         corpus -- and kept because a future mod could be written that way
         @endrst
         */
        std::map<int, std::map<std::string, std::string>> registerRoles;

        /**
         * @brief
         @rst
         The game folder under ``Data/Mod Downloads`` this character's textures are fetched from.
         **Default**: ``"WuWa"``
         @endrst
         */
        std::string downloadGameFolder = "WuWa";

        /**
         * @brief
         @rst
         This character's download folder, version folder and file prefix under
         :cpp:member:`downloadGameFolder` -- ``Sanhua`` / ``2_5`` / ``Sanhua`` for
         ``WuWa/Sanhua/2_5/SanhuaTexture<hash>.dds``. Empty (the default) registers no fallback
         download at all :raw-html:`<br />` :raw-html:`<br />`

         Beside the roles rather than on the fixer's config for the reason
         :cpp:member:`GIMICharParserConfig::downloadCharFolder` is: they describe the character a
         mod was made FOR, so a second target for the same source would otherwise repeat them
         @endrst
         */
        std::string downloadCharFolder;
        std::string downloadVersionFolder;
        std::string downloadPrefix;

        /**
         * @brief
         @rst
         Role -> this character's texture hash of that role, for a planned role the mod has NO file
         for: the register is bound to the character's own game texture, downloaded as
         ``<downloadPrefix><Role>RemapDL.dds`` into the mod's texture folder :raw-html:`<br />`
         :raw-html:`<br />`

         The mod's UVs are the source's, so what an unbound register samples on the target's draw
         -- the TARGET's texture -- is wrong by construction: the red-camellia mod ships no bodice
         or skirt mask, and the Exorcist's mask at its UVs put skin codes over cloth, a reddish hue
         over the whole body while every diffuse was right (2026-09-19). The same reasoning as the
         GI templates' texture donor. A role whose hash BOTH skins bind needs no entry: the target's
         texture is the source's. Empty (the default) binds nothing for a missing role
         :raw-html:`<br />` :raw-html:`<br />`

         .. note::
            Which GENERATION of a role's hash to name here is the one thing this table says that
            #roles does not, so it is not that table inverted. ``Data/Mod Downloads`` was built
            from one frame dump, and for ChisaParfait that is not the generation
            :cpp:class:`HashData` files at 3.5 -- eight of her roles would name a hash with no file
            behind it if this were derived by taking the newest (measured 2026-09-30). Name the
            hash the download folder actually holds
         @endrst
         */
        std::map<std::string, std::string> fallbackTextures;
    };

}

#endif
