import sys

from .baseUnitTest import BaseUnitTest
from ..src.Config import Configs
from ..src.constants.ConfigKeys import ConfigKeys

sys.path.insert(1, Configs[ConfigKeys.SysPath])
import src.py.FixRaidenBoss2 as FRB


class IfPredParserTest(BaseUnitTest):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()

        cls._tokenizer = FRB.IfPredTokenizer()
        cls._tokenizer.setup()

    def setUp(self):
        super().setUp()

        # A fresh parser per test (rather than one shared, mutable class-level instance) --
        # setup() regenerates the DFA with fresh random state/item/node ids each time (see
        # compareParseTreeShape's own note on why those can no longer be deterministically mocked
        # the way the pure-Python original's tests did), so there's no determinism left to share
        # across tests anyway; a fresh instance also keeps tests independent of each other.
        self._parser = FRB.IfPredParser()

    # ================== parse =======================

    def test_differentIfPreds_ifPredsParsed(self):
        file = "MyFile.agr"
        startLineNo = 8

        tests = [
                    [" ", 
                     FRB.ParseTree({
                         1: FRB.ParseNode(1, token=FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                         2: FRB.ParseNode(2, token=FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                         3: FRB.ParseNode(3, prodId="start empty"),
                     },
                     {3: [1, 2]},
                     3)],

                    ["$swapvar == 5", 
                     FRB.ParseTree({
                        1: FRB.ParseNode(1, token = FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                        2: FRB.ParseNode(2, token = FRB.Token('ID', '$swapvar', 8, 1)),
                        3: FRB.ParseNode(3, prodId = 'variable'),
                        4: FRB.ParseNode(4, prodId = 'nterm reduce'),
                        5: FRB.ParseNode(5, prodId = 'multexpr reduce'),
                        6: FRB.ParseNode(6, prodId = 'addexpr reduce'),
                        7: FRB.ParseNode(7, prodId = 'keyexpr reduce'),
                        8: FRB.ParseNode(8, token = FRB.Token('EQ', '==', 8, 10)),
                        9: FRB.ParseNode(9, token = FRB.Token('INT', '5', 8, 13)),
                        10: FRB.ParseNode(10, prodId = 'int'),
                        11: FRB.ParseNode(11, prodId = 'nterm reduce'),
                        12: FRB.ParseNode(12, prodId = 'multexpr reduce'),
                        13: FRB.ParseNode(13, prodId = 'addexpr reduce'),
                        14: FRB.ParseNode(14, prodId = 'keyexpr reduce'),
                        15: FRB.ParseNode(15, prodId = 'eq'),
                        16: FRB.ParseNode(16, prodId = 'pred reduce'),
                        17: FRB.ParseNode(17, token = FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                        18: FRB.ParseNode(18, prodId = 'start'),
                    },
                    {3: [2], 4: [3], 5: [4], 6: [5], 7: [6], 10: [9], 11: [10], 12: [11], 13: [12], 14: [13], 15: [7, 8, 14], 16: [15], 18: [1, 16, 17]},
                    18)],

                    ['$x >= 5', 
                     FRB.ParseTree({
                        1: FRB.ParseNode(1, token = FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                        2: FRB.ParseNode(2, token = FRB.Token('ID', '$x', 8, 1)),
                        3: FRB.ParseNode(3, prodId = 'variable'),
                        4: FRB.ParseNode(4, prodId = 'nterm reduce'),
                        5: FRB.ParseNode(5, prodId = 'multexpr reduce'),
                        6: FRB.ParseNode(6, prodId = 'addexpr reduce'),
                        7: FRB.ParseNode(7, prodId = 'keyexpr reduce'),
                        8: FRB.ParseNode(8, token = FRB.Token('GE', '>=', 8, 4)),
                        9: FRB.ParseNode(9, token = FRB.Token('INT', '5', 8, 7)),
                        10: FRB.ParseNode(10, prodId = 'int'),
                        11: FRB.ParseNode(11, prodId = 'nterm reduce'),
                        12: FRB.ParseNode(12, prodId = 'multexpr reduce'),
                        13: FRB.ParseNode(13, prodId = 'addexpr reduce'),
                        14: FRB.ParseNode(14, prodId = 'keyexpr reduce'),
                        15: FRB.ParseNode(15, prodId = 'ge'),
                        16: FRB.ParseNode(16, prodId = 'pred reduce'),
                        17: FRB.ParseNode(17, token = FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                        18: FRB.ParseNode(18, prodId = 'start'),
                     }, {3: [2], 4: [3], 5: [4], 6: [5], 7: [6], 10: [9], 11: [10], 12: [11], 13: [12], 14: [13], 15: [7, 8, 14], 16: [15], 18: [1, 16, 17]},
                     18)],

                     ['($\\swapvar < 7)', 
                      FRB.ParseTree({
                        1: FRB.ParseNode(1, token = FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                        2: FRB.ParseNode(2, token = FRB.Token('LPAREN', '(', 8, 1)),
                        3: FRB.ParseNode(3, token = FRB.Token('ID', '$\swapvar', 8, 2)),
                        4: FRB.ParseNode(4, prodId = 'variable'),
                        5: FRB.ParseNode(5, prodId = 'nterm reduce'),
                        6: FRB.ParseNode(6, prodId = 'multexpr reduce'),
                        7: FRB.ParseNode(7, prodId = 'addexpr reduce'),
                        8: FRB.ParseNode(8, prodId = 'keyexpr reduce'),
                        9: FRB.ParseNode(9, token = FRB.Token('LT', '<', 8, 12)),
                        10: FRB.ParseNode(10, token = FRB.Token('INT', '7', 8, 14)),
                        11: FRB.ParseNode(11, prodId = 'int'),
                        12: FRB.ParseNode(12, prodId = 'nterm reduce'),
                        13: FRB.ParseNode(13, prodId = 'multexpr reduce'),
                        14: FRB.ParseNode(14, prodId = 'addexpr reduce'),
                        15: FRB.ParseNode(15, prodId = 'keyexpr reduce'),
                        16: FRB.ParseNode(16, prodId = 'lt'),
                        17: FRB.ParseNode(17, prodId = 'pred reduce'),
                        18: FRB.ParseNode(18, token = FRB.Token('RPAREN', ')', 8, 15)),
                        19: FRB.ParseNode(19, prodId = 'bracket loop'),
                        20: FRB.ParseNode(20, prodId = 'nterm reduce'),
                        21: FRB.ParseNode(21, prodId = 'multexpr reduce'),
                        22: FRB.ParseNode(22, prodId = 'addexpr reduce'),
                        23: FRB.ParseNode(23, prodId = 'keyexpr reduce'),
                        24: FRB.ParseNode(24, prodId = 'test reduce'),
                        25: FRB.ParseNode(25, prodId = 'pred reduce'),
                        26: FRB.ParseNode(26, token = FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                        27: FRB.ParseNode(27, prodId = 'start'),
                      }, {4: [3], 5: [4], 6: [5], 7: [6], 8: [7], 11: [10], 12: [11], 13: [12], 14: [13], 15: [14], 16: [8, 9, 15], 17: [16], 19: [2, 17, 18], 20: [19], 21: [20], 22: [21], 23: [22], 24: [23], 25: [24], 27: [1, 25, 26]},
                      27)],

                      ['(($x >= 5 && $\\swapvar < (7 + 3.456 * -0.0)) || !($z[]%d >= 1 && $z[]%d < -9 && $123 == null)) \t && $\\~ + -234 -        -0 / -9.6',
                       FRB.ParseTree({
                        1: FRB.ParseNode(1, token = FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                        2: FRB.ParseNode(2, token = FRB.Token('LPAREN', '(', 8, 1)),
                        3: FRB.ParseNode(3, token = FRB.Token('LPAREN', '(', 8, 2)),
                        4: FRB.ParseNode(4, token = FRB.Token('ID', '$x', 8, 3)),
                        5: FRB.ParseNode(5, prodId = 'variable'),
                        6: FRB.ParseNode(6, prodId = 'nterm reduce'),
                        7: FRB.ParseNode(7, prodId = 'multexpr reduce'),
                        8: FRB.ParseNode(8, prodId = 'addexpr reduce'),
                        9: FRB.ParseNode(9, prodId = 'keyexpr reduce'),
                        10: FRB.ParseNode(10, token = FRB.Token('GE', '>=', 8, 6)),
                        11: FRB.ParseNode(11, token = FRB.Token('INT', '5', 8, 9)),
                        12: FRB.ParseNode(12, prodId = 'int'),
                        13: FRB.ParseNode(13, prodId = 'nterm reduce'),
                        14: FRB.ParseNode(14, prodId = 'multexpr reduce'),
                        15: FRB.ParseNode(15, prodId = 'addexpr reduce'),
                        16: FRB.ParseNode(16, prodId = 'keyexpr reduce'),
                        17: FRB.ParseNode(17, prodId = 'ge'),
                        18: FRB.ParseNode(18, prodId = 'pred reduce'),
                        19: FRB.ParseNode(19, token = FRB.Token('AND', '&&', 8, 11)),
                        20: FRB.ParseNode(20, token = FRB.Token('ID', '$\swapvar', 8, 14)),
                        21: FRB.ParseNode(21, prodId = 'variable'),
                        22: FRB.ParseNode(22, prodId = 'nterm reduce'),
                        23: FRB.ParseNode(23, prodId = 'multexpr reduce'),
                        24: FRB.ParseNode(24, prodId = 'addexpr reduce'),
                        25: FRB.ParseNode(25, prodId = 'keyexpr reduce'),
                        26: FRB.ParseNode(26, token = FRB.Token('LT', '<', 8, 24)),
                        27: FRB.ParseNode(27, token = FRB.Token('LPAREN', '(', 8, 26)),
                        28: FRB.ParseNode(28, token = FRB.Token('INT', '7', 8, 27)),
                        29: FRB.ParseNode(29, prodId = 'int'),
                        30: FRB.ParseNode(30, prodId = 'nterm reduce'),
                        31: FRB.ParseNode(31, prodId = 'multexpr reduce'),
                        32: FRB.ParseNode(32, prodId = 'addexpr reduce'),
                        33: FRB.ParseNode(33, token = FRB.Token('PLUS', '+', 8, 29)),
                        34: FRB.ParseNode(34, token = FRB.Token('FLOAT', '3.456', 8, 31)),
                        35: FRB.ParseNode(35, prodId = 'float'),
                        36: FRB.ParseNode(36, prodId = 'nterm reduce'),
                        37: FRB.ParseNode(37, prodId = 'multexpr reduce'),
                        38: FRB.ParseNode(38, token = FRB.Token('STAR', '*', 8, 37)),
                        39: FRB.ParseNode(39, token = FRB.Token('FLOAT', '-0.0', 8, 39)),
                        40: FRB.ParseNode(40, prodId = 'float'),
                        41: FRB.ParseNode(41, prodId = 'nterm reduce'),
                        42: FRB.ParseNode(42, prodId = 'multiply'),
                        43: FRB.ParseNode(43, prodId = 'add'),
                        44: FRB.ParseNode(44, prodId = 'keyexpr reduce'),
                        45: FRB.ParseNode(45, prodId = 'test reduce'),
                        46: FRB.ParseNode(46, prodId = 'pred reduce'),
                        47: FRB.ParseNode(47, token = FRB.Token('RPAREN', ')', 8, 43)),
                        48: FRB.ParseNode(48, prodId = 'bracket loop'),
                        49: FRB.ParseNode(49, prodId = 'nterm reduce'),
                        50: FRB.ParseNode(50, prodId = 'multexpr reduce'),
                        51: FRB.ParseNode(51, prodId = 'addexpr reduce'),
                        52: FRB.ParseNode(52, prodId = 'keyexpr reduce'),
                        53: FRB.ParseNode(53, prodId = 'lt'),
                        54: FRB.ParseNode(54, prodId = 'and'),
                        55: FRB.ParseNode(55, token = FRB.Token('RPAREN', ')', 8, 44)),
                        56: FRB.ParseNode(56, prodId = 'bracket loop'),
                        57: FRB.ParseNode(57, prodId = 'nterm reduce'),
                        58: FRB.ParseNode(58, prodId = 'multexpr reduce'),
                        59: FRB.ParseNode(59, prodId = 'addexpr reduce'),
                        60: FRB.ParseNode(60, prodId = 'keyexpr reduce'),
                        61: FRB.ParseNode(61, prodId = 'test reduce'),
                        62: FRB.ParseNode(62, prodId = 'pred reduce'),
                        63: FRB.ParseNode(63, token = FRB.Token('OR', '||', 8, 46)),
                        64: FRB.ParseNode(64, token = FRB.Token('NOT', '!', 8, 49)),
                        65: FRB.ParseNode(65, token = FRB.Token('LPAREN', '(', 8, 50)),
                        66: FRB.ParseNode(66, token = FRB.Token('ID', '$z[]%d', 8, 51)),
                        67: FRB.ParseNode(67, prodId = 'variable'),
                        68: FRB.ParseNode(68, prodId = 'nterm reduce'),
                        69: FRB.ParseNode(69, prodId = 'multexpr reduce'),
                        70: FRB.ParseNode(70, prodId = 'addexpr reduce'),
                        71: FRB.ParseNode(71, prodId = 'keyexpr reduce'),
                        72: FRB.ParseNode(72, token = FRB.Token('GE', '>=', 8, 58)),
                        73: FRB.ParseNode(73, token = FRB.Token('INT', '1', 8, 61)),
                        74: FRB.ParseNode(74, prodId = 'int'),
                        75: FRB.ParseNode(75, prodId = 'nterm reduce'),
                        76: FRB.ParseNode(76, prodId = 'multexpr reduce'),
                        77: FRB.ParseNode(77, prodId = 'addexpr reduce'),
                        78: FRB.ParseNode(78, prodId = 'keyexpr reduce'),
                        79: FRB.ParseNode(79, prodId = 'ge'),
                        80: FRB.ParseNode(80, prodId = 'pred reduce'),
                        81: FRB.ParseNode(81, token = FRB.Token('AND', '&&', 8, 63)),
                        82: FRB.ParseNode(82, token = FRB.Token('ID', '$z[]%d', 8, 66)),
                        83: FRB.ParseNode(83, prodId = 'variable'),
                        84: FRB.ParseNode(84, prodId = 'nterm reduce'),
                        85: FRB.ParseNode(85, prodId = 'multexpr reduce'),
                        86: FRB.ParseNode(86, prodId = 'addexpr reduce'),
                        87: FRB.ParseNode(87, prodId = 'keyexpr reduce'),
                        88: FRB.ParseNode(88, token = FRB.Token('LT', '<', 8, 73)),
                        89: FRB.ParseNode(89, token = FRB.Token('INT', '-9', 8, 75)),
                        90: FRB.ParseNode(90, prodId = 'int'),
                        91: FRB.ParseNode(91, prodId = 'nterm reduce'),
                        92: FRB.ParseNode(92, prodId = 'multexpr reduce'),
                        93: FRB.ParseNode(93, prodId = 'addexpr reduce'),
                        94: FRB.ParseNode(94, prodId = 'keyexpr reduce'),
                        95: FRB.ParseNode(95, prodId = 'lt'),
                        96: FRB.ParseNode(96, prodId = 'and'),
                        97: FRB.ParseNode(97, token = FRB.Token('AND', '&&', 8, 78)),
                        98: FRB.ParseNode(98, token = FRB.Token('ID', '$123', 8, 81)),
                        99: FRB.ParseNode(99, prodId = 'variable'),
                        100: FRB.ParseNode(100, prodId = 'nterm reduce'),
                        101: FRB.ParseNode(101, prodId = 'multexpr reduce'),
                        102: FRB.ParseNode(102, prodId = 'addexpr reduce'),
                        103: FRB.ParseNode(103, prodId = 'keyexpr reduce'),
                        104: FRB.ParseNode(104, token = FRB.Token('EQ', '==', 8, 86)),
                        105: FRB.ParseNode(105, token = FRB.Token('NULL', 'null', 8, 89)),
                        106: FRB.ParseNode(106, prodId = 'null'),
                        107: FRB.ParseNode(107, prodId = 'eq'),
                        108: FRB.ParseNode(108, prodId = 'and'),
                        109: FRB.ParseNode(109, token = FRB.Token('RPAREN', ')', 8, 93)),
                        110: FRB.ParseNode(110, prodId = 'bracket loop'),
                        111: FRB.ParseNode(111, prodId = 'nterm reduce'),
                        112: FRB.ParseNode(112, prodId = 'not'),
                        113: FRB.ParseNode(113, prodId = 'multexpr reduce'),
                        114: FRB.ParseNode(114, prodId = 'addexpr reduce'),
                        115: FRB.ParseNode(115, prodId = 'keyexpr reduce'),
                        116: FRB.ParseNode(116, prodId = 'test reduce'),
                        117: FRB.ParseNode(117, prodId = 'or'),
                        118: FRB.ParseNode(118, token = FRB.Token('RPAREN', ')', 8, 94)),
                        119: FRB.ParseNode(119, prodId = 'bracket loop'),
                        120: FRB.ParseNode(120, prodId = 'nterm reduce'),
                        121: FRB.ParseNode(121, prodId = 'multexpr reduce'),
                        122: FRB.ParseNode(122, prodId = 'addexpr reduce'),
                        123: FRB.ParseNode(123, prodId = 'keyexpr reduce'),
                        124: FRB.ParseNode(124, prodId = 'test reduce'),
                        125: FRB.ParseNode(125, prodId = 'pred reduce'),
                        126: FRB.ParseNode(126, token = FRB.Token('AND', '&&', 8, 98)),
                        127: FRB.ParseNode(127, token = FRB.Token('ID', '$\~', 8, 101)),
                        128: FRB.ParseNode(128, prodId = 'variable'),
                        129: FRB.ParseNode(129, prodId = 'nterm reduce'),
                        130: FRB.ParseNode(130, prodId = 'multexpr reduce'),
                        131: FRB.ParseNode(131, prodId = 'addexpr reduce'),
                        132: FRB.ParseNode(132, token = FRB.Token('PLUS', '+', 8, 105)),
                        133: FRB.ParseNode(133, token = FRB.Token('INT', '-234', 8, 107)),
                        134: FRB.ParseNode(134, prodId = 'int'),
                        135: FRB.ParseNode(135, prodId = 'nterm reduce'),
                        136: FRB.ParseNode(136, prodId = 'multexpr reduce'),
                        137: FRB.ParseNode(137, prodId = 'add'),
                        138: FRB.ParseNode(138, token = FRB.Token('MINUS', '-', 8, 112)),
                        139: FRB.ParseNode(139, token = FRB.Token('INT', '-0', 8, 121)),
                        140: FRB.ParseNode(140, prodId = 'int'),
                        141: FRB.ParseNode(141, prodId = 'nterm reduce'),
                        142: FRB.ParseNode(142, prodId = 'multexpr reduce'),
                        143: FRB.ParseNode(143, token = FRB.Token('SLASH', '/', 8, 124)),
                        144: FRB.ParseNode(144, token = FRB.Token('FLOAT', '-9.6', 8, 126)),
                        145: FRB.ParseNode(145, prodId = 'float'),
                        146: FRB.ParseNode(146, prodId = 'nterm reduce'),
                        147: FRB.ParseNode(147, prodId = 'divide'),
                        148: FRB.ParseNode(148, prodId = 'subtract'),
                        149: FRB.ParseNode(149, prodId = 'keyexpr reduce'),
                        150: FRB.ParseNode(150, prodId = 'test reduce'),
                        151: FRB.ParseNode(151, prodId = 'and'),
                        152: FRB.ParseNode(152, token = FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                        153: FRB.ParseNode(153, prodId = 'start'),
                       }, {5: [4], 6: [5], 7: [6], 8: [7], 9: [8], 12: [11], 13: [12], 14: [13], 15: [14], 16: [15], 17: [9, 10, 16], 18: [17], 21: [20], 22: [21], 23: [22], 24: [23], 25: [24], 29: [28], 30: [29], 
                           31: [30], 32: [31], 35: [34], 36: [35], 37: [36], 40: [39], 41: [40], 42: [37, 38, 41], 43: [32, 33, 42], 44: [43], 45: [44], 46: [45], 48: [27, 46, 47], 49: [48], 50: [49], 51: [50], 52: [51], 
                           53: [25, 26, 52], 54: [18, 19, 53], 56: [3, 54, 55], 57: [56], 58: [57], 59: [58], 60: [59], 61: [60], 62: [61], 67: [66], 68: [67], 69: [68], 70: [69], 71: [70], 74: [73], 75: [74], 76: [75], 
                           77: [76], 78: [77], 79: [71, 72, 78], 80: [79], 83: [82], 84: [83], 85: [84], 86: [85], 87: [86], 90: [89], 91: [90], 92: [91], 93: [92], 94: [93], 95: [87, 88, 94], 96: [80, 81, 95], 99: [98], 
                           100: [99], 101: [100], 102: [101], 103: [102], 106: [105], 107: [103, 104, 106], 108: [96, 97, 107], 110: [65, 108, 109], 111: [110], 112: [64, 111], 113: [112], 114: [113], 115: [114], 116: [115], 
                           117: [62, 63, 116], 119: [2, 117, 118], 120: [119], 121: [120], 122: [121], 123: [122], 124: [123], 125: [124], 128: [127], 129: [128], 130: [129], 131: [130], 134: [133], 135: [134], 136: [135], 
                           137: [131, 132, 136], 140: [139], 141: [140], 142: [141], 145: [144], 146: [145], 147: [142, 143, 146], 148: [137, 138, 147], 149: [148], 150: [149], 151: [125, 126, 150], 153: [1, 151, 152]},
                           153)],

                    ['(($x >= 5 && $\\swapvar < (7 + 3.456 * -0.0)) || !($z[]%d >= 1 && $z[]%d < -9 && $123 == null)) \t && $\\~ + -234 -        -0 / -9.6)', 
                     FRB.Token("RPAREN", ")", 8, 130)],
                    ['!!(!$a + 8 && $b > !8)',
                     FRB.ParseTree({
                        1: FRB.ParseNode(1, token = FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                        2: FRB.ParseNode(2, token = FRB.Token('NOT', '!', 8, 1)),
                        3: FRB.ParseNode(3, token = FRB.Token('NOT', '!', 8, 2)),
                        4: FRB.ParseNode(4, token = FRB.Token('LPAREN', '(', 8, 3)),
                        5: FRB.ParseNode(5, token = FRB.Token('NOT', '!', 8, 4)),
                        6: FRB.ParseNode(6, token = FRB.Token('ID', '$a', 8, 5)),
                        7: FRB.ParseNode(7, prodId = 'variable'),
                        8: FRB.ParseNode(8, prodId = 'nterm reduce'),
                        9: FRB.ParseNode(9, prodId = 'not'),
                        10: FRB.ParseNode(10, prodId = 'multexpr reduce'),
                        11: FRB.ParseNode(11, prodId = 'addexpr reduce'),
                        12: FRB.ParseNode(12, token = FRB.Token('PLUS', '+', 8, 8)),
                        13: FRB.ParseNode(13, token = FRB.Token('INT', '8', 8, 10)),
                        14: FRB.ParseNode(14, prodId = 'int'),
                        15: FRB.ParseNode(15, prodId = 'nterm reduce'),
                        16: FRB.ParseNode(16, prodId = 'multexpr reduce'),
                        17: FRB.ParseNode(17, prodId = 'add'),
                        18: FRB.ParseNode(18, prodId = 'keyexpr reduce'),
                        19: FRB.ParseNode(19, prodId = 'test reduce'),
                        20: FRB.ParseNode(20, prodId = 'pred reduce'),
                        21: FRB.ParseNode(21, token = FRB.Token('AND', '&&', 8, 12)),
                        22: FRB.ParseNode(22, token = FRB.Token('ID', '$b', 8, 15)),
                        23: FRB.ParseNode(23, prodId = 'variable'),
                        24: FRB.ParseNode(24, prodId = 'nterm reduce'),
                        25: FRB.ParseNode(25, prodId = 'multexpr reduce'),
                        26: FRB.ParseNode(26, prodId = 'addexpr reduce'),
                        27: FRB.ParseNode(27, prodId = 'keyexpr reduce'),
                        28: FRB.ParseNode(28, token = FRB.Token('GT', '>', 8, 18)),
                        29: FRB.ParseNode(29, token = FRB.Token('NOT', '!', 8, 20)),
                        30: FRB.ParseNode(30, token = FRB.Token('INT', '8', 8, 21)),
                        31: FRB.ParseNode(31, prodId = 'int'),
                        32: FRB.ParseNode(32, prodId = 'nterm reduce'),
                        33: FRB.ParseNode(33, prodId = 'not'),
                        34: FRB.ParseNode(34, prodId = 'multexpr reduce'),
                        35: FRB.ParseNode(35, prodId = 'addexpr reduce'),
                        36: FRB.ParseNode(36, prodId = 'keyexpr reduce'),
                        37: FRB.ParseNode(37, prodId = 'gt'),
                        38: FRB.ParseNode(38, prodId = 'and'),
                        39: FRB.ParseNode(39, token = FRB.Token('RPAREN', ')', 8, 22)),
                        40: FRB.ParseNode(40, prodId = 'bracket loop'),
                        41: FRB.ParseNode(41, prodId = 'nterm reduce'),
                        42: FRB.ParseNode(42, prodId = 'not'),
                        43: FRB.ParseNode(43, prodId = 'not'),
                        44: FRB.ParseNode(44, prodId = 'multexpr reduce'),
                        45: FRB.ParseNode(45, prodId = 'addexpr reduce'),
                        46: FRB.ParseNode(46, prodId = 'keyexpr reduce'),
                        47: FRB.ParseNode(47, prodId = 'test reduce'),
                        48: FRB.ParseNode(48, prodId = 'pred reduce'),
                        49: FRB.ParseNode(49, token = FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                        50: FRB.ParseNode(50, prodId = 'start'),
                      }, {7: [6], 8: [7], 9: [5, 8], 10: [9], 11: [10], 14: [13], 15: [14], 16: [15], 17: [11, 12, 16], 18: [17], 19: [18], 20: [19], 23: [22], 24: [23], 
                          25: [24], 26: [25], 27: [26], 31: [30], 32: [31], 33: [29, 32], 34: [33], 35: [34], 36: [35], 37: [27, 28, 36], 38: [20, 21, 37], 40: [4, 38, 39], 
                          41: [40], 42: [3, 41], 43: [2, 42], 44: [43], 45: [44], 46: [45], 47: [46], 48: [47], 50: [1, 48, 49]},
                      50)]
                 ]

        for test in tests:
            inputText = test[0]
            expected = test[1]

            ctx = FRB.ParseContext(inputText, file = file, startLineNo = startLineNo)
            tokens = self._tokenizer.simplifiedMaximalMunch(ctx)

            error = None
            result = None
            try:
                result = self._parser.parse(tokens, ctx = ctx)
            except FRB.SyntaxErr as e:
                error = e

            if (error is not None):
                expected = FRB.SyntaxErr(ctx, expected, process = "parsing")
                self.compareSyntaxErr(error, expected)
            else:
                self.compareParseTreeShape(result, expected)

    # ================================================