import sys

from .baseUnitTest import BaseUnitTest
from ..src.Config import Configs
from ..src.constants.ConfigKeys import ConfigKeys

sys.path.insert(1, Configs[ConfigKeys.SysPath])
import src.py.FixRaidenBoss2 as FRB


class SympyParserTest(BaseUnitTest):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()

        cls._tokenizer = FRB.SympyTokenizer()
        cls._tokenizer.setup()

    def setUp(self):
        super().setUp()

        # See IfPredParserTest's identically-shaped setUp for why this is a fresh parser per test
        # rather than a shared, mock-driven one.
        self._parser = FRB.SympyParser()

    # ================== parse =======================

    def test_differentIfPreds_ifPredsParsed(self):
        file = "MyFile.agr"
        startLineNo = 8

        tests = [
                    [" ", 
                     FRB.ParseTree({
                         1: FRB.ParseNode(1, token=FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                         2: FRB.ParseNode(2, token=FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                         3: FRB.ParseNode(3, prodId="start empty"),
                     },
                     {3: [1, 2]},
                     3)],

                    ["$swapvar$ == 5", 
                     FRB.ParseTree({
                        1: FRB.ParseNode(1, token = FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                        2: FRB.ParseNode(2, token = FRB.Token('ID', '$swapvar$', 8, 1)),
                        3: FRB.ParseNode(3, prodId = 'variable'),
                        4: FRB.ParseNode(4, prodId = 'nterm reduce'),
                        5: FRB.ParseNode(5, prodId = 'multexpr reduce'),
                        6: FRB.ParseNode(6, prodId = 'addexpr reduce'),
                        7: FRB.ParseNode(7, prodId = 'keyexpr reduce'),
                        8: FRB.ParseNode(8, token = FRB.Token('EQ', '==', 8, 11)),
                        9: FRB.ParseNode(9, token = FRB.Token('INT', '5', 8, 14)),
                        10: FRB.ParseNode(10, prodId = 'int'),
                        11: FRB.ParseNode(11, prodId = 'nterm reduce'),
                        12: FRB.ParseNode(12, prodId = 'multexpr reduce'),
                        13: FRB.ParseNode(13, prodId = 'addexpr reduce'),
                        14: FRB.ParseNode(14, prodId = 'keyexpr reduce'),
                        15: FRB.ParseNode(15, prodId = 'eq'),
                        16: FRB.ParseNode(16, prodId = 'pred reduce'),
                        17: FRB.ParseNode(17, token = FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                        18: FRB.ParseNode(18, prodId = 'start')
                    },
                    {3: [2], 4: [3], 5: [4], 6: [5], 7: [6], 10: [9], 11: [10], 12: [11], 13: [12], 14: [13], 15: [7, 8, 14], 16: [15], 18: [1, 16, 17]},
                    18)],

                    ["Eq($swapvar$, 5)", 
                     FRB.ParseTree({
                        1: FRB.ParseNode(1, token = FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                        2: FRB.ParseNode(2, token = FRB.Token('EQFUNC', 'Eq', 8, 1)),
                        3: FRB.ParseNode(3, token = FRB.Token('LPAREN', '(', 8, 3)),
                        4: FRB.ParseNode(4, token = FRB.Token('ID', '$swapvar$', 8, 4)),
                        5: FRB.ParseNode(5, prodId = 'variable'),
                        6: FRB.ParseNode(6, prodId = 'nterm reduce'),
                        7: FRB.ParseNode(7, prodId = 'multexpr reduce'),
                        8: FRB.ParseNode(8, prodId = 'addexpr reduce'),
                        9: FRB.ParseNode(9, prodId = 'keyexpr reduce'),
                        10: FRB.ParseNode(10, prodId = 'test reduce'),
                        11: FRB.ParseNode(11, prodId = 'pred reduce'),
                        12: FRB.ParseNode(12, token = FRB.Token('COMMA', ',', 8, 13)),
                        13: FRB.ParseNode(13, token = FRB.Token('INT', '5', 8, 15)),
                        14: FRB.ParseNode(14, prodId = 'int'),
                        15: FRB.ParseNode(15, prodId = 'nterm reduce'),
                        16: FRB.ParseNode(16, prodId = 'multexpr reduce'),
                        17: FRB.ParseNode(17, prodId = 'addexpr reduce'),
                        18: FRB.ParseNode(18, prodId = 'keyexpr reduce'),
                        19: FRB.ParseNode(19, prodId = 'test reduce'),
                        20: FRB.ParseNode(20, prodId = 'pred reduce'),
                        21: FRB.ParseNode(21, token = FRB.Token('RPAREN', ')', 8, 16)),
                        22: FRB.ParseNode(22, prodId = 'eq func'),
                        23: FRB.ParseNode(23, prodId = 'pred reduce'),
                        24: FRB.ParseNode(24, token = FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                        25: FRB.ParseNode(25, prodId = 'start')
                     }, 
                     {5: [4], 6: [5], 7: [6], 8: [7], 9: [8], 10: [9], 11: [10], 14: [13], 15: [14], 16: [15], 
                      17: [16], 18: [17], 19: [18], 20: [19], 22: [2, 3, 11, 12, 20, 21], 23: [22], 25: [1, 23, 24]},
                     25)],

                    ['$x$ >= 5', 
                     FRB.ParseTree({
                        1: FRB.ParseNode(1, token = FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                        2: FRB.ParseNode(2, token = FRB.Token('ID', '$x$', 8, 1)),
                        3: FRB.ParseNode(3, prodId = 'variable'),
                        4: FRB.ParseNode(4, prodId = 'nterm reduce'),
                        5: FRB.ParseNode(5, prodId = 'multexpr reduce'),
                        6: FRB.ParseNode(6, prodId = 'addexpr reduce'),
                        7: FRB.ParseNode(7, prodId = 'keyexpr reduce'),
                        8: FRB.ParseNode(8, token = FRB.Token('GE', '>=', 8, 5)),
                        9: FRB.ParseNode(9, token = FRB.Token('INT', '5', 8, 8)),
                        10: FRB.ParseNode(10, prodId = 'int'),
                        11: FRB.ParseNode(11, prodId = 'nterm reduce'),
                        12: FRB.ParseNode(12, prodId = 'multexpr reduce'),
                        13: FRB.ParseNode(13, prodId = 'addexpr reduce'),
                        14: FRB.ParseNode(14, prodId = 'keyexpr reduce'),
                        15: FRB.ParseNode(15, prodId = 'ge'),
                        16: FRB.ParseNode(16, prodId = 'pred reduce'),
                        17: FRB.ParseNode(17, token = FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                        18: FRB.ParseNode(18, prodId = 'start')
                     }, {3: [2], 4: [3], 5: [4], 6: [5], 7: [6], 10: [9], 11: [10], 12: [11], 13: [12], 14: [13], 15: [7, 8, 14], 16: [15], 18: [1, 16, 17]},
                     18)],

                     ['Ge($x$, 5)', 
                      FRB.ParseTree({
                        1: FRB.ParseNode(1, token = FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                        2: FRB.ParseNode(2, token = FRB.Token('GEFUNC', 'Ge', 8, 1)),
                        3: FRB.ParseNode(3, token = FRB.Token('LPAREN', '(', 8, 3)),
                        4: FRB.ParseNode(4, token = FRB.Token('ID', '$x$', 8, 4)),
                        5: FRB.ParseNode(5, prodId = 'variable'),
                        6: FRB.ParseNode(6, prodId = 'nterm reduce'),
                        7: FRB.ParseNode(7, prodId = 'multexpr reduce'),
                        8: FRB.ParseNode(8, prodId = 'addexpr reduce'),
                        9: FRB.ParseNode(9, prodId = 'keyexpr reduce'),
                        10: FRB.ParseNode(10, prodId = 'test reduce'),
                        11: FRB.ParseNode(11, prodId = 'pred reduce'),
                        12: FRB.ParseNode(12, token = FRB.Token('COMMA', ',', 8, 7)),
                        13: FRB.ParseNode(13, token = FRB.Token('INT', '5', 8, 9)),
                        14: FRB.ParseNode(14, prodId = 'int'),
                        15: FRB.ParseNode(15, prodId = 'nterm reduce'),
                        16: FRB.ParseNode(16, prodId = 'multexpr reduce'),
                        17: FRB.ParseNode(17, prodId = 'addexpr reduce'),
                        18: FRB.ParseNode(18, prodId = 'keyexpr reduce'),
                        19: FRB.ParseNode(19, prodId = 'test reduce'),
                        20: FRB.ParseNode(20, prodId = 'pred reduce'),
                        21: FRB.ParseNode(21, token = FRB.Token('RPAREN', ')', 8, 10)),
                        22: FRB.ParseNode(22, prodId = 'ge func'),
                        23: FRB.ParseNode(23, prodId = 'pred reduce'),
                        24: FRB.ParseNode(24, token = FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                        25: FRB.ParseNode(25, prodId = 'start')
                     }, {5: [4], 6: [5], 7: [6], 8: [7], 9: [8], 10: [9], 11: [10], 14: [13], 15: [14], 
                         16: [15], 17: [16], 18: [17], 19: [18], 20: [19], 22: [2, 3, 11, 12, 20, 21], 23: [22], 25: [1, 23, 24]},
                     25)],

                    ['And($x$ == 0, $y$ != False, $z$ <= 8, $a$ >= True, Or(True, False), Or(8, 5))',
                      FRB.ParseTree({
                        1: FRB.ParseNode(1, token = FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                        2: FRB.ParseNode(2, token = FRB.Token('ANDFUNC', 'And', 8, 1)),
                        3: FRB.ParseNode(3, token = FRB.Token('LPAREN', '(', 8, 4)),
                        4: FRB.ParseNode(4, token = FRB.Token('ID', '$x$', 8, 5)),
                        5: FRB.ParseNode(5, prodId = 'variable'),
                        6: FRB.ParseNode(6, prodId = 'nterm reduce'),
                        7: FRB.ParseNode(7, prodId = 'multexpr reduce'),
                        8: FRB.ParseNode(8, prodId = 'addexpr reduce'),
                        9: FRB.ParseNode(9, prodId = 'keyexpr reduce'),
                        10: FRB.ParseNode(10, token = FRB.Token('EQ', '==', 8, 9)),
                        11: FRB.ParseNode(11, token = FRB.Token('INT', '0', 8, 12)),
                        12: FRB.ParseNode(12, prodId = 'int'),
                        13: FRB.ParseNode(13, prodId = 'nterm reduce'),
                        14: FRB.ParseNode(14, prodId = 'multexpr reduce'),
                        15: FRB.ParseNode(15, prodId = 'addexpr reduce'),
                        16: FRB.ParseNode(16, prodId = 'keyexpr reduce'),
                        17: FRB.ParseNode(17, prodId = 'eq'),
                        18: FRB.ParseNode(18, prodId = 'pred reduce'),
                        19: FRB.ParseNode(19, prodId = 'pred args reduce'),
                        20: FRB.ParseNode(20, token = FRB.Token('COMMA', ',', 8, 13)),
                        21: FRB.ParseNode(21, token = FRB.Token('ID', '$y$', 8, 15)),
                        22: FRB.ParseNode(22, prodId = 'variable'),
                        23: FRB.ParseNode(23, prodId = 'nterm reduce'),
                        24: FRB.ParseNode(24, prodId = 'multexpr reduce'),
                        25: FRB.ParseNode(25, prodId = 'addexpr reduce'),
                        26: FRB.ParseNode(26, prodId = 'keyexpr reduce'),
                        27: FRB.ParseNode(27, token = FRB.Token('NE', '!=', 8, 19)),
                        28: FRB.ParseNode(28, token = FRB.Token('FALSE', 'False', 8, 22)),
                        29: FRB.ParseNode(29, prodId = 'false'),
                        30: FRB.ParseNode(30, prodId = 'ne'),
                        31: FRB.ParseNode(31, prodId = 'pred reduce'),
                        32: FRB.ParseNode(32, prodId = 'pred arg list'),
                        33: FRB.ParseNode(33, token = FRB.Token('COMMA', ',', 8, 27)),
                        34: FRB.ParseNode(34, token = FRB.Token('ID', '$z$', 8, 29)),
                        35: FRB.ParseNode(35, prodId = 'variable'),
                        36: FRB.ParseNode(36, prodId = 'nterm reduce'),
                        37: FRB.ParseNode(37, prodId = 'multexpr reduce'),
                        38: FRB.ParseNode(38, prodId = 'addexpr reduce'),
                        39: FRB.ParseNode(39, prodId = 'keyexpr reduce'),
                        40: FRB.ParseNode(40, token = FRB.Token('LE', '<=', 8, 33)),
                        41: FRB.ParseNode(41, token = FRB.Token('INT', '8', 8, 36)),
                        42: FRB.ParseNode(42, prodId = 'int'),
                        43: FRB.ParseNode(43, prodId = 'nterm reduce'),
                        44: FRB.ParseNode(44, prodId = 'multexpr reduce'),
                        45: FRB.ParseNode(45, prodId = 'addexpr reduce'),
                        46: FRB.ParseNode(46, prodId = 'keyexpr reduce'),
                        47: FRB.ParseNode(47, prodId = 'le'),
                        48: FRB.ParseNode(48, prodId = 'pred reduce'),
                        49: FRB.ParseNode(49, prodId = 'pred arg list'),
                        50: FRB.ParseNode(50, token = FRB.Token('COMMA', ',', 8, 37)),
                        51: FRB.ParseNode(51, token = FRB.Token('ID', '$a$', 8, 39)),
                        52: FRB.ParseNode(52, prodId = 'variable'),
                        53: FRB.ParseNode(53, prodId = 'nterm reduce'),
                        54: FRB.ParseNode(54, prodId = 'multexpr reduce'),
                        55: FRB.ParseNode(55, prodId = 'addexpr reduce'),
                        56: FRB.ParseNode(56, prodId = 'keyexpr reduce'),
                        57: FRB.ParseNode(57, token = FRB.Token('GE', '>=', 8, 43)),
                        58: FRB.ParseNode(58, token = FRB.Token('TRUE', 'True', 8, 46)),
                        59: FRB.ParseNode(59, prodId = 'true'),
                        60: FRB.ParseNode(60, prodId = 'ge'),
                        61: FRB.ParseNode(61, prodId = 'pred reduce'),
                        62: FRB.ParseNode(62, prodId = 'pred arg list'),
                        63: FRB.ParseNode(63, token = FRB.Token('COMMA', ',', 8, 50)),
                        64: FRB.ParseNode(64, token = FRB.Token('ORFUNC', 'Or', 8, 52)),
                        65: FRB.ParseNode(65, token = FRB.Token('LPAREN', '(', 8, 54)),
                        66: FRB.ParseNode(66, token = FRB.Token('TRUE', 'True', 8, 55)),
                        67: FRB.ParseNode(67, prodId = 'true'),
                        68: FRB.ParseNode(68, prodId = 'test reduce'),
                        69: FRB.ParseNode(69, prodId = 'pred reduce'),
                        70: FRB.ParseNode(70, prodId = 'pred args reduce'),
                        71: FRB.ParseNode(71, token = FRB.Token('COMMA', ',', 8, 59)),
                        72: FRB.ParseNode(72, token = FRB.Token('FALSE', 'False', 8, 61)),
                        73: FRB.ParseNode(73, prodId = 'false'),
                        74: FRB.ParseNode(74, prodId = 'test reduce'),
                        75: FRB.ParseNode(75, prodId = 'pred reduce'),
                        76: FRB.ParseNode(76, prodId = 'pred arg list'),
                        77: FRB.ParseNode(77, token = FRB.Token('RPAREN', ')', 8, 66)),
                        78: FRB.ParseNode(78, prodId = 'or func'),
                        79: FRB.ParseNode(79, prodId = 'pred arg list'),
                        80: FRB.ParseNode(80, token = FRB.Token('COMMA', ',', 8, 67)),
                        81: FRB.ParseNode(81, token = FRB.Token('ORFUNC', 'Or', 8, 69)),
                        82: FRB.ParseNode(82, token = FRB.Token('LPAREN', '(', 8, 71)),
                        83: FRB.ParseNode(83, token = FRB.Token('INT', '8', 8, 72)),
                        84: FRB.ParseNode(84, prodId = 'int'),
                        85: FRB.ParseNode(85, prodId = 'nterm reduce'),
                        86: FRB.ParseNode(86, prodId = 'multexpr reduce'),
                        87: FRB.ParseNode(87, prodId = 'addexpr reduce'),
                        88: FRB.ParseNode(88, prodId = 'keyexpr reduce'),
                        89: FRB.ParseNode(89, prodId = 'test reduce'),
                        90: FRB.ParseNode(90, prodId = 'pred reduce'),
                        91: FRB.ParseNode(91, prodId = 'pred args reduce'),
                        92: FRB.ParseNode(92, token = FRB.Token('COMMA', ',', 8, 73)),
                        93: FRB.ParseNode(93, token = FRB.Token('INT', '5', 8, 75)),
                        94: FRB.ParseNode(94, prodId = 'int'),
                        95: FRB.ParseNode(95, prodId = 'nterm reduce'),
                        96: FRB.ParseNode(96, prodId = 'multexpr reduce'),
                        97: FRB.ParseNode(97, prodId = 'addexpr reduce'),
                        98: FRB.ParseNode(98, prodId = 'keyexpr reduce'),
                        99: FRB.ParseNode(99, prodId = 'test reduce'),
                        100: FRB.ParseNode(100, prodId = 'pred reduce'),
                        101: FRB.ParseNode(101, prodId = 'pred arg list'),
                        102: FRB.ParseNode(102, token = FRB.Token('RPAREN', ')', 8, 76)),
                        103: FRB.ParseNode(103, prodId = 'or func'),
                        104: FRB.ParseNode(104, prodId = 'pred arg list'),
                        105: FRB.ParseNode(105, token = FRB.Token('RPAREN', ')', 8, 77)),
                        106: FRB.ParseNode(106, prodId = 'and func'),
                        107: FRB.ParseNode(107, token = FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                        108: FRB.ParseNode(108, prodId = 'start'),
                     }, {5: [4], 6: [5], 7: [6], 8: [7], 9: [8], 12: [11], 13: [12], 14: [13], 15: [14], 16: [15], 17: [9, 10, 16], 18: [17], 19: [18], 22: [21], 23: [22], 
                         24: [23], 25: [24], 26: [25], 29: [28], 30: [26, 27, 29], 31: [30], 32: [19, 20, 31], 35: [34], 36: [35], 37: [36], 38: [37], 39: [38], 42: [41], 
                         43: [42], 44: [43], 45: [44], 46: [45], 47: [39, 40, 46], 48: [47], 49: [32, 33, 48], 52: [51], 53: [52], 54: [53], 55: [54], 56: [55], 59: [58], 
                         60: [56, 57, 59], 61: [60], 62: [49, 50, 61], 67: [66], 68: [67], 69: [68], 70: [69], 73: [72], 74: [73], 75: [74], 76: [70, 71, 75], 78: [64, 65, 76, 77], 
                         79: [62, 63, 78], 84: [83], 85: [84], 86: [85], 87: [86], 88: [87], 89: [88], 90: [89], 91: [90], 94: [93], 95: [94], 96: [95], 97: [96], 98: [97], 99: [98], 
                         100: [99], 101: [91, 92, 100], 103: [81, 82, 101, 102], 104: [79, 80, 103], 106: [2, 3, 104, 105], 108: [1, 106, 107]},
                     108)],

                    ["Eq($x$, And($y$, True, Gt($z$, False), Or(True, False, $a$ > 8)))",
                     FRB.ParseTree({
                        1: FRB.ParseNode(1, token = FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                        2: FRB.ParseNode(2, token = FRB.Token('EQFUNC', 'Eq', 8, 1)),
                        3: FRB.ParseNode(3, token = FRB.Token('LPAREN', '(', 8, 3)),
                        4: FRB.ParseNode(4, token = FRB.Token('ID', '$x$', 8, 4)),
                        5: FRB.ParseNode(5, prodId = 'variable'),
                        6: FRB.ParseNode(6, prodId = 'nterm reduce'),
                        7: FRB.ParseNode(7, prodId = 'multexpr reduce'),
                        8: FRB.ParseNode(8, prodId = 'addexpr reduce'),
                        9: FRB.ParseNode(9, prodId = 'keyexpr reduce'),
                        10: FRB.ParseNode(10, prodId = 'test reduce'),
                        11: FRB.ParseNode(11, prodId = 'pred reduce'),
                        12: FRB.ParseNode(12, token = FRB.Token('COMMA', ',', 8, 7)),
                        13: FRB.ParseNode(13, token = FRB.Token('ANDFUNC', 'And', 8, 9)),
                        14: FRB.ParseNode(14, token = FRB.Token('LPAREN', '(', 8, 12)),
                        15: FRB.ParseNode(15, token = FRB.Token('ID', '$y$', 8, 13)),
                        16: FRB.ParseNode(16, prodId = 'variable'),
                        17: FRB.ParseNode(17, prodId = 'nterm reduce'),
                        18: FRB.ParseNode(18, prodId = 'multexpr reduce'),
                        19: FRB.ParseNode(19, prodId = 'addexpr reduce'),
                        20: FRB.ParseNode(20, prodId = 'keyexpr reduce'),
                        21: FRB.ParseNode(21, prodId = 'test reduce'),
                        22: FRB.ParseNode(22, prodId = 'pred reduce'),
                        23: FRB.ParseNode(23, prodId = 'pred args reduce'),
                        24: FRB.ParseNode(24, token = FRB.Token('COMMA', ',', 8, 16)),
                        25: FRB.ParseNode(25, token = FRB.Token('TRUE', 'True', 8, 18)),
                        26: FRB.ParseNode(26, prodId = 'true'),
                        27: FRB.ParseNode(27, prodId = 'test reduce'),
                        28: FRB.ParseNode(28, prodId = 'pred reduce'),
                        29: FRB.ParseNode(29, prodId = 'pred arg list'),
                        30: FRB.ParseNode(30, token = FRB.Token('COMMA', ',', 8, 22)),
                        31: FRB.ParseNode(31, token = FRB.Token('GTFUNC', 'Gt', 8, 24)),
                        32: FRB.ParseNode(32, token = FRB.Token('LPAREN', '(', 8, 26)),
                        33: FRB.ParseNode(33, token = FRB.Token('ID', '$z$', 8, 27)),
                        34: FRB.ParseNode(34, prodId = 'variable'),
                        35: FRB.ParseNode(35, prodId = 'nterm reduce'),
                        36: FRB.ParseNode(36, prodId = 'multexpr reduce'),
                        37: FRB.ParseNode(37, prodId = 'addexpr reduce'),
                        38: FRB.ParseNode(38, prodId = 'keyexpr reduce'),
                        39: FRB.ParseNode(39, prodId = 'test reduce'),
                        40: FRB.ParseNode(40, prodId = 'pred reduce'),
                        41: FRB.ParseNode(41, token = FRB.Token('COMMA', ',', 8, 30)),
                        42: FRB.ParseNode(42, token = FRB.Token('FALSE', 'False', 8, 32)),
                        43: FRB.ParseNode(43, prodId = 'false'),
                        44: FRB.ParseNode(44, prodId = 'test reduce'),
                        45: FRB.ParseNode(45, prodId = 'pred reduce'),
                        46: FRB.ParseNode(46, token = FRB.Token('RPAREN', ')', 8, 37)),
                        47: FRB.ParseNode(47, prodId = 'gt func'),
                        48: FRB.ParseNode(48, prodId = 'pred reduce'),
                        49: FRB.ParseNode(49, prodId = 'pred arg list'),
                        50: FRB.ParseNode(50, token = FRB.Token('COMMA', ',', 8, 38)),
                        51: FRB.ParseNode(51, token = FRB.Token('ORFUNC', 'Or', 8, 40)),
                        52: FRB.ParseNode(52, token = FRB.Token('LPAREN', '(', 8, 42)),
                        53: FRB.ParseNode(53, token = FRB.Token('TRUE', 'True', 8, 43)),
                        54: FRB.ParseNode(54, prodId = 'true'),
                        55: FRB.ParseNode(55, prodId = 'test reduce'),
                        56: FRB.ParseNode(56, prodId = 'pred reduce'),
                        57: FRB.ParseNode(57, prodId = 'pred args reduce'),
                        58: FRB.ParseNode(58, token = FRB.Token('COMMA', ',', 8, 47)),
                        59: FRB.ParseNode(59, token = FRB.Token('FALSE', 'False', 8, 49)),
                        60: FRB.ParseNode(60, prodId = 'false'),
                        61: FRB.ParseNode(61, prodId = 'test reduce'),
                        62: FRB.ParseNode(62, prodId = 'pred reduce'),
                        63: FRB.ParseNode(63, prodId = 'pred arg list'),
                        64: FRB.ParseNode(64, token = FRB.Token('COMMA', ',', 8, 54)),
                        65: FRB.ParseNode(65, token = FRB.Token('ID', '$a$', 8, 56)),
                        66: FRB.ParseNode(66, prodId = 'variable'),
                        67: FRB.ParseNode(67, prodId = 'nterm reduce'),
                        68: FRB.ParseNode(68, prodId = 'multexpr reduce'),
                        69: FRB.ParseNode(69, prodId = 'addexpr reduce'),
                        70: FRB.ParseNode(70, prodId = 'keyexpr reduce'),
                        71: FRB.ParseNode(71, token = FRB.Token('GT', '>', 8, 60)),
                        72: FRB.ParseNode(72, token = FRB.Token('INT', '8', 8, 62)),
                        73: FRB.ParseNode(73, prodId = 'int'),
                        74: FRB.ParseNode(74, prodId = 'nterm reduce'),
                        75: FRB.ParseNode(75, prodId = 'multexpr reduce'),
                        76: FRB.ParseNode(76, prodId = 'addexpr reduce'),
                        77: FRB.ParseNode(77, prodId = 'keyexpr reduce'),
                        78: FRB.ParseNode(78, prodId = 'gt'),
                        79: FRB.ParseNode(79, prodId = 'pred reduce'),
                        80: FRB.ParseNode(80, prodId = 'pred arg list'),
                        81: FRB.ParseNode(81, token = FRB.Token('RPAREN', ')', 8, 63)),
                        82: FRB.ParseNode(82, prodId = 'or func'),
                        83: FRB.ParseNode(83, prodId = 'pred arg list'),
                        84: FRB.ParseNode(84, token = FRB.Token('RPAREN', ')', 8, 64)),
                        85: FRB.ParseNode(85, prodId = 'and func'),
                        86: FRB.ParseNode(86, token = FRB.Token('RPAREN', ')', 8, 65)),
                        87: FRB.ParseNode(87, prodId = 'eq func'),
                        88: FRB.ParseNode(88, prodId = 'pred reduce'),
                        89: FRB.ParseNode(89, token = FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                        90: FRB.ParseNode(90, prodId = 'start'),
                     }, {5: [4], 6: [5], 7: [6], 8: [7], 9: [8], 10: [9], 11: [10], 16: [15], 17: [16], 18: [17], 19: [18], 20: [19], 21: [20], 22: [21], 23: [22], 
                         26: [25], 27: [26], 28: [27], 29: [23, 24, 28], 34: [33], 35: [34], 36: [35], 37: [36], 38: [37], 39: [38], 40: [39], 43: [42], 44: [43], 
                         45: [44], 47: [31, 32, 40, 41, 45, 46], 48: [47], 49: [29, 30, 48], 54: [53], 55: [54], 56: [55], 57: [56], 60: [59], 61: [60], 62: [61], 
                         63: [57, 58, 62], 66: [65], 67: [66], 68: [67], 69: [68], 70: [69], 73: [72], 74: [73], 75: [74], 76: [75], 77: [76], 78: [70, 71, 77], 
                         79: [78], 80: [63, 64, 79], 82: [51, 52, 80, 81], 83: [49, 50, 82], 85: [13, 14, 83, 84], 87: [2, 3, 11, 12, 85, 86], 88: [87], 90: [1, 88, 89]},
                     90)],

                     ['($\\swapvar$ < 7)', 
                      FRB.ParseTree({
                        1: FRB.ParseNode(1, token = FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                        2: FRB.ParseNode(2, token = FRB.Token('LPAREN', '(', 8, 1)),
                        3: FRB.ParseNode(3, token = FRB.Token('ID', '$\swapvar$', 8, 2)),
                        4: FRB.ParseNode(4, prodId = 'variable'),
                        5: FRB.ParseNode(5, prodId = 'nterm reduce'),
                        6: FRB.ParseNode(6, prodId = 'multexpr reduce'),
                        7: FRB.ParseNode(7, prodId = 'addexpr reduce'),
                        8: FRB.ParseNode(8, prodId = 'keyexpr reduce'),
                        9: FRB.ParseNode(9, token = FRB.Token('LT', '<', 8, 13)),
                        10: FRB.ParseNode(10, token = FRB.Token('INT', '7', 8, 15)),
                        11: FRB.ParseNode(11, prodId = 'int'),
                        12: FRB.ParseNode(12, prodId = 'nterm reduce'),
                        13: FRB.ParseNode(13, prodId = 'multexpr reduce'),
                        14: FRB.ParseNode(14, prodId = 'addexpr reduce'),
                        15: FRB.ParseNode(15, prodId = 'keyexpr reduce'),
                        16: FRB.ParseNode(16, prodId = 'lt'),
                        17: FRB.ParseNode(17, prodId = 'pred reduce'),
                        18: FRB.ParseNode(18, token = FRB.Token('RPAREN', ')', 8, 16)),
                        19: FRB.ParseNode(19, prodId = 'bracket loop'),
                        20: FRB.ParseNode(20, prodId = 'nterm reduce'),
                        21: FRB.ParseNode(21, prodId = 'multexpr reduce'),
                        22: FRB.ParseNode(22, prodId = 'addexpr reduce'),
                        23: FRB.ParseNode(23, prodId = 'keyexpr reduce'),
                        24: FRB.ParseNode(24, prodId = 'test reduce'),
                        25: FRB.ParseNode(25, prodId = 'pred reduce'),
                        26: FRB.ParseNode(26, token = FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                        27: FRB.ParseNode(27, prodId = 'start'),
                      }, {4: [3], 5: [4], 6: [5], 7: [6], 8: [7], 11: [10], 12: [11], 13: [12], 14: [13], 15: [14], 16: [8, 9, 15], 17: [16], 19: [2, 17, 18], 20: [19], 21: [20], 22: [21], 23: [22], 24: [23], 25: [24], 27: [1, 25, 26]},
                      27)],

                      ['Lt($\\swapvar$ , 7)',
                       FRB.ParseTree({
                        1: FRB.ParseNode(1, token = FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                        2: FRB.ParseNode(2, token = FRB.Token('LTFUNC', 'Lt', 8, 1)),
                        3: FRB.ParseNode(3, token = FRB.Token('LPAREN', '(', 8, 3)),
                        4: FRB.ParseNode(4, token = FRB.Token('ID', '$\swapvar$', 8, 4)),
                        5: FRB.ParseNode(5, prodId = 'variable'),
                        6: FRB.ParseNode(6, prodId = 'nterm reduce'),
                        7: FRB.ParseNode(7, prodId = 'multexpr reduce'),
                        8: FRB.ParseNode(8, prodId = 'addexpr reduce'),
                        9: FRB.ParseNode(9, prodId = 'keyexpr reduce'),
                        10: FRB.ParseNode(10, prodId = 'test reduce'),
                        11: FRB.ParseNode(11, prodId = 'pred reduce'),
                        12: FRB.ParseNode(12, token = FRB.Token('COMMA', ',', 8, 15)),
                        13: FRB.ParseNode(13, token = FRB.Token('INT', '7', 8, 17)),
                        14: FRB.ParseNode(14, prodId = 'int'),
                        15: FRB.ParseNode(15, prodId = 'nterm reduce'),
                        16: FRB.ParseNode(16, prodId = 'multexpr reduce'),
                        17: FRB.ParseNode(17, prodId = 'addexpr reduce'),
                        18: FRB.ParseNode(18, prodId = 'keyexpr reduce'),
                        19: FRB.ParseNode(19, prodId = 'test reduce'),
                        20: FRB.ParseNode(20, prodId = 'pred reduce'),
                        21: FRB.ParseNode(21, token = FRB.Token('RPAREN', ')', 8, 18)),
                        22: FRB.ParseNode(22, prodId = 'lt func'),
                        23: FRB.ParseNode(23, prodId = 'pred reduce'),
                        24: FRB.ParseNode(24, token = FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                        25: FRB.ParseNode(25, prodId = 'start'),
                      }, {5: [4], 6: [5], 7: [6], 8: [7], 9: [8], 10: [9], 11: [10], 14: [13], 15: [14], 16: [15], 17: [16], 18: [17], 19: [18], 20: [19], 22: [2, 3, 11, 12, 20, 21], 23: [22], 25: [1, 23, 24]},
                      25)],

                      ['(($x$ >= 5 & $\\swapvar$ < (7 + 3.456 * -0.0)) | ~($z[]%d$ >= 1 & $z[]%d$ < -9 & $123$ == True)) \t & $\\~$ + -234 -        -0 / -9.6',
                       FRB.ParseTree({
                        1: FRB.ParseNode(1, token = FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                        2: FRB.ParseNode(2, token = FRB.Token('LPAREN', '(', 8, 1)),
                        3: FRB.ParseNode(3, token = FRB.Token('LPAREN', '(', 8, 2)),
                        4: FRB.ParseNode(4, token = FRB.Token('ID', '$x$', 8, 3)),
                        5: FRB.ParseNode(5, prodId = 'variable'),
                        6: FRB.ParseNode(6, prodId = 'nterm reduce'),
                        7: FRB.ParseNode(7, prodId = 'multexpr reduce'),
                        8: FRB.ParseNode(8, prodId = 'addexpr reduce'),
                        9: FRB.ParseNode(9, prodId = 'keyexpr reduce'),
                        10: FRB.ParseNode(10, token = FRB.Token('GE', '>=', 8, 7)),
                        11: FRB.ParseNode(11, token = FRB.Token('INT', '5', 8, 10)),
                        12: FRB.ParseNode(12, prodId = 'int'),
                        13: FRB.ParseNode(13, prodId = 'nterm reduce'),
                        14: FRB.ParseNode(14, prodId = 'multexpr reduce'),
                        15: FRB.ParseNode(15, prodId = 'addexpr reduce'),
                        16: FRB.ParseNode(16, prodId = 'keyexpr reduce'),
                        17: FRB.ParseNode(17, prodId = 'ge'),
                        18: FRB.ParseNode(18, prodId = 'pred reduce'),
                        19: FRB.ParseNode(19, token = FRB.Token('AND', '&', 8, 12)),
                        20: FRB.ParseNode(20, token = FRB.Token('ID', '$\swapvar$', 8, 14)),
                        21: FRB.ParseNode(21, prodId = 'variable'),
                        22: FRB.ParseNode(22, prodId = 'nterm reduce'),
                        23: FRB.ParseNode(23, prodId = 'multexpr reduce'),
                        24: FRB.ParseNode(24, prodId = 'addexpr reduce'),
                        25: FRB.ParseNode(25, prodId = 'keyexpr reduce'),
                        26: FRB.ParseNode(26, token = FRB.Token('LT', '<', 8, 25)),
                        27: FRB.ParseNode(27, token = FRB.Token('LPAREN', '(', 8, 27)),
                        28: FRB.ParseNode(28, token = FRB.Token('INT', '7', 8, 28)),
                        29: FRB.ParseNode(29, prodId = 'int'),
                        30: FRB.ParseNode(30, prodId = 'nterm reduce'),
                        31: FRB.ParseNode(31, prodId = 'multexpr reduce'),
                        32: FRB.ParseNode(32, prodId = 'addexpr reduce'),
                        33: FRB.ParseNode(33, token = FRB.Token('PLUS', '+', 8, 30)),
                        34: FRB.ParseNode(34, token = FRB.Token('FLOAT', '3.456', 8, 32)),
                        35: FRB.ParseNode(35, prodId = 'float'),
                        36: FRB.ParseNode(36, prodId = 'nterm reduce'),
                        37: FRB.ParseNode(37, prodId = 'multexpr reduce'),
                        38: FRB.ParseNode(38, token = FRB.Token('STAR', '*', 8, 38)),
                        39: FRB.ParseNode(39, token = FRB.Token('FLOAT', '-0.0', 8, 40)),
                        40: FRB.ParseNode(40, prodId = 'float'),
                        41: FRB.ParseNode(41, prodId = 'nterm reduce'),
                        42: FRB.ParseNode(42, prodId = 'multiply'),
                        43: FRB.ParseNode(43, prodId = 'add'),
                        44: FRB.ParseNode(44, prodId = 'keyexpr reduce'),
                        45: FRB.ParseNode(45, prodId = 'test reduce'),
                        46: FRB.ParseNode(46, prodId = 'pred reduce'),
                        47: FRB.ParseNode(47, token = FRB.Token('RPAREN', ')', 8, 44)),
                        48: FRB.ParseNode(48, prodId = 'bracket loop'),
                        49: FRB.ParseNode(49, prodId = 'nterm reduce'),
                        50: FRB.ParseNode(50, prodId = 'multexpr reduce'),
                        51: FRB.ParseNode(51, prodId = 'addexpr reduce'),
                        52: FRB.ParseNode(52, prodId = 'keyexpr reduce'),
                        53: FRB.ParseNode(53, prodId = 'lt'),
                        54: FRB.ParseNode(54, prodId = 'and'),
                        55: FRB.ParseNode(55, token = FRB.Token('RPAREN', ')', 8, 45)),
                        56: FRB.ParseNode(56, prodId = 'bracket loop'),
                        57: FRB.ParseNode(57, prodId = 'nterm reduce'),
                        58: FRB.ParseNode(58, prodId = 'multexpr reduce'),
                        59: FRB.ParseNode(59, prodId = 'addexpr reduce'),
                        60: FRB.ParseNode(60, prodId = 'keyexpr reduce'),
                        61: FRB.ParseNode(61, prodId = 'test reduce'),
                        62: FRB.ParseNode(62, prodId = 'pred reduce'),
                        63: FRB.ParseNode(63, token = FRB.Token('OR', '|', 8, 47)),
                        64: FRB.ParseNode(64, token = FRB.Token('NOT', '~', 8, 49)),
                        65: FRB.ParseNode(65, token = FRB.Token('LPAREN', '(', 8, 50)),
                        66: FRB.ParseNode(66, token = FRB.Token('ID', '$z[]%d$', 8, 51)),
                        67: FRB.ParseNode(67, prodId = 'variable'),
                        68: FRB.ParseNode(68, prodId = 'nterm reduce'),
                        69: FRB.ParseNode(69, prodId = 'multexpr reduce'),
                        70: FRB.ParseNode(70, prodId = 'addexpr reduce'),
                        71: FRB.ParseNode(71, prodId = 'keyexpr reduce'),
                        72: FRB.ParseNode(72, token = FRB.Token('GE', '>=', 8, 59)),
                        73: FRB.ParseNode(73, token = FRB.Token('INT', '1', 8, 62)),
                        74: FRB.ParseNode(74, prodId = 'int'),
                        75: FRB.ParseNode(75, prodId = 'nterm reduce'),
                        76: FRB.ParseNode(76, prodId = 'multexpr reduce'),
                        77: FRB.ParseNode(77, prodId = 'addexpr reduce'),
                        78: FRB.ParseNode(78, prodId = 'keyexpr reduce'),
                        79: FRB.ParseNode(79, prodId = 'ge'),
                        80: FRB.ParseNode(80, prodId = 'pred reduce'),
                        81: FRB.ParseNode(81, token = FRB.Token('AND', '&', 8, 64)),
                        82: FRB.ParseNode(82, token = FRB.Token('ID', '$z[]%d$', 8, 66)),
                        83: FRB.ParseNode(83, prodId = 'variable'),
                        84: FRB.ParseNode(84, prodId = 'nterm reduce'),
                        85: FRB.ParseNode(85, prodId = 'multexpr reduce'),
                        86: FRB.ParseNode(86, prodId = 'addexpr reduce'),
                        87: FRB.ParseNode(87, prodId = 'keyexpr reduce'),
                        88: FRB.ParseNode(88, token = FRB.Token('LT', '<', 8, 74)),
                        89: FRB.ParseNode(89, token = FRB.Token('INT', '-9', 8, 76)),
                        90: FRB.ParseNode(90, prodId = 'int'),
                        91: FRB.ParseNode(91, prodId = 'nterm reduce'),
                        92: FRB.ParseNode(92, prodId = 'multexpr reduce'),
                        93: FRB.ParseNode(93, prodId = 'addexpr reduce'),
                        94: FRB.ParseNode(94, prodId = 'keyexpr reduce'),
                        95: FRB.ParseNode(95, prodId = 'lt'),
                        96: FRB.ParseNode(96, prodId = 'and'),
                        97: FRB.ParseNode(97, token = FRB.Token('AND', '&', 8, 79)),
                        98: FRB.ParseNode(98, token = FRB.Token('ID', '$123$', 8, 81)),
                        99: FRB.ParseNode(99, prodId = 'variable'),
                        100: FRB.ParseNode(100, prodId = 'nterm reduce'),
                        101: FRB.ParseNode(101, prodId = 'multexpr reduce'),
                        102: FRB.ParseNode(102, prodId = 'addexpr reduce'),
                        103: FRB.ParseNode(103, prodId = 'keyexpr reduce'),
                        104: FRB.ParseNode(104, token = FRB.Token('EQ', '==', 8, 87)),
                        105: FRB.ParseNode(105, token = FRB.Token('TRUE', 'True', 8, 90)),
                        106: FRB.ParseNode(106, prodId = 'true'),
                        107: FRB.ParseNode(107, prodId = 'eq'),
                        108: FRB.ParseNode(108, prodId = 'and'),
                        109: FRB.ParseNode(109, token = FRB.Token('RPAREN', ')', 8, 94)),
                        110: FRB.ParseNode(110, prodId = 'bracket loop'),
                        111: FRB.ParseNode(111, prodId = 'nterm reduce'),
                        112: FRB.ParseNode(112, prodId = 'not'),
                        113: FRB.ParseNode(113, prodId = 'multexpr reduce'),
                        114: FRB.ParseNode(114, prodId = 'addexpr reduce'),
                        115: FRB.ParseNode(115, prodId = 'keyexpr reduce'),
                        116: FRB.ParseNode(116, prodId = 'test reduce'),
                        117: FRB.ParseNode(117, prodId = 'or'),
                        118: FRB.ParseNode(118, token = FRB.Token('RPAREN', ')', 8, 95)),
                        119: FRB.ParseNode(119, prodId = 'bracket loop'),
                        120: FRB.ParseNode(120, prodId = 'nterm reduce'),
                        121: FRB.ParseNode(121, prodId = 'multexpr reduce'),
                        122: FRB.ParseNode(122, prodId = 'addexpr reduce'),
                        123: FRB.ParseNode(123, prodId = 'keyexpr reduce'),
                        124: FRB.ParseNode(124, prodId = 'test reduce'),
                        125: FRB.ParseNode(125, prodId = 'pred reduce'),
                        126: FRB.ParseNode(126, token = FRB.Token('AND', '&', 8, 99)),
                        127: FRB.ParseNode(127, token = FRB.Token('ID', '$\~$', 8, 101)),
                        128: FRB.ParseNode(128, prodId = 'variable'),
                        129: FRB.ParseNode(129, prodId = 'nterm reduce'),
                        130: FRB.ParseNode(130, prodId = 'multexpr reduce'),
                        131: FRB.ParseNode(131, prodId = 'addexpr reduce'),
                        132: FRB.ParseNode(132, token = FRB.Token('PLUS', '+', 8, 106)),
                        133: FRB.ParseNode(133, token = FRB.Token('INT', '-234', 8, 108)),
                        134: FRB.ParseNode(134, prodId = 'int'),
                        135: FRB.ParseNode(135, prodId = 'nterm reduce'),
                        136: FRB.ParseNode(136, prodId = 'multexpr reduce'),
                        137: FRB.ParseNode(137, prodId = 'add'),
                        138: FRB.ParseNode(138, token = FRB.Token('MINUS', '-', 8, 113)),
                        139: FRB.ParseNode(139, token = FRB.Token('INT', '-0', 8, 122)),
                        140: FRB.ParseNode(140, prodId = 'int'),
                        141: FRB.ParseNode(141, prodId = 'nterm reduce'),
                        142: FRB.ParseNode(142, prodId = 'multexpr reduce'),
                        143: FRB.ParseNode(143, token = FRB.Token('SLASH', '/', 8, 125)),
                        144: FRB.ParseNode(144, token = FRB.Token('FLOAT', '-9.6', 8, 127)),
                        145: FRB.ParseNode(145, prodId = 'float'),
                        146: FRB.ParseNode(146, prodId = 'nterm reduce'),
                        147: FRB.ParseNode(147, prodId = 'divide'),
                        148: FRB.ParseNode(148, prodId = 'subtract'),
                        149: FRB.ParseNode(149, prodId = 'keyexpr reduce'),
                        150: FRB.ParseNode(150, prodId = 'test reduce'),
                        151: FRB.ParseNode(151, prodId = 'and'),
                        152: FRB.ParseNode(152, token = FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                        153: FRB.ParseNode(153, prodId = 'start'),
                       }, {5: [4], 6: [5], 7: [6], 8: [7], 9: [8], 12: [11], 13: [12], 14: [13], 15: [14], 16: [15], 17: [9, 10, 16], 18: [17], 21: [20], 22: [21], 23: [22], 24: [23], 25: [24], 29: [28], 30: [29], 31: [30], 
                           32: [31], 35: [34], 36: [35], 37: [36], 40: [39], 41: [40], 42: [37, 38, 41], 43: [32, 33, 42], 44: [43], 45: [44], 46: [45], 48: [27, 46, 47], 49: [48], 50: [49], 51: [50], 52: [51], 53: [25, 26, 52], 
                           54: [18, 19, 53], 56: [3, 54, 55], 57: [56], 58: [57], 59: [58], 60: [59], 61: [60], 62: [61], 67: [66], 68: [67], 69: [68], 70: [69], 71: [70], 74: [73], 75: [74], 76: [75], 77: [76], 78: [77], 79: [71, 72, 78], 
                           80: [79], 83: [82], 84: [83], 85: [84], 86: [85], 87: [86], 90: [89], 91: [90], 92: [91], 93: [92], 94: [93], 95: [87, 88, 94], 96: [80, 81, 95], 99: [98], 100: [99], 101: [100], 102: [101], 103: [102], 106: [105], 
                           107: [103, 104, 106], 108: [96, 97, 107], 110: [65, 108, 109], 111: [110], 112: [64, 111], 113: [112], 114: [113], 115: [114], 116: [115], 117: [62, 63, 116], 119: [2, 117, 118], 120: [119], 121: [120], 122: [121], 
                           123: [122], 124: [123], 125: [124], 128: [127], 129: [128], 130: [129], 131: [130], 134: [133], 135: [134], 136: [135], 137: [131, 132, 136], 140: [139], 141: [140], 142: [141], 145: [144], 146: [145], 147: [142, 143, 146], 
                           148: [137, 138, 147], 149: [148], 150: [149], 151: [125, 126, 150], 153: [1, 151, 152]},
                           153)],

                    ['(($x$ >= 5 & $\\swapvar$ < (7 + 3.456 * -0.0)) | ~($z[]%d$ >= 1 & $z[]%d$ < -9 & $123$ == True)) \t & $\\~$ + -234 -        -0 / -9.6)', 
                     FRB.Token("RPAREN", ")", 8, 131)],

                    ['~(($y$ | Ne($x$, $y$)) & (($x$ >= $y$) | ($x$ <= $y$)) & Eq($x$, $y$*$z$ - $y$ + $z$/3))',
                     FRB.ParseTree({
                        1: FRB.ParseNode(1, token = FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                        2: FRB.ParseNode(2, token = FRB.Token('NOT', '~', 8, 1)),
                        3: FRB.ParseNode(3, token = FRB.Token('LPAREN', '(', 8, 2)),
                        4: FRB.ParseNode(4, token = FRB.Token('LPAREN', '(', 8, 3)),
                        5: FRB.ParseNode(5, token = FRB.Token('ID', '$y$', 8, 4)),
                        6: FRB.ParseNode(6, prodId = 'variable'),
                        7: FRB.ParseNode(7, prodId = 'nterm reduce'),
                        8: FRB.ParseNode(8, prodId = 'multexpr reduce'),
                        9: FRB.ParseNode(9, prodId = 'addexpr reduce'),
                        10: FRB.ParseNode(10, prodId = 'keyexpr reduce'),
                        11: FRB.ParseNode(11, prodId = 'test reduce'),
                        12: FRB.ParseNode(12, prodId = 'pred reduce'),
                        13: FRB.ParseNode(13, token = FRB.Token('OR', '|', 8, 8)),
                        14: FRB.ParseNode(14, token = FRB.Token('NEFUNC', 'Ne', 8, 10)),
                        15: FRB.ParseNode(15, token = FRB.Token('LPAREN', '(', 8, 12)),
                        16: FRB.ParseNode(16, token = FRB.Token('ID', '$x$', 8, 13)),
                        17: FRB.ParseNode(17, prodId = 'variable'),
                        18: FRB.ParseNode(18, prodId = 'nterm reduce'),
                        19: FRB.ParseNode(19, prodId = 'multexpr reduce'),
                        20: FRB.ParseNode(20, prodId = 'addexpr reduce'),
                        21: FRB.ParseNode(21, prodId = 'keyexpr reduce'),
                        22: FRB.ParseNode(22, prodId = 'test reduce'),
                        23: FRB.ParseNode(23, prodId = 'pred reduce'),
                        24: FRB.ParseNode(24, token = FRB.Token('COMMA', ',', 8, 16)),
                        25: FRB.ParseNode(25, token = FRB.Token('ID', '$y$', 8, 18)),
                        26: FRB.ParseNode(26, prodId = 'variable'),
                        27: FRB.ParseNode(27, prodId = 'nterm reduce'),
                        28: FRB.ParseNode(28, prodId = 'multexpr reduce'),
                        29: FRB.ParseNode(29, prodId = 'addexpr reduce'),
                        30: FRB.ParseNode(30, prodId = 'keyexpr reduce'),
                        31: FRB.ParseNode(31, prodId = 'test reduce'),
                        32: FRB.ParseNode(32, prodId = 'pred reduce'),
                        33: FRB.ParseNode(33, token = FRB.Token('RPAREN', ')', 8, 21)),
                        34: FRB.ParseNode(34, prodId = 'ne func'),
                        35: FRB.ParseNode(35, prodId = 'or'),
                        36: FRB.ParseNode(36, token = FRB.Token('RPAREN', ')', 8, 22)),
                        37: FRB.ParseNode(37, prodId = 'bracket loop'),
                        38: FRB.ParseNode(38, prodId = 'nterm reduce'),
                        39: FRB.ParseNode(39, prodId = 'multexpr reduce'),
                        40: FRB.ParseNode(40, prodId = 'addexpr reduce'),
                        41: FRB.ParseNode(41, prodId = 'keyexpr reduce'),
                        42: FRB.ParseNode(42, prodId = 'test reduce'),
                        43: FRB.ParseNode(43, prodId = 'pred reduce'),
                        44: FRB.ParseNode(44, token = FRB.Token('AND', '&', 8, 24)),
                        45: FRB.ParseNode(45, token = FRB.Token('LPAREN', '(', 8, 26)),
                        46: FRB.ParseNode(46, token = FRB.Token('LPAREN', '(', 8, 27)),
                        47: FRB.ParseNode(47, token = FRB.Token('ID', '$x$', 8, 28)),
                        48: FRB.ParseNode(48, prodId = 'variable'),
                        49: FRB.ParseNode(49, prodId = 'nterm reduce'),
                        50: FRB.ParseNode(50, prodId = 'multexpr reduce'),
                        51: FRB.ParseNode(51, prodId = 'addexpr reduce'),
                        52: FRB.ParseNode(52, prodId = 'keyexpr reduce'),
                        53: FRB.ParseNode(53, token = FRB.Token('GE', '>=', 8, 32)),
                        54: FRB.ParseNode(54, token = FRB.Token('ID', '$y$', 8, 35)),
                        55: FRB.ParseNode(55, prodId = 'variable'),
                        56: FRB.ParseNode(56, prodId = 'nterm reduce'),
                        57: FRB.ParseNode(57, prodId = 'multexpr reduce'),
                        58: FRB.ParseNode(58, prodId = 'addexpr reduce'),
                        59: FRB.ParseNode(59, prodId = 'keyexpr reduce'),
                        60: FRB.ParseNode(60, prodId = 'ge'),
                        61: FRB.ParseNode(61, prodId = 'pred reduce'),
                        62: FRB.ParseNode(62, token = FRB.Token('RPAREN', ')', 8, 38)),
                        63: FRB.ParseNode(63, prodId = 'bracket loop'),
                        64: FRB.ParseNode(64, prodId = 'nterm reduce'),
                        65: FRB.ParseNode(65, prodId = 'multexpr reduce'),
                        66: FRB.ParseNode(66, prodId = 'addexpr reduce'),
                        67: FRB.ParseNode(67, prodId = 'keyexpr reduce'),
                        68: FRB.ParseNode(68, prodId = 'test reduce'),
                        69: FRB.ParseNode(69, prodId = 'pred reduce'),
                        70: FRB.ParseNode(70, token = FRB.Token('OR', '|', 8, 40)),
                        71: FRB.ParseNode(71, token = FRB.Token('LPAREN', '(', 8, 42)),
                        72: FRB.ParseNode(72, token = FRB.Token('ID', '$x$', 8, 43)),
                        73: FRB.ParseNode(73, prodId = 'variable'),
                        74: FRB.ParseNode(74, prodId = 'nterm reduce'),
                        75: FRB.ParseNode(75, prodId = 'multexpr reduce'),
                        76: FRB.ParseNode(76, prodId = 'addexpr reduce'),
                        77: FRB.ParseNode(77, prodId = 'keyexpr reduce'),
                        78: FRB.ParseNode(78, token = FRB.Token('LE', '<=', 8, 47)),
                        79: FRB.ParseNode(79, token = FRB.Token('ID', '$y$', 8, 50)),
                        80: FRB.ParseNode(80, prodId = 'variable'),
                        81: FRB.ParseNode(81, prodId = 'nterm reduce'),
                        82: FRB.ParseNode(82, prodId = 'multexpr reduce'),
                        83: FRB.ParseNode(83, prodId = 'addexpr reduce'),
                        84: FRB.ParseNode(84, prodId = 'keyexpr reduce'),
                        85: FRB.ParseNode(85, prodId = 'le'),
                        86: FRB.ParseNode(86, prodId = 'pred reduce'),
                        87: FRB.ParseNode(87, token = FRB.Token('RPAREN', ')', 8, 53)),
                        88: FRB.ParseNode(88, prodId = 'bracket loop'),
                        89: FRB.ParseNode(89, prodId = 'nterm reduce'),
                        90: FRB.ParseNode(90, prodId = 'multexpr reduce'),
                        91: FRB.ParseNode(91, prodId = 'addexpr reduce'),
                        92: FRB.ParseNode(92, prodId = 'keyexpr reduce'),
                        93: FRB.ParseNode(93, prodId = 'test reduce'),
                        94: FRB.ParseNode(94, prodId = 'or'),
                        95: FRB.ParseNode(95, token = FRB.Token('RPAREN', ')', 8, 54)),
                        96: FRB.ParseNode(96, prodId = 'bracket loop'),
                        97: FRB.ParseNode(97, prodId = 'nterm reduce'),
                        98: FRB.ParseNode(98, prodId = 'multexpr reduce'),
                        99: FRB.ParseNode(99, prodId = 'addexpr reduce'),
                        100: FRB.ParseNode(100, prodId = 'keyexpr reduce'),
                        101: FRB.ParseNode(101, prodId = 'test reduce'),
                        102: FRB.ParseNode(102, prodId = 'and'),
                        103: FRB.ParseNode(103, token = FRB.Token('AND', '&', 8, 56)),
                        104: FRB.ParseNode(104, token = FRB.Token('EQFUNC', 'Eq', 8, 58)),
                        105: FRB.ParseNode(105, token = FRB.Token('LPAREN', '(', 8, 60)),
                        106: FRB.ParseNode(106, token = FRB.Token('ID', '$x$', 8, 61)),
                        107: FRB.ParseNode(107, prodId = 'variable'),
                        108: FRB.ParseNode(108, prodId = 'nterm reduce'),
                        109: FRB.ParseNode(109, prodId = 'multexpr reduce'),
                        110: FRB.ParseNode(110, prodId = 'addexpr reduce'),
                        111: FRB.ParseNode(111, prodId = 'keyexpr reduce'),
                        112: FRB.ParseNode(112, prodId = 'test reduce'),
                        113: FRB.ParseNode(113, prodId = 'pred reduce'),
                        114: FRB.ParseNode(114, token = FRB.Token('COMMA', ',', 8, 64)),
                        115: FRB.ParseNode(115, token = FRB.Token('ID', '$y$', 8, 66)),
                        116: FRB.ParseNode(116, prodId = 'variable'),
                        117: FRB.ParseNode(117, prodId = 'nterm reduce'),
                        118: FRB.ParseNode(118, prodId = 'multexpr reduce'),
                        119: FRB.ParseNode(119, token = FRB.Token('STAR', '*', 8, 69)),
                        120: FRB.ParseNode(120, token = FRB.Token('ID', '$z$', 8, 70)),
                        121: FRB.ParseNode(121, prodId = 'variable'),
                        122: FRB.ParseNode(122, prodId = 'nterm reduce'),
                        123: FRB.ParseNode(123, prodId = 'multiply'),
                        124: FRB.ParseNode(124, prodId = 'addexpr reduce'),
                        125: FRB.ParseNode(125, token = FRB.Token('MINUS', '-', 8, 74)),
                        126: FRB.ParseNode(126, token = FRB.Token('ID', '$y$', 8, 76)),
                        127: FRB.ParseNode(127, prodId = 'variable'),
                        128: FRB.ParseNode(128, prodId = 'nterm reduce'),
                        129: FRB.ParseNode(129, prodId = 'multexpr reduce'),
                        130: FRB.ParseNode(130, prodId = 'subtract'),
                        131: FRB.ParseNode(131, token = FRB.Token('PLUS', '+', 8, 80)),
                        132: FRB.ParseNode(132, token = FRB.Token('ID', '$z$', 8, 82)),
                        133: FRB.ParseNode(133, prodId = 'variable'),
                        134: FRB.ParseNode(134, prodId = 'nterm reduce'),
                        135: FRB.ParseNode(135, prodId = 'multexpr reduce'),
                        136: FRB.ParseNode(136, token = FRB.Token('SLASH', '/', 8, 85)),
                        137: FRB.ParseNode(137, token = FRB.Token('INT', '3', 8, 86)),
                        138: FRB.ParseNode(138, prodId = 'int'),
                        139: FRB.ParseNode(139, prodId = 'nterm reduce'),
                        140: FRB.ParseNode(140, prodId = 'divide'),
                        141: FRB.ParseNode(141, prodId = 'add'),
                        142: FRB.ParseNode(142, prodId = 'keyexpr reduce'),
                        143: FRB.ParseNode(143, prodId = 'test reduce'),
                        144: FRB.ParseNode(144, prodId = 'pred reduce'),
                        145: FRB.ParseNode(145, token = FRB.Token('RPAREN', ')', 8, 87)),
                        146: FRB.ParseNode(146, prodId = 'eq func'),
                        147: FRB.ParseNode(147, prodId = 'and'),
                        148: FRB.ParseNode(148, token = FRB.Token('RPAREN', ')', 8, 88)),
                        149: FRB.ParseNode(149, prodId = 'bracket loop'),
                        150: FRB.ParseNode(150, prodId = 'nterm reduce'),
                        151: FRB.ParseNode(151, prodId = 'not'),
                        152: FRB.ParseNode(152, prodId = 'multexpr reduce'),
                        153: FRB.ParseNode(153, prodId = 'addexpr reduce'),
                        154: FRB.ParseNode(154, prodId = 'keyexpr reduce'),
                        155: FRB.ParseNode(155, prodId = 'test reduce'),
                        156: FRB.ParseNode(156, prodId = 'pred reduce'),
                        157: FRB.ParseNode(157, token = FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                        158: FRB.ParseNode(158, prodId = 'start'),
                      }, 
                      {6: [5], 7: [6], 8: [7], 9: [8], 10: [9], 11: [10], 12: [11], 17: [16], 18: [17], 19: [18], 20: [19], 21: [20], 22: [21], 23: [22], 26: [25], 27: [26], 28: [27], 29: [28], 30: [29], 31: [30], 32: [31], 
                       34: [14, 15, 23, 24, 32, 33], 35: [12, 13, 34], 37: [4, 35, 36], 38: [37], 39: [38], 40: [39], 41: [40], 42: [41], 43: [42], 48: [47], 49: [48], 50: [49], 51: [50], 52: [51], 55: [54], 56: [55], 57: [56], 
                       58: [57], 59: [58], 60: [52, 53, 59], 61: [60], 63: [46, 61, 62], 64: [63], 65: [64], 66: [65], 67: [66], 68: [67], 69: [68], 73: [72], 74: [73], 75: [74], 76: [75], 77: [76], 80: [79], 81: [80], 82: [81], 
                       83: [82], 84: [83], 85: [77, 78, 84], 86: [85], 88: [71, 86, 87], 89: [88], 90: [89], 91: [90], 92: [91], 93: [92], 94: [69, 70, 93], 96: [45, 94, 95], 97: [96], 98: [97], 99: [98], 100: [99], 101: [100], 
                       102: [43, 44, 101], 107: [106], 108: [107], 109: [108], 110: [109], 111: [110], 112: [111], 113: [112], 116: [115], 117: [116], 118: [117], 121: [120], 122: [121], 123: [118, 119, 122], 124: [123], 127: [126], 
                       128: [127], 129: [128], 130: [124, 125, 129], 133: [132], 134: [133], 135: [134], 138: [137], 139: [138], 140: [135, 136, 139], 141: [130, 131, 140], 142: [141], 143: [142], 144: [143], 146: [104, 105, 113, 114, 144, 145], 
                       147: [102, 103, 146], 149: [3, 147, 148], 150: [149], 151: [2, 150], 152: [151], 153: [152], 154: [153], 155: [154], 156: [155], 158: [1, 156, 157]},
                      158)],
                    ['~$a$ & ~8', 
                       FRB.ParseTree({
                        1: FRB.ParseNode(1, token = FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                        2: FRB.ParseNode(2, token = FRB.Token('NOT', '~', 8, 1)),
                        3: FRB.ParseNode(3, token = FRB.Token('ID', '$a$', 8, 2)),
                        4: FRB.ParseNode(4, prodId = 'variable'),
                        5: FRB.ParseNode(5, prodId = 'nterm reduce'),
                        6: FRB.ParseNode(6, prodId = 'not'),
                        7: FRB.ParseNode(7, prodId = 'multexpr reduce'),
                        8: FRB.ParseNode(8, prodId = 'addexpr reduce'),
                        9: FRB.ParseNode(9, prodId = 'keyexpr reduce'),
                        10: FRB.ParseNode(10, prodId = 'test reduce'),
                        11: FRB.ParseNode(11, prodId = 'pred reduce'),
                        12: FRB.ParseNode(12, token = FRB.Token('AND', '&', 8, 6)),
                        13: FRB.ParseNode(13, token = FRB.Token('NOT', '~', 8, 8)),
                        14: FRB.ParseNode(14, token = FRB.Token('INT', '8', 8, 9)),
                        15: FRB.ParseNode(15, prodId = 'int'),
                        16: FRB.ParseNode(16, prodId = 'nterm reduce'),
                        17: FRB.ParseNode(17, prodId = 'not'),
                        18: FRB.ParseNode(18, prodId = 'multexpr reduce'),
                        19: FRB.ParseNode(19, prodId = 'addexpr reduce'),
                        20: FRB.ParseNode(20, prodId = 'keyexpr reduce'),
                        21: FRB.ParseNode(21, prodId = 'test reduce'),
                        22: FRB.ParseNode(22, prodId = 'and'),
                        23: FRB.ParseNode(23, token = FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                        24: FRB.ParseNode(24, prodId = 'start'),
                        }, 
                        {4: [3], 5: [4], 6: [2, 5], 7: [6], 8: [7], 9: [8], 10: [9], 11: [10], 15: [14], 16: [15], 17: [13, 16], 18: [17], 19: [18], 20: [19], 21: [20], 22: [11, 12, 21], 24: [1, 22, 23]}, 
                        24)],
                    ['~~(~$a$ + 8 & $b$ > ~8)',
                     FRB.ParseTree({
                        1: FRB.ParseNode(1, token = FRB.Token('STARTTOKEN', 'STARTTOKEN', 8, 0)),
                        2: FRB.ParseNode(2, token = FRB.Token('NOT', '~', 8, 1)),
                        3: FRB.ParseNode(3, token = FRB.Token('NOT', '~', 8, 2)),
                        4: FRB.ParseNode(4, token = FRB.Token('LPAREN', '(', 8, 3)),
                        5: FRB.ParseNode(5, token = FRB.Token('NOT', '~', 8, 4)),
                        6: FRB.ParseNode(6, token = FRB.Token('ID', '$a$', 8, 5)),
                        7: FRB.ParseNode(7, prodId = 'variable'),
                        8: FRB.ParseNode(8, prodId = 'nterm reduce'),
                        9: FRB.ParseNode(9, prodId = 'not'),
                        10: FRB.ParseNode(10, prodId = 'multexpr reduce'),
                        11: FRB.ParseNode(11, prodId = 'addexpr reduce'),
                        12: FRB.ParseNode(12, token = FRB.Token('PLUS', '+', 8, 9)),
                        13: FRB.ParseNode(13, token = FRB.Token('INT', '8', 8, 11)),
                        14: FRB.ParseNode(14, prodId = 'int'),
                        15: FRB.ParseNode(15, prodId = 'nterm reduce'),
                        16: FRB.ParseNode(16, prodId = 'multexpr reduce'),
                        17: FRB.ParseNode(17, prodId = 'add'),
                        18: FRB.ParseNode(18, prodId = 'keyexpr reduce'),
                        19: FRB.ParseNode(19, prodId = 'test reduce'),
                        20: FRB.ParseNode(20, prodId = 'pred reduce'),
                        21: FRB.ParseNode(21, token = FRB.Token('AND', '&', 8, 13)),
                        22: FRB.ParseNode(22, token = FRB.Token('ID', '$b$', 8, 15)),
                        23: FRB.ParseNode(23, prodId = 'variable'),
                        24: FRB.ParseNode(24, prodId = 'nterm reduce'),
                        25: FRB.ParseNode(25, prodId = 'multexpr reduce'),
                        26: FRB.ParseNode(26, prodId = 'addexpr reduce'),
                        27: FRB.ParseNode(27, prodId = 'keyexpr reduce'),
                        28: FRB.ParseNode(28, token = FRB.Token('GT', '>', 8, 19)),
                        29: FRB.ParseNode(29, token = FRB.Token('NOT', '~', 8, 21)),
                        30: FRB.ParseNode(30, token = FRB.Token('INT', '8', 8, 22)),
                        31: FRB.ParseNode(31, prodId = 'int'),
                        32: FRB.ParseNode(32, prodId = 'nterm reduce'),
                        33: FRB.ParseNode(33, prodId = 'not'),
                        34: FRB.ParseNode(34, prodId = 'multexpr reduce'),
                        35: FRB.ParseNode(35, prodId = 'addexpr reduce'),
                        36: FRB.ParseNode(36, prodId = 'keyexpr reduce'),
                        37: FRB.ParseNode(37, prodId = 'gt'),
                        38: FRB.ParseNode(38, prodId = 'and'),
                        39: FRB.ParseNode(39, token = FRB.Token('RPAREN', ')', 8, 23)),
                        40: FRB.ParseNode(40, prodId = 'bracket loop'),
                        41: FRB.ParseNode(41, prodId = 'nterm reduce'),
                        42: FRB.ParseNode(42, prodId = 'not'),
                        43: FRB.ParseNode(43, prodId = 'not'),
                        44: FRB.ParseNode(44, prodId = 'multexpr reduce'),
                        45: FRB.ParseNode(45, prodId = 'addexpr reduce'),
                        46: FRB.ParseNode(46, prodId = 'keyexpr reduce'),
                        47: FRB.ParseNode(47, prodId = 'test reduce'),
                        48: FRB.ParseNode(48, prodId = 'pred reduce'),
                        49: FRB.ParseNode(49, token = FRB.Token('ENDTOKEN', 'ENDTOKEN', 9, 0)),
                        50: FRB.ParseNode(50, prodId = 'start'),
                        }, 
                        {7: [6], 8: [7], 9: [5, 8], 10: [9], 11: [10], 14: [13], 15: [14], 16: [15], 17: [11, 12, 16], 18: [17], 19: [18], 20: [19], 23: [22], 24: [23], 25: [24], 26: [25], 27: [26], 31: [30], 
                         32: [31], 33: [29, 32], 34: [33], 35: [34], 36: [35], 37: [27, 28, 36], 38: [20, 21, 37], 40: [4, 38, 39], 41: [40], 42: [3, 41], 43: [2, 42], 44: [43], 45: [44], 46: [45], 47: [46], 48: [47], 50: [1, 48, 49]}, 
                        50)]
                 ]  

        for test in tests:
            inputText = test[0]
            expected = test[1]

            ctx = FRB.ParseContext(inputText, file = file, startLineNo = startLineNo)
            tokens = self._tokenizer.simplifiedMaximalMunch(ctx)

            error = None
            result = None
            try:
                result = self._parser.parse(tokens, ctx = ctx)
            except FRB.SyntaxErr as e:
                error = e

            if (error is not None):
                expected = FRB.SyntaxErr(ctx, expected, process = "parsing")
                self.compareSyntaxErr(error, expected)
            else:
                self.compareParseTreeShape(result, expected)

    # ================================================