// ##### Credits

// ===== Anime Game Remap (AG Remap) =====
// Authors: Albert Gold#2696, NK#1321
//
// if you used it to remap your mods pls give credit for "Albert Gold#2696" and "Nhok0169"
// Special Thanks:
//   nguen#2011 (for support)
//   SilentNightSound#7430 (for internal knowdege so wrote the blendCorrection code)
//   HazrateGolabi#1364 (for being awesome, and improving the code)

// ##### EndCredits

#include "AGRemapCore/data/IniFixData/LynaePeppermint/LynaePeppermintSkeleton.h"


namespace AGRemapCore {
    // GENERATED from Data/Mod Downloads/WuWa/LynaePeppermint/3_7/LynaePeppermintMetadata.json (each
    // component's vg_map, in local-bone order)
    const std::map<int, std::vector<int>>& lynaePeppermintVgMaps() {
        static const std::map<int, std::vector<int>> table = {
            {0, {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42}},
            {1, {43, 44, 45, 46, 0, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98}},
            {2, {0}},
            {3, {100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 98, 0, 126, 127, 73, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 54, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 46, 48, 183, 184}},
            {4, {100, 106, 107, 144, 189, 145, 101, 103, 105, 102, 195, 108, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256}},
            {5, {213, 208, 212, 216, 214, 206, 205, 210, 209, 211, 231, 219, 218, 217, 220, 221, 222, 224, 207, 215}},
            {6, {174, 175, 111, 98, 127, 176, 177, 184, 183, 286, 236, 235, 241, 290, 291, 292, 293, 294, 244, 243, 249, 298, 299, 300, 301, 104, 122, 126, 101, 110, 109, 123, 309, 310, 100, 157, 146}},
            {7, {0}}
        };
        return table;
    }

    // Generated by Tools/Misc/Diagnostics/wwmiShapeKeyOrder.py LynaePeppermint Lynae: the inverse of
    // lynaeToPeppermintShapeKeys
    const std::vector<long long>& peppermintToLynaeShapeKeys() {
        static const std::vector<long long> table = {
            5, 1, 3, 2, 4, 0, 10, 14, 11, 16, 13, 9, 8, 17, 12, 26, 31, 30, 24, 29,
            27, 28, 7, 6, 23, 32, 46, 90, 44, 43, 36, 35, 40, 37, 41, 42, 34, 45, 39, 33,
            38, 51, 48, 57, 56, 22, 21, 18, 20, 19, 59, 58, 54, 47, 52, 49, 50, 55, 53, 25,
            15, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
            -1, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 91, 92, 93, 94, 95, 96, 97, 98, 99,
            100, 101, 102, 103, 104
        };
        return table;
    }
}
