pybind11_add_module(core
    src/bindings.cpp
    src/tools/PyAlgo.cpp
    src/tools/PyBiMap.cpp
    src/tools/PyGraphTools.cpp
    src/tools/PyIntTools.cpp
    src/tools/PyListTools.cpp
    src/tools/PyRanges.cpp
    src/tools/dfa/PyDFA.cpp
    src/tools/tries/PyTrie.cpp
    src/tools/tries/PyAhoCorasickDFA.cpp
    src/tools/orderedMultiMap/PyOrderedMultiMap.cpp
    src/tools/orderedMultiMap/PyOrderedMultiMapSqrt.cpp
    src/tools/orderedMultiMap/PyIOrderedMultiMap.cpp
    src/model/iftemplate/PyIfContentPart.cpp
    src/model/iftemplate/PyIfContentPartColour.cpp
    src/model/PyVersion.cpp
    src/model/assets/PyModDictAssets.cpp
    src/model/assets/PyModMappedAssets.cpp
    src/model/assets/PyModAssets.cpp
    src/model/assets/PyHashes.cpp
    src/model/assets/PyIndices.cpp
    src/model/strategies/PyModTypeIdData.cpp
    src/model/strategies/PyModType.cpp
    src/model/strategies/iniClassifiers/PyIniClassifyStats.cpp
    src/model/strategies/iniClassifiers/PyBaseIniClassifier.cpp
    src/model/strategies/iniClassifiers/PyIniClassifier.cpp
    src/constants/PyGameTypeId.cpp
    src/constants/PyModTypeId.cpp
    src/constants/PyGIBuilder.cpp
    src/tools/parsing/PyToken.cpp
    src/tools/parsing/PyParseContext.cpp
    src/tools/parsing/PyBaseTokenizer.cpp
    src/tools/parsing/PyFilteredTokenizer.cpp
    src/tools/parsing/PyIfPredTokenizer.cpp
    src/tools/parsing/PySympyTokenizer.cpp
    src/tools/nodes/PyParseNode.cpp
    src/tools/parsing/PyParseTree.cpp
    src/tools/parsing/PyBaseSLR1Parser.cpp
    src/model/iftemplate/PySympyParser.cpp
    src/model/iftemplate/PyIfPredParser.cpp
    src/tools/z3/PyZ3Context.cpp
    src/tools/z3/PyZ3Predicate.cpp
    src/model/iftemplate/PyIfPredPart.cpp
    src/model/iftemplate/PyIfTemplateNode.cpp
    src/model/iftemplate/PyIfTemplateTree.cpp
    src/model/iftemplate/PyIfTemplate.cpp
    src/model/PyCallGraph.cpp
    src/model/PySectionIterData.cpp
    src/model/PyIniSectionGraph.cpp
    src/model/PyIniGraphGroup.cpp
    src/model/strategies/iniFixers/regEdits/PyBaseRegEdit.cpp
    src/model/strategies/iniFixers/regEdits/PyRegAdd.cpp
    src/model/strategies/iniFixers/regEdits/PyRegNewVals.cpp
    src/model/strategies/iniFixers/regEdits/PyRegRemap.cpp
    src/model/strategies/iniFixers/regEdits/PyRegRemove.cpp
    src/model/strategies/iniFixers/graphEdits/PyBaseIniGraphEdit.cpp
    src/model/strategies/iniFixers/graphEdits/PyGraphRename.cpp
    src/model/strategies/iniFixers/graphEdits/PyRegFillMissing.cpp
    src/model/strategies/iniFixers/graphEdits/PyRegSurroundedAdd.cpp
    src/model/strategies/iniFixers/graphGroupEdits/PyIniGraphGroups.cpp
    src/model/strategies/iniFixers/graphGroupEdits/PyBaseIniGraphGroupEdit.cpp
    src/model/strategies/iniFixers/graphGroupEdits/PyGraphRemove.cpp
    src/model/strategies/iniFixers/graphGroupEdits/PyGraphInherit.cpp
    src/model/strategies/iniFixers/graphGroupEdits/PyGraphGroupRemap.cpp
    src/model/strategies/iniFixers/graphGroupEdits/PyGraphGroupEdit.cpp
    src/model/strategies/iniFixers/graphGroupEdits/resEdits/PyResEdit.cpp
    src/model/strategies/iniFixers/graphGroupEdits/resEdits/PyBlendEdit.cpp
    src/model/strategies/iniFixers/graphGroupEdits/resEdits/PyTexEdit.cpp
    src/model/strategies/iniFixers/graphGroupEdits/PyResRegCollect.cpp
    src/model/strategies/iniFixers/graphGroupEdits/PyResGroupCollect.cpp
    src/model/strategies/iniParsers/PyBaseIniParser.cpp
    src/model/strategies/iniParsers/PyGIMISectionClassifier.cpp
    src/model/strategies/iniParsers/PyGIMIParser.cpp
    src/model/strategies/iniFixers/PyBaseIniFixer.cpp
    src/model/strategies/iniFixers/PyGIMIFixer.cpp
    src/tools/hashing/PyHash64.cpp
    src/tools/hashing/PyHash128.cpp
    src/tools/hashing/PyHashTools.cpp
    src/model/buffers/PyBufBytes.cpp
    src/model/buffers/PyBufType.cpp
    src/model/buffers/PyBufDataType.cpp
    src/model/buffers/PyBufInt.cpp
    src/model/buffers/PyBufFloat.cpp
    src/model/buffers/PyBufUnorm.cpp
    src/model/buffers/PyBufElementType.cpp
    src/model/files/PyBinaryFile.cpp
    src/model/files/PyBufFile.cpp
    src/model/PyVGRemap.cpp
    src/model/files/PyBlendFile.cpp
    src/model/files/PyPositionFile.cpp
    src/model/textures/PyColour.cpp
    src/model/textures/PyColourRange.cpp
    src/model/files/PyTextureFile.cpp
    src/model/strategies/texEditors/pixelTransforms/PyBasePixelTransform.cpp
    src/model/strategies/texEditors/pixelTransforms/PyCorrectGamma.cpp
    src/model/strategies/texEditors/pixelTransforms/PyColourReplace.cpp
    src/model/strategies/texEditors/pixelTransforms/PyHighlightShadow.cpp
    src/model/strategies/texEditors/pixelTransforms/PyInvertAlpha.cpp
    src/model/strategies/texEditors/pixelTransforms/PyTempControl.cpp
    src/model/strategies/texEditors/pixelTransforms/PyTintTransform.cpp
    src/model/strategies/texEditors/pixelTransforms/PyTransparency.cpp
    src/model/strategies/texEditors/texFilters/PyBaseTexFilter.cpp
    src/model/strategies/texEditors/texFilters/PyGammaFilter.cpp
    src/model/strategies/texEditors/texFilters/PyTexFilterCommon.cpp
    src/model/strategies/texEditors/texFilters/PyColourReplaceFilter.cpp
    src/model/strategies/texEditors/texFilters/PyTransparencyAdjustFilter.cpp
    src/model/strategies/texEditors/texFilters/PyInvertAlphaFilter.cpp
    src/model/strategies/texEditors/texFilters/PyHueAdjust.cpp
    src/model/strategies/texEditors/texFilters/PyPixelFilter.cpp
    src/model/strategies/texEditors/PyBaseTexEditor.cpp
    src/model/strategies/texEditors/PyTexEditor.cpp
    src/model/strategies/texEditors/PyTexCreator.cpp
    src/model/stats/PyFileStats.cpp
    src/model/stats/PyCachedFileStats.cpp
    src/model/stats/PyRemapStats.cpp
    src/tools/files/PyFileDownload.cpp
    src/model/iniresources/PyIniResourceModel.cpp
    src/model/iniresources/PyIniSrcResourceModel.cpp
    src/model/iniresources/PyIniFixResourceModel.cpp
    src/model/iniresources/PyIniTexModel.cpp
    src/model/iniresources/PyIniDownloadModel.cpp
    src/model/iniresources/PyIniResource.cpp
    src/model/iniresources/PyIniGroupedResource.cpp
    src/model/iniresources/PyRemapIniResource.cpp
    src/model/iniresources/PyRemapIniGroupedResource.cpp
    src/model/iniresources/PyRemapBlendResource.cpp
    src/model/iniresources/PyRemapTexResource.cpp
)

# Forces the linker to use response files (.rsp) to bypass Windows command limits
set_target_properties(core PROPERTIES MSVC_USE_RESPONSE_FILES ON)

target_link_libraries(core PRIVATE AGRemapCore::AGRemapCore)

set_target_properties(core PROPERTIES PREFIX "")

install(TARGETS core
    LIBRARY DESTINATION FixRaidenBoss2
    RUNTIME DESTINATION FixRaidenBoss2
)

if (WIN32)
    install(FILES
        $<TARGET_FILE:z3::libz3>
        $<TARGET_FILE:utf8proc>
        $<TARGET_FILE:CURL::libcurl>
        DESTINATION FixRaidenBoss2
    )
endif()