
#
# ===== Note =====
#
# This script was auto-generated by AG Remap's ScriptBuilder tool,
#   a build system tool used in AG Remap's CI pipeline that transforms the script's
#   source code into a single script
#
# For more info, check out the Github to ScriptBuilder at:
# https://github.com/nhok0169/Anime-Game-Remap/tree/nhok0169/Tools/ScriptBuilder
#
# ***** ScriptBuilder Stats *****
#
# Version: 1.0.0
# Authors: Albert Gold#2696
# Datetime Ran: Thursday, September 10, 2026 07:56:12.786 AM UTC
# Run Hash: e1ae3981-a48c-46cd-8311-66261d76e182
# 
# *******************************
# ================
# 
# ########## START OF AUTO-GENERATED SCRIPT ##########


# ===== Anime Game Remap (AG Remap) =====
# Authors: Albert Gold#2696, NK#1321
#
# if you used it to remap your mods pls give credit for "Albert Gold#2696" and "Nhok0169"
# Special Thanks:
#   nguen#2011 (for support)
#   SilentNightSound#7430 (for internal knowdege so wrote the blendCorrection code)
#   HazrateGolabi#1364 (for being awesome, and improving the code)
#
# ***** AG Remap Script Stats *****
#
# Version: 4.5.5
# Authors: Albert Gold#2696, NK#1321
# Datetime Compiled: Thursday, September 10, 2026 07:56:12.786 AM UTC
# Build Hash: 821237d3-fe58-4c27-b8ec-c29f772e3a01
#
# *********************************
#


import os, importlib, pip._internal as pip, sys, argparse

from typing import Optional, Any, List, Callable, Dict, Tuple
from enum import Enum
from types import ModuleType



# change our current working directory to this file, allowing users to run program
#   by clicking on the script instead of running by CLI
if __name__ == "__main__":
    os.chdir(os.path.dirname(os.path.abspath(__file__)))


# note: every value below is filled in by the ScriptBuilder when this script is compiled. Running
#   this module straight out of the repo leaves the placeholders as they are, which is why
#   Tools/Script/main.py hands in its own API reference instead of relying on them.

# note: every placeholder below is a STRING on purpose. This module still has to be valid python
#   before anything is filled in -- the ScriptBuilder imports this package to work out the order to
#   write it out in, so a placeholder that is not itself parseable stops the script being built at
#   all.

# EnvName: The environment this script was built for. See BuildEnv
EnvName = "prod"

# ApiRelPath: Where the API's source folder sits relative to this script
#
# note: separated by '/' rather than by os.sep, so that a script compiled on one OS still finds the
#   API on another. Only a 'dev' build uses this.
ApiRelPath = "../../../api/src/py"

# ApiPackage: The API, both as a module to import and as an installation name on pypi
ApiPackage = "FixRaidenBoss2"


class BuildEnv(Enum):
    """
    The environment a build of this script was made for
    """

    Dev = "dev"
    """
    Reaches the API by a path on this machine, the way the tools in this repo reach each other
    """

    Prod = "prod"
    """
    Downloads the API from `pypi`_ at runtime
    """

    @classmethod
    def match(cls, name: str) -> Optional["BuildEnv"]:
        """
        Retrieves the environment by name

        Parameters
        ----------
        name: :class:`str`
            The name of the environment

        Returns
        -------
        Optional[:class:`BuildEnv`]
            The found environment, or ``None``
        """

        name = name.lower().strip()
        for env in cls:
            if (env.value == name):
                return env

        return None


class CommandOption():
    """
    A single command line option, declared once and registered in more than one place

    :raw-html:`<br />`

    .. note::
        This script has to know some of its options *before* the API exists to parse them -- whether
        to update the API's package is the option that decides whether the package gets downloaded at
        all. So each option is registered twice: once into a throwaway parser that reads it early,
        and once into the API's own command, so that it still shows up in ``--help`` next to every
        API option instead of being rejected as unrecognised.

    Parameters
    ----------
    args: Tuple[Any, ...]
        The positional arguments to hand to `argparse's add_argument`_

    kwargs: Optional[Dict[:class:`str`, Any]]
        The keyword arguments to hand to `argparse's add_argument`_
    """

    def __init__(self, args: Tuple[Any, ...], kwargs: Optional[Dict[str, Any]] = None):
        self.args = args
        self.kwargs = {} if (kwargs is None) else kwargs

    def add(self, addFunc: Callable[..., Any]):
        """
        Registers this option

        Parameters
        ----------
        addFunc: Callable[..., Any]
            The function that adds an option, taking the same arguments as
            `argparse's add_argument`_
        """

        addFunc(*self.args, **self.kwargs)


class BaseApiRef():
    """
    Base class for how a build of this script reaches the API

    :raw-html:`<br />`

    .. note::
        The script is only a thin front for the API now. It cannot simply *contain* the API any more:
        the API is a C++/Cython/python project, and a single ``.py`` file cannot carry a compiled
        extension module.

    Parameters
    ----------
    package: :class:`str`
        The API, both as a module to import and as an installation name

    Attributes
    ----------
    package: :class:`str`
        The API, both as a module to import and as an installation name
    """

    def __init__(self, package: str):
        self.package = package

    def getOptions(self) -> List[CommandOption]:
        """
        The command line options this way of reaching the API needs

        Returns
        -------
        List[:class:`CommandOption`]
            The options, which are empty for a reference that needs none
        """

        return []

    def prepare(self, args: Any):
        """
        Makes the API importable

        Parameters
        ----------
        args: `Namespace`_
            This script's own options, already read
        """

        pass

    def load(self, args: Any) -> ModuleType:
        """
        Retrieves the API

        Parameters
        ----------
        args: `Namespace`_
            This script's own options, already read

        Returns
        -------
        `Module`_
            The API's module
        """

        self.prepare(args)
        return importlib.import_module(self.package)


class CommandOpts(Enum):
    """
    The options this script adds on top of the API's own
    """

    Update = "--update"
    PreRelease = "--preRelease"


class ShortCommandOpts(Enum):
    """
    The short forms of the options this script adds on top of the API's own
    """

    Update = "-up"
    PreRelease = "-pre"


class PackageApiRef(BaseApiRef):
    """
    This class inherits from :class:`BaseApiRef`

    :raw-html:`<br />`

    Downloads the API from `pypi`_ at runtime, the same shape as the API's own ``PackageManager``:
    try to import it, and only reach for `pip`_ when it is not there

    Parameters
    ----------
    package: :class:`str`
        The API, both as a module to import and as an installation name
    """

    def getOptions(self) -> List[CommandOption]:
        return [
            CommandOption((ShortCommandOpts.Update.value, CommandOpts.Update.value),
                          {"action": "store_true",
                           "help": f"Updates '{self.package}' to its latest version before running. Without this option, the package is only downloaded when it is not already installed."}),

            CommandOption((ShortCommandOpts.PreRelease.value, CommandOpts.PreRelease.value),
                          {"action": "store_true",
                           "help": f"Also considers prereleases of '{self.package}' when downloading it"})
        ]

    def getInstallOptions(self, args: Any) -> List[str]:
        """
        The options handed to `pip`_ for the download

        Parameters
        ----------
        args: `Namespace`_
            This script's own options, already read

        Returns
        -------
        List[:class:`str`]
            The options
        """

        result = ["install", "-U"]

        if (getattr(args, "preRelease", False)):
            result.append("--pre")

        return result + [self.package]

    def isInstalled(self) -> bool:
        """
        Whether the API can already be imported

        Returns
        -------
        :class:`bool`
            Whether the API is available
        """

        try:
            importlib.import_module(self.package)
        except ModuleNotFoundError:
            return False

        return True

    def prepare(self, args: Any):
        update = getattr(args, "update", False)

        if (not update and self.isInstalled()):
            return

        print(f"Downloading the latest version of '{self.package}'...")
        pip.main(self.getInstallOptions(args))

        # a package installed during this run is not on any import path that was cached before it
        #   arrived, so the caches have to be dropped before the import below can find it
        importlib.invalidate_caches()


class PathApiRef(BaseApiRef):
    """
    This class inherits from :class:`BaseApiRef`

    :raw-html:`<br />`

    Reaches the API by a path on this machine, the way every tool in this repo reaches the others

    Parameters
    ----------
    package: :class:`str`
        The API, both as a module to import and as an installation name

    apiPath: Optional[:class:`str`]
        The folder holding the API's package :raw-html:`<br />` :raw-html:`<br />`

        When this is ``None``, the path is worked out from where this script sits, using the
        relative path the ScriptBuilder compiled in :raw-html:`<br />` :raw-html:`<br />`

        **Default**: ``None``
    """

    def __init__(self, package: str, apiPath: Optional[str] = None):
        super().__init__(package)
        self._apiPath = apiPath

    def getApiPath(self) -> str:
        """
        The folder holding the API's package

        Returns
        -------
        :class:`str`
            The folder
        """

        if (self._apiPath is not None):
            return self._apiPath

        scriptFolder = os.path.dirname(os.path.abspath(__file__))
        return os.path.abspath(os.path.join(scriptFolder, *ApiRelPath.split("/")))

    def prepare(self, args: Any):
        apiPath = self.getApiPath()

        if (not os.path.isdir(apiPath)):
            raise FileNotFoundError(f"This is a 'dev' build of the script, which expects the API's source at: {apiPath}")

        sys.path.insert(1, apiPath)


class ApiRefBuilder():
    """
    Picks how this build of the script reaches the API
    """

    @classmethod
    def build(cls) -> BaseApiRef:
        """
        Retrieves the way this build of the script reaches the API

        Returns
        -------
        :class:`BaseApiRef`
            How to reach the API
        """

        if (BuildEnv.match(EnvName) == BuildEnv.Prod):
            return PackageApiRef(ApiPackage)

        return PathApiRef(ApiPackage)


class CommandBuilder():
    """
    Handles the options this script adds on top of the API's own

    Parameters
    ----------
    options: Optional[List[:class:`CommandOption`]]
        The options to add :raw-html:`<br />` :raw-html:`<br />`

        **Default**: ``None``
    """

    def __init__(self, options: Optional[List[CommandOption]] = None):
        self.options = [] if (options is None) else options

    def preParse(self, argv: Optional[List[str]] = None) -> Tuple[Any, List[str]]:
        """
        Reads only this script's own options, leaving everything else for the API

        :raw-html:`<br />`

        .. note::
            Abbreviations are off. With them on, argparse would happily match a shortened form of an
            *API* option onto one of ours and swallow it.

        Parameters
        ----------
        argv: Optional[List[:class:`str`]]
            The command line arguments to read :raw-html:`<br />` :raw-html:`<br />`

            **Default**: ``None``

        Returns
        -------
        Tuple[`Namespace`_, List[:class:`str`]]
            The options that were read, and the arguments left over
        """

        parser = argparse.ArgumentParser(add_help = False, allow_abbrev = False)
        for option in self.options:
            option.add(parser.add_argument)

        return parser.parse_known_args(argv)

    def addTo(self, command: Any):
        """
        Registers this script's options into the API's command, so they appear in the same
        ``--help`` as the API's own options

        Parameters
        ----------
        command: :class:`CommandBuilder`
            The API's command builder
        """

        for option in self.options:
            option.add(command.addArgument)


def remapMain(apiRef: Optional[BaseApiRef] = None):
    """
    Runs the script

    :raw-html:`<br />`

    The script does not do the remapping itself -- it makes the API available and then hands the
    command line straight to it

    Parameters
    ----------
    apiRef: Optional[:class:`BaseApiRef`]
        How to reach the API :raw-html:`<br />` :raw-html:`<br />`

        When this is ``None``, whichever reference this script was compiled for is used. Running
        this out of the repo rather than from a compiled script is the case that passes one in,
        since the compiled-in values do not exist yet :raw-html:`<br />` :raw-html:`<br />`

        **Default**: ``None``
    """

    if (apiRef is None):
        apiRef = ApiRefBuilder.build()

    command = CommandBuilder(apiRef.getOptions())

    # this script's own options have to be read before the API is fetched, since one of them decides
    #   whether the API gets downloaded at all. They are handed to the API's command afterwards so
    #   that they still appear in its --help rather than being rejected there as unrecognised.
    args, remainingArgs = command.preParse()

    api = apiRef.load(args)
    api.remapMain(commandSetup = command.addTo)


# Main Driver Code
if __name__ == "__main__":
    remapMain()

########### END OF AUTO-GENERATED SCRIPT ###########