
#
# ===== Note =====
#
# This library was auto-generated by AG Remap's APIMirrorBuilder tool,
#   a build system tool used in AG Remap's CI pipeline that creates a mirror for the existing
#   API source code since we cannot rename the original name of 'FixRaidenBoss2' to 'Anime Game Remap' in Pypi,
#   therefore, we decided to make a brand new package that mirrors the original API.
#
# ***** APIMirrorBuilder Stats *****
#
# Version: 1.0.0
# Authors: Albert Gold#2696
# Datetime Ran: Thursday, October 01, 2026 07:57:17.183 PM UTC
# Run Hash: bdf66e63-518f-4378-ba7f-40c6d5ed6db9
# 
# **********************************
# ================
#

# ===== Anime Game Remap (AG Remap) =====
# Authors: Albert Gold#2696, NK#1321
#
# if you used it to remap your mods pls give credit for "Albert Gold#2696" and "Nhok0169"
# Special Thanks:
#   nguen#2011 (for support)
#   SilentNightSound#7430 (for internal knowdege so wrote the blendCorrection code)
#   HazrateGolabi#1364 (for being awesome, and improving the code)

#
# ***** AG Remap Stats *****
#
# Version: 5.0.0a2
# Authors: Albert Gold#2696, NK#1321
# Datetime Compiled: Thursday, October 01, 2026 07:57:17.183 PM UTC
# Build Hash: 26414e22-8390-4f56-be8a-5c7572a7b70b
#
# **************************
#

from FixRaidenBoss2 import remapMain

if __name__ == '__main__':
    remapMain()