
#
# ===== Note =====
#
# This library was auto-generated by AG Remap's APIMirrorBuilder tool,
#   a build system tool used in AG Remap's CI pipeline that creates a mirror for the existing
#   API source code since we cannot rename the original name of 'FixRaidenBoss2' to 'Anime Game Remap' in Pypi,
#   therefore, we decided to make a brand new package that mirrors the original API.
#
# ***** APIMirrorBuilder Stats *****
#
# Version: 1.0.0
# Authors: Albert Gold#2696
# Datetime Ran: Thursday, September 17, 2026 10:28:21.874 PM UTC
# Run Hash: 7b88eafd-f570-463b-8c58-96836499d0d0
# 
# **********************************
# ================
#

# ===== Anime Game Remap (AG Remap) =====
# Authors: Albert Gold#2696, NK#1321
#
# if you used it to remap your mods pls give credit for "Albert Gold#2696" and "Nhok0169"
# Special Thanks:
#   nguen#2011 (for support)
#   SilentNightSound#7430 (for internal knowdege so wrote the blendCorrection code)
#   HazrateGolabi#1364 (for being awesome, and improving the code)

#
# ***** AG Remap Stats *****
#
# Version: 5.0.0a1
# Authors: Albert Gold#2696, NK#1321
# Datetime Compiled: Thursday, September 17, 2026 10:28:21.874 PM UTC
# Build Hash: 0c6f2d8c-b726-49de-a983-f58e8b588050
#
# **************************
#

from FixRaidenBoss2 import remapMain

if __name__ == '__main__':
    remapMain()