name: Unit Tests

on:
  workflow_call:

jobs:
  run-tests:
    name: Run Unit Tester
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ">=3.6"
    - name: Install Tester Dependencies
      run: python3 -m pip install -r requirements.txt
      working-directory: './Testing/Unit Tester'
    - name: Run Unit Tests
      run: python3 main.py
      working-directory: './Testing/Unit Tester'
    
